-- Reports chapter strings
-- Languages: en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('rpt_title',
    'Reports',
    'Informes',
    'Berichte',
    '报告',
    'Rapports',
    'Relatórios',
    'レポート',
    'Báo cáo',
    'Rapporten',
    'Jelentések',
    'التقارير',
    'گزارش‌ها',
    'Raporlar',
    '보고서',
    'รายงาน',
    'အစီရင်ခံစာများ',
    'Тайлангууд',
    '',
    'Raporty');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('rpt_intro',
    '`precc report` generates an analytics dashboard summarizing PRECC activity and token savings.',
    '`precc report` genera un panel analítico que resume la actividad de PRECC y el ahorro de tokens.',
    '`precc report` erstellt ein Analyse-Dashboard, das PRECC-Aktivität und Token-Einsparungen zusammenfasst.',
    '`precc report` 生成一个分析仪表板，总结 PRECC 活动和 token 节省情况。',
    '`precc report` génère un tableau de bord analytique résumant l''activité PRECC et les économies de tokens.',
    '`precc report` gera um painel analítico resumindo a atividade do PRECC e a economia de tokens.',
    '`precc report` は PRECC の活動とトークン節約をまとめた分析ダッシュボードを生成します。',
    '`precc report` tạo bảng điều khiển phân tích tóm tắt hoạt động PRECC và token tiết kiệm được.',
    '`precc report` genereert een analytisch dashboard dat PRECC-activiteit en tokenbesparingen samenvat.',
    'A `precc report` egy elemzési irányítópultot generál, amely összefoglalja a PRECC tevékenységét és a tokenmegtakarításokat.',
    'يُنشئ `precc report` لوحة تحليلات تلخص نشاط PRECC وتوفير الرموز.',
    '`precc report` یک داشبورد تحلیلی تولید می‌کند که فعالیت PRECC و صرفه‌جویی توکن را خلاصه می‌کند.',
    '`precc report` PRECC etkinliğini ve token tasarruflarını özetleyen bir analiz panosu oluşturur.',
    '`precc report`는 PRECC 활동과 토큰 절감을 요약하는 분석 대시보드를 생성합니다.',
    '`precc report` สร้างแดชบอร์ดวิเคราะห์ที่สรุปกิจกรรม PRECC และการประหยัดโทเค็น',
    '`precc report` သည် PRECC လုပ်ဆောင်ချက်နှင့် token ချွေတာမှုကို အကျဉ်းချုပ် ခွဲခြမ်းစိတ်ဖြာမှု ဒတ်ရှ်ဘုတ် ဖန်တီးသည်။',
    '`precc report` нь PRECC-ийн үйл ажиллагаа болон токен хэмнэлтийг нэгтгэсэн аналитик хянах самбар үүсгэнэ.',
    '',
    '`precc report` generuje panel analityczny podsumowujący aktywność PRECC i oszczędności tokenów.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('rpt_generating_title',
    'Generating a Report',
    'Generar un informe',
    'Einen Bericht erstellen',
    '生成报告',
    'Générer un rapport',
    'Gerando um relatório',
    'レポートの生成',
    'Tạo báo cáo',
    'Een rapport genereren',
    'Jelentés készítése',
    'إنشاء تقرير',
    'ایجاد گزارش',
    'Rapor oluşturma',
    '보고서 생성',
    'การสร้างรายงาน',
    'အစီရင်ခံစာ ဖန်တီးခြင်း',
    'Тайлан үүсгэх',
    '',
    'Generowanie raportu');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('rpt_email_title',
    'Emailing a Report',
    'Enviar un informe por correo',
    'Einen Bericht per E-Mail senden',
    '通过电子邮件发送报告',
    'Envoyer un rapport par e-mail',
    'Enviando um relatório por e-mail',
    'レポートのメール送信',
    'Gửi báo cáo qua email',
    'Een rapport e-mailen',
    'Jelentés küldése e-mailben',
    'إرسال تقرير بالبريد الإلكتروني',
    'ارسال گزارش با ایمیل',
    'Raporu e-postayla gönderme',
    '보고서 이메일 전송',
    'ส่งรายงานทางอีเมล',
    'အစီရင်ခံစာကို အီးမေးလ် ပို့ခြင်း',
    'Тайланг имэйлээр илгээх',
    '',
    'Wysyłanie raportu e-mailem');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('rpt_email_body',
    'Send the report to an email address (requires mail setup, see [Email](email.md)):',
    'Envía el informe a una dirección de correo (requiere configuración de correo, ver [Email](email.md)):',
    'Senden Sie den Bericht an eine E-Mail-Adresse (erfordert Mail-Einrichtung, siehe [Email](email.md)):',
    '将报告发送到电子邮件地址（需要邮件设置，见 [Email](email.md)）：',
    'Envoyez le rapport à une adresse e-mail (nécessite la configuration du courrier, voir [Email](email.md)) :',
    'Envie o relatório para um endereço de e-mail (requer configuração de e-mail, veja [Email](email.md)):',
    'レポートをメールアドレスに送信（メール設定が必要、[Email](email.md) 参照）：',
    'Gửi báo cáo đến địa chỉ email (yêu cầu thiết lập mail, xem [Email](email.md)):',
    'Stuur het rapport naar een e-mailadres (vereist mailconfiguratie, zie [Email](email.md)):',
    'Küldje el a jelentést egy e-mail címre (levelezés beállítása szükséges, lásd [Email](email.md)):',
    'أرسل التقرير إلى عنوان بريد إلكتروني (يتطلب إعداد البريد، راجع [Email](email.md)):',
    'گزارش را به آدرس ایمیل ارسال کنید (نیاز به تنظیمات ایمیل دارد، به [Email](email.md) مراجعه کنید):',
    'Raporu bir e-posta adresine gönderin (posta kurulumu gerekir, bkz. [Email](email.md)):',
    '이메일 주소로 보고서 전송 (메일 설정 필요, [Email](email.md) 참조):',
    'ส่งรายงานไปยังที่อยู่อีเมล (ต้องตั้งค่าอีเมล ดู [Email](email.md)):',
    'အစီရင်ခံစာကို အီးမေးလ်လိပ်စာသို့ ပို့ပါ (မေးလ်ဆက်တင် လိုအပ်သည်၊ [Email](email.md) ကြည့်ပါ):',
    'Тайланг имэйл хаяг руу илгээнэ үү (шуудангийн тохиргоо шаардлагатай, [Email](email.md)-г үзнэ үү):',
    '',
    'Wyślij raport na adres e-mail (wymaga konfiguracji poczty, zobacz [Email](email.md)):');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('rpt_email_config',
    'The recipient address is read from `~/.config/precc/mail.toml`. You can also use `precc mail report EMAIL` to send to a specific address.',
    'La dirección del destinatario se lee de `~/.config/precc/mail.toml`. También puedes usar `precc mail report EMAIL` para enviar a una dirección específica.',
    'Die Empfängeradresse wird aus `~/.config/precc/mail.toml` gelesen. Sie können auch `precc mail report EMAIL` verwenden, um an eine bestimmte Adresse zu senden.',
    '收件人地址从 `~/.config/precc/mail.toml` 读取。您也可以使用 `precc mail report EMAIL` 发送到特定地址。',
    'L''adresse du destinataire est lue depuis `~/.config/precc/mail.toml`. Vous pouvez aussi utiliser `precc mail report EMAIL` pour envoyer à une adresse spécifique.',
    'O endereço do destinatário é lido de `~/.config/precc/mail.toml`. Você também pode usar `precc mail report EMAIL` para enviar para um endereço específico.',
    '受信者アドレスは `~/.config/precc/mail.toml` から読み取られます。`precc mail report EMAIL` を使って特定のアドレスに送信することもできます。',
    'Địa chỉ người nhận được đọc từ `~/.config/precc/mail.toml`. Bạn cũng có thể dùng `precc mail report EMAIL` để gửi đến địa chỉ cụ thể.',
    'Het ontvangersadres wordt gelezen uit `~/.config/precc/mail.toml`. U kunt ook `precc mail report EMAIL` gebruiken om naar een specifiek adres te sturen.',
    'A címzett címe a `~/.config/precc/mail.toml` fájlból olvasható. A `precc mail report EMAIL` paranccsal is küldhet adott címre.',
    'يُقرأ عنوان المستلم من `~/.config/precc/mail.toml`. يمكنك أيضًا استخدام `precc mail report EMAIL` للإرسال إلى عنوان محدد.',
    'آدرس گیرنده از `~/.config/precc/mail.toml` خوانده می‌شود. همچنین می‌توانید از `precc mail report EMAIL` برای ارسال به آدرس خاص استفاده کنید.',
    'Alıcı adresi `~/.config/precc/mail.toml` dosyasından okunur. Belirli bir adrese göndermek için `precc mail report EMAIL` de kullanabilirsiniz.',
    '수신자 주소는 `~/.config/precc/mail.toml`에서 읽힙니다. `precc mail report EMAIL`을 사용하여 특정 주소로 보낼 수도 있습니다.',
    'ที่อยู่ผู้รับอ่านจาก `~/.config/precc/mail.toml` คุณยังสามารถใช้ `precc mail report EMAIL` เพื่อส่งไปยังที่อยู่เฉพาะ',
    'လက်ခံသူလိပ်စာကို `~/.config/precc/mail.toml` မှ ဖတ်သည်။ သီးခြားလိပ်စာသို့ ပို့ရန် `precc mail report EMAIL` ကိုလည်း သုံးနိုင်သည်။',
    'Хүлээн авагчийн хаягийг `~/.config/precc/mail.toml`-аас уншина. Тодорхой хаяг руу илгээхийн тулд `precc mail report EMAIL`-г ашиглаж болно.',
    '',
    'Adres odbiorcy jest odczytywany z `~/.config/precc/mail.toml`. Możesz też użyć `precc mail report EMAIL`, aby wysłać na konkretny adres.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('rpt_data_title',
    'Report Data',
    'Datos del informe',
    'Berichtsdaten',
    '报告数据',
    'Données du rapport',
    'Dados do relatório',
    'レポートデータ',
    'Dữ liệu báo cáo',
    'Rapportgegevens',
    'Jelentésadatok',
    'بيانات التقرير',
    'داده‌های گزارش',
    'Rapor verileri',
    '보고서 데이터',
    'ข้อมูลรายงาน',
    'အစီရင်ခံစာ ဒေတာ',
    'Тайлангийн өгөгдөл',
    '',
    'Dane raportu');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('rpt_data_body',
    'Reports are generated from the local PRECC database at `~/.local/share/precc/history.db`. No data leaves your machine unless you explicitly email the report.',
    'Los informes se generan desde la base de datos local de PRECC en `~/.local/share/precc/history.db`. Ningún dato sale de tu máquina a menos que envíes el informe por correo explícitamente.',
    'Berichte werden aus der lokalen PRECC-Datenbank unter `~/.local/share/precc/history.db` generiert. Keine Daten verlassen Ihren Rechner, es sei denn, Sie senden den Bericht explizit per E-Mail.',
    '报告从本地 PRECC 数据库 `~/.local/share/precc/history.db` 生成。除非您明确通过电子邮件发送报告，否则没有数据离开您的机器。',
    'Les rapports sont générés à partir de la base de données PRECC locale dans `~/.local/share/precc/history.db`. Aucune donnée ne quitte votre machine sauf si vous envoyez explicitement le rapport par e-mail.',
    'Relatórios são gerados a partir do banco de dados PRECC local em `~/.local/share/precc/history.db`. Nenhum dado sai da sua máquina a menos que você envie o relatório por e-mail explicitamente.',
    'レポートは `~/.local/share/precc/history.db` のローカル PRECC データベースから生成されます。レポートを明示的にメール送信しない限り、データはマシンから出ません。',
    'Báo cáo được tạo từ cơ sở dữ liệu PRECC cục bộ tại `~/.local/share/precc/history.db`. Không có dữ liệu nào rời khỏi máy của bạn trừ khi bạn gửi báo cáo qua email.',
    'Rapporten worden gegenereerd uit de lokale PRECC-database op `~/.local/share/precc/history.db`. Er verlaat geen data uw machine tenzij u het rapport expliciet e-mailt.',
    'A jelentések a helyi PRECC adatbázisból generálódnak: `~/.local/share/precc/history.db`. Semmilyen adat nem hagyja el a gépet, hacsak nem küldi el kifejezetten e-mailben a jelentést.',
    'يتم إنشاء التقارير من قاعدة بيانات PRECC المحلية في `~/.local/share/precc/history.db`. لا تغادر أي بيانات جهازك ما لم ترسل التقرير بالبريد الإلكتروني صراحةً.',
    'گزارش‌ها از پایگاه داده محلی PRECC در `~/.local/share/precc/history.db` تولید می‌شوند. هیچ داده‌ای از دستگاه شما خارج نمی‌شود مگر اینکه صراحتاً گزارش را ایمیل کنید.',
    'Raporlar `~/.local/share/precc/history.db` adresindeki yerel PRECC veritabanından oluşturulur. Raporu açıkça e-postayla göndermediğiniz sürece hiçbir veri makinenizden çıkmaz.',
    '보고서는 `~/.local/share/precc/history.db`의 로컬 PRECC 데이터베이스에서 생성됩니다. 보고서를 명시적으로 이메일로 보내지 않는 한 데이터는 머신을 떠나지 않습니다.',
    'รายงานสร้างจากฐานข้อมูล PRECC ในเครื่องที่ `~/.local/share/precc/history.db` ไม่มีข้อมูลออกจากเครื่องของคุณเว้นแต่คุณจะส่งรายงานทางอีเมลอย่างชัดเจน',
    'အစီရင်ခံစာများကို `~/.local/share/precc/history.db` ရှိ ဒေသတွင်း PRECC ဒေတာဘေ့စ်မှ ဖန်တီးသည်။ အစီရင်ခံစာကို အီးမေးလ်ဖြင့် တိကျစွာ မပို့မချင်း ဒေတာသည် သင့်စက်မှ မထွက်ပါ။',
    'Тайлангууд `~/.local/share/precc/history.db` дахь локал PRECC мэдээллийн сангаас үүсгэгддэг. Тайланг имэйлээр илгээхээс бусад тохиолдолд ямар ч өгөгдөл таны компьютерээс гарахгүй.',
    '',
    'Raporty są generowane z lokalnej bazy danych PRECC w `~/.local/share/precc/history.db`. Żadne dane nie opuszczają Twojego komputera, chyba że jawnie wyślesz raport e-mailem.');
