-- Savings chapter strings
INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_title',
    'Savings',
    'Ahorros',
    'Einsparungen',
    '节省',
    'Économies',
    'Economia',
    '節約',
    'Tiết kiệm',
    'Besparingen',
    'Megtakarítások',
    'التوفير',
    'صرفه‌جویی',
    'Tasarruflar',
    '절약',
    'การประหยัด',
    'ချွေတာမှု',
    'Хэмнэлт',
    '',
    'Oszczędności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_intro',
    'PRECC tracks estimated token savings from every interception. Use `precc savings` to see how much waste PRECC has prevented.',
    'PRECC rastrea el ahorro estimado de tokens de cada intercepción. Usa `precc savings` para ver cuánto desperdicio ha evitado PRECC.',
    'PRECC verfolgt die geschätzten Token-Einsparungen bei jeder Interception. Verwenden Sie `precc savings`, um zu sehen, wie viel Verschwendung PRECC verhindert hat.',
    'PRECC追踪每次拦截的估计token节省。使用 `precc savings` 查看PRECC阻止了多少浪费。',
    'PRECC suit les économies de tokens estimées à chaque interception. Utilisez `precc savings` pour voir combien de gaspillage PRECC a évité.',
    'PRECC rastreia a economia estimada de tokens em cada intercepção. Use `precc savings` para ver quanto desperdício PRECC evitou.',
    'PRECCは各インターセプションから推定されるトークン節約を追跡します。`precc savings` を使用して、PRECCがどれだけの無駄を防いだかを確認してください。',
    'PRECC theo dõi token tiết kiệm ước tính từ mỗi lần chặn. Dùng `precc savings` để xem PRECC đã ngăn được bao nhiêu lãng phí.',
    'PRECC houdt geschatte tokenbesparingen bij van elke onderschepping. Gebruik `precc savings` om te zien hoeveel verspilling PRECC heeft voorkomen.',
    'A PRECC nyomon követi a becsült token-megtakarításokat minden elfogásnál. Használja a `precc savings` parancsot a megelőzött pazarlás megtekintéséhez.',
    'يتتبع PRECC التوفير المقدر في الرموز من كل اعتراض. استخدم `precc savings` لمعرفة مقدار الهدر الذي منعه PRECC.',
    'PRECC صرفه‌جویی تخمینی توکن‌ها را از هر رهگیری پیگیری می‌کند. از `precc savings` برای مشاهده میزان اتلاف جلوگیری‌شده استفاده کنید.',
    'PRECC, her müdahaleden elde edilen tahmini token tasarrufunu takip eder. PRECC''nin ne kadar israfı önlediğini görmek için `precc savings` kullanın.',
    'PRECC는 매 인터셉션에서 추정 토큰 절약량을 추적합니다. `precc savings`를 사용하여 PRECC가 얼마나 낭비를 방지했는지 확인하세요.',
    'PRECC ติดตามการประหยัดโทเค็นโดยประมาณจากทุกการสกัดกั้น ใช้ `precc savings` เพื่อดูว่า PRECC ป้องกันการสูญเสียได้เท่าไร',
    'PRECC သည် ကြားဖြတ်မှုတိုင်းမှ ခန့်မှန်းတိုကင်ချွေတာမှုကို ခြေရာခံသည်။ PRECC မည်မျှ ဖြုန်းတီးမှုကို တားဆီးခဲ့သည်ကို ကြည့်ရန် `precc savings` ကို သုံးပါ။',
    'PRECC нь таслан зогсоолт бүрээс хэмнэсэн токены тооцоог хянадаг. PRECC хэдий хэмжээний үрэлгэнгээс сэргийлснийг харахын тулд `precc savings` ашиглана уу.',
    '',
    'PRECC śledzi szacowane oszczędności tokenów z każdego przechwycenia. Użyj `precc savings`, aby zobaczyć ile marnotrawstwa PRECC zapobiegł.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_quick_summary_title',
    'Quick Summary',
    'Resumen rápido',
    'Kurzübersicht',
    '快速摘要',
    'Résumé rapide',
    'Resumo rápido',
    'クイックサマリー',
    'Tóm tắt nhanh',
    'Snel overzicht',
    'Gyors összefoglaló',
    'ملخص سريع',
    'خلاصه سریع',
    'Hızlı özet',
    '빠른 요약',
    'สรุปย่อ',
    'အကျဉ်းချုပ်',
    'Товч тойм',
    '',
    'Szybkie podsumowanie');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_detailed_title',
    'Detailed Breakdown (Pro)',
    'Desglose detallado (Pro)',
    'Detaillierte Aufschlüsselung (Pro)',
    '详细分类（Pro）',
    'Ventilation détaillée (Pro)',
    'Detalhamento completo (Pro)',
    '詳細内訳（Pro）',
    'Phân tích chi tiết (Pro)',
    'Gedetailleerd overzicht (Pro)',
    'Részletes bontás (Pro)',
    'تفصيل مفصل (Pro)',
    'جزئیات کامل (Pro)',
    'Ayrıntılı döküm (Pro)',
    '상세 분석 (Pro)',
    'รายละเอียด (Pro)',
    'အသေးစိတ်ခွဲခြမ်းစိတ်ဖြာမှု (Pro)',
    'Дэлгэрэнгүй задаргаа (Pro)',
    '',
    'Szczegółowy rozkład (Pro)');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_how_title',
    'How Savings Are Estimated',
    'Cómo se estiman los ahorros',
    'Wie Einsparungen geschätzt werden',
    '如何估算节省',
    'Comment les économies sont estimées',
    'Como as economias são estimadas',
    '節約の推定方法',
    'Cách ước tính tiết kiệm',
    'Hoe besparingen worden geschat',
    'Hogyan becsüljük a megtakarításokat',
    'كيف يتم تقدير التوفير',
    'نحوه تخمین صرفه‌جویی',
    'Tasarruflar nasıl tahmin edilir',
    '절약량 추정 방법',
    'วิธีประมาณการประหยัด',
    'ချွေတာမှုကို ခန့်မှန်းပုံ',
    'Хэмнэлтийг хэрхэн тооцоолох',
    '',
    'Jak szacowane są oszczędności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_how_intro',
    'Each correction type has an estimated token cost based on what would have happened without PRECC:',
    'Cada tipo de corrección tiene un costo estimado de tokens basado en lo que habría ocurrido sin PRECC:',
    'Jeder Korrekturtyp hat geschätzte Token-Kosten basierend darauf, was ohne PRECC passiert wäre:',
    '每种修正类型都有基于没有PRECC时会发生什么的估计token成本：',
    'Chaque type de correction a un coût estimé en tokens basé sur ce qui se serait passé sans PRECC :',
    'Cada tipo de correção tem um custo estimado de tokens baseado no que teria acontecido sem PRECC:',
    '各修正タイプには、PRECCなしで何が起こったかに基づく推定トークンコストがあります：',
    'Mỗi loại sửa lỗi có chi phí token ước tính dựa trên những gì sẽ xảy ra nếu không có PRECC:',
    'Elk correctietype heeft een geschatte tokenkost op basis van wat er zonder PRECC zou zijn gebeurd:',
    'Minden javítási típusnak van egy becsült token-költsége azon alapulva, mi történt volna PRECC nélkül:',
    'لكل نوع تصحيح تكلفة تقديرية بالرموز بناءً على ما كان سيحدث بدون PRECC:',
    'هر نوع اصلاح دارای هزینه تخمینی توکن بر اساس آنچه بدون PRECC رخ می‌داد است:',
    'Her düzeltme türünün, PRECC olmadan ne olacağına dayalı tahmini bir token maliyeti vardır:',
    '각 수정 유형에는 PRECC 없이 발생했을 상황을 기반으로 한 예상 토큰 비용이 있습니다:',
    'การแก้ไขแต่ละประเภทมีค่าโทเค็นโดยประมาณตามสิ่งที่จะเกิดขึ้นหากไม่มี PRECC:',
    'ပြင်ဆင်မှု အမျိုးအစားတစ်ခုစီတွင် PRECC မရှိလျှင် ဖြစ်မည့်အရာအပေါ် အခြေခံ၍ ခန့်မှန်းတိုကင်ကုန်ကျစရိတ်ရှိသည်:',
    'Засварын төрөл бүр PRECC-гүй бол юу болох байсанд үндэслэсэн тооцоолсон токен зардалтай:',
    '',
    'Każdy typ korekty ma szacowany koszt tokenów na podstawie tego, co by się stało bez PRECC:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_col_type',
    'Correction Type',
    'Tipo de corrección',
    'Korrekturtyp',
    '修正类型',
    'Type de correction',
    'Tipo de correção',
    '修正タイプ',
    'Loại sửa lỗi',
    'Correctietype',
    'Javítás típusa',
    'نوع التصحيح',
    'نوع اصلاح',
    'Düzeltme türü',
    '수정 유형',
    'ประเภทการแก้ไข',
    'ပြင်ဆင်မှုအမျိုးအစား',
    'Засварын төрөл',
    '',
    'Typ korekty');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_col_saving',
    'Estimated Saving',
    'Ahorro estimado',
    'Geschätzte Einsparung',
    '估计节省',
    'Économie estimée',
    'Economia estimada',
    '推定節約',
    'Tiết kiệm ước tính',
    'Geschatte besparing',
    'Becsült megtakarítás',
    'التوفير المقدر',
    'صرفه‌جویی تخمینی',
    'Tahmini tasarruf',
    '예상 절약',
    'การประหยัดโดยประมาณ',
    'ခန့်မှန်းချွေတာမှု',
    'Тооцоолсон хэмнэлт',
    '',
    'Szacowana oszczędność');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_col_reasoning',
    'Reasoning',
    'Razonamiento',
    'Begründung',
    '原因',
    'Raisonnement',
    'Justificativa',
    '理由',
    'Lý do',
    'Redenering',
    'Indoklás',
    'التبرير',
    'دلیل',
    'Gerekçe',
    '근거',
    'เหตุผล',
    'အကြောင်းပြချက်',
    'Шалтгаан',
    '',
    'Uzasadnienie');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_reason_cd',
    'Error output + Claude reasoning + retry',
    'Salida de error + razonamiento de Claude + reintento',
    'Fehlerausgabe + Claude-Reasoning + Wiederholung',
    '错误输出 + Claude推理 + 重试',
    'Sortie d''erreur + raisonnement de Claude + nouvelle tentative',
    'Saída de erro + raciocínio do Claude + retry',
    'エラー出力 + Claudeの推論 + リトライ',
    'Đầu ra lỗi + suy luận của Claude + thử lại',
    'Foutuitvoer + Claude-redenering + herpoging',
    'Hibakimenet + Claude gondolkodás + újrapróbálás',
    'مخرجات الخطأ + تفكير Claude + إعادة المحاولة',
    'خروجی خطا + استدلال Claude + تلاش مجدد',
    'Hata çıktısı + Claude muhakemesi + yeniden deneme',
    '오류 출력 + Claude 추론 + 재시도',
    'ผลลัพธ์ข้อผิดพลาด + การให้เหตุผลของ Claude + ลองใหม่',
    'အမှားရလဒ် + Claude ဆင်ခြင်မှု + ပြန်ကြိုးစားမှု',
    'Алдааны гаралт + Claude-ийн дүгнэлт + дахин оролдлого',
    '',
    'Wyjście błędu + rozumowanie Claude + ponowna próba');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_skill_activation',
    'Skill activation',
    'Activación de habilidad',
    'Skill-Aktivierung',
    '技能激活',
    'Activation de compétence',
    'Ativação de habilidade',
    'スキルアクティベーション',
    'Kích hoạt kỹ năng',
    'Vaardigheidactivatie',
    'Képesség aktiválás',
    'تفعيل المهارة',
    'فعال‌سازی مهارت',
    'Beceri etkinleştirme',
    '스킬 활성화',
    'การเปิดใช้ทักษะ',
    'ကျွမ်းကျင်မှုအသက်သွင်းခြင်း',
    'Ур чадварыг идэвхжүүлэх',
    '',
    'Aktywacja umiejętności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_reason_skill',
    'Error output + Claude reasoning + retry',
    'Salida de error + razonamiento de Claude + reintento',
    'Fehlerausgabe + Claude-Reasoning + Wiederholung',
    '错误输出 + Claude推理 + 重试',
    'Sortie d''erreur + raisonnement de Claude + nouvelle tentative',
    'Saída de erro + raciocínio do Claude + retry',
    'エラー出力 + Claudeの推論 + リトライ',
    'Đầu ra lỗi + suy luận của Claude + thử lại',
    'Foutuitvoer + Claude-redenering + herpoging',
    'Hibakimenet + Claude gondolkodás + újrapróbálás',
    'مخرجات الخطأ + تفكير Claude + إعادة المحاولة',
    'خروجی خطا + استدلال Claude + تلاش مجدد',
    'Hata çıktısı + Claude muhakemesi + yeniden deneme',
    '오류 출력 + Claude 추론 + 재시도',
    'ผลลัพธ์ข้อผิดพลาด + การให้เหตุผลของ Claude + ลองใหม่',
    'အမှားရလဒ် + Claude ဆင်ခြင်မှု + ပြန်ကြိုးစားမှု',
    'Алдааны гаралт + Claude-ийн дүгнэлт + дахин оролдлого',
    '',
    'Wyjście błędu + rozumowanie Claude + ponowna próba');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_reason_rtk',
    'Verbose output that Claude would have to read',
    'Salida verbose que Claude tendría que leer',
    'Ausführliche Ausgabe, die Claude lesen müsste',
    'Claude需要阅读的冗长输出',
    'Sortie verbose que Claude devrait lire',
    'Saída verbosa que Claude teria que ler',
    'Claudeが読まなければならない冗長な出力',
    'Đầu ra dài dòng mà Claude phải đọc',
    'Uitgebreide uitvoer die Claude zou moeten lezen',
    'Részletes kimenet, amit Claude-nak el kellene olvasnia',
    'مخرجات مطولة يتعين على Claude قراءتها',
    'خروجی طولانی که Claude باید بخواند',
    'Claude''un okuması gereken ayrıntılı çıktı',
    'Claude가 읽어야 할 장황한 출력',
    'ผลลัพธ์ยาวที่ Claude ต้องอ่าน',
    'Claude ဖတ်ရမည့် အကျယ်တစ်ပြန့်ရလဒ်',
    'Claude-д уншуулах ёстой дэлгэрэнгүй гаралт',
    '',
    'Szczegółowe wyjście, które Claude musiałby przeczytać');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_reason_lean',
    'Large file contents compressed',
    'Contenido de archivo grande comprimido',
    'Große Dateiinhalte komprimiert',
    '大文件内容被压缩',
    'Contenu de fichier volumineux compressé',
    'Conteúdo de arquivo grande comprimido',
    '大きなファイル内容が圧縮される',
    'Nội dung tệp lớn được nén',
    'Grote bestandsinhoud gecomprimeerd',
    'Nagy fájltartalom tömörítve',
    'محتوى الملف الكبير مضغوط',
    'محتوای فایل بزرگ فشرده شده',
    'Büyük dosya içeriği sıkıştırıldı',
    '대용량 파일 내용 압축',
    'เนื้อหาไฟล์ขนาดใหญ่ถูกบีบอัด',
    'ဖိုင်ကြီးအကြောင်းအရာများ ချုံ့ထားသည်',
    'Том файлын агуулгыг шахсан',
    '',
    'Zawartość dużego pliku skompresowana');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_mined_prevention',
    'Mined prevention',
    'Prevención minada',
    'Gelernte Prävention',
    '挖掘预防',
    'Prévention apprise',
    'Prevenção minerada',
    'マイニングされた予防',
    'Phòng ngừa khai thác',
    'Gemijnde preventie',
    'Bányászott megelőzés',
    'منع مستخرج',
    'پیشگیری استخراج‌شده',
    'Öğrenilmiş önleme',
    '마이닝된 예방',
    'การป้องกันที่ขุดค้น',
    'တူးဖော်ထားသော ကြိုတင်ကာကွယ်မှု',
    'Олборлосон урьдчилан сэргийлэлт',
    '',
    'Wydobyta prewencja');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_reason_mined',
    'Known failure pattern avoided',
    'Patrón de fallo conocido evitado',
    'Bekanntes Fehlermuster vermieden',
    '已知的失败模式被避免',
    'Modèle d''échec connu évité',
    'Padrão de falha conhecido evitado',
    '既知の失敗パターンを回避',
    'Mẫu lỗi đã biết được tránh',
    'Bekend faalpatroon vermeden',
    'Ismert hibaminta elkerülve',
    'تم تجنب نمط فشل معروف',
    'الگوی شکست شناخته‌شده اجتناب شد',
    'Bilinen hata kalıbından kaçınıldı',
    '알려진 실패 패턴 회피',
    'หลีกเลี่ยงรูปแบบความล้มเหลวที่รู้จัก',
    'သိထားသော ကျရှုံးမှုပုံစံကို ရှောင်လွှဲသည်',
    'Мэдэгдэж буй алдааны хэв маягаас зайлсхийсэн',
    '',
    'Uniknięto znanego wzorca awarii');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_conservative_note',
    'These are conservative estimates. Actual savings are often higher because Claude''s reasoning about errors can be verbose.',
    'Estas son estimaciones conservadoras. Los ahorros reales suelen ser mayores porque el razonamiento de Claude sobre errores puede ser extenso.',
    'Dies sind konservative Schätzungen. Die tatsächlichen Einsparungen sind oft höher, da Claudes Reasoning über Fehler ausführlich sein kann.',
    '这些是保守估计。实际节省通常更高，因为Claude对错误的推理可能很冗长。',
    'Ce sont des estimations conservatrices. Les économies réelles sont souvent plus élevées car le raisonnement de Claude sur les erreurs peut être verbose.',
    'Estas são estimativas conservadoras. As economias reais são frequentemente maiores porque o raciocínio do Claude sobre erros pode ser extenso.',
    'これらは控えめな見積もりです。Claudeのエラーに関する推論は冗長になることがあるため、実際の節約はより高いことが多いです。',
    'Đây là ước tính thận trọng. Tiết kiệm thực tế thường cao hơn vì suy luận của Claude về lỗi có thể rất dài dòng.',
    'Dit zijn conservatieve schattingen. Werkelijke besparingen zijn vaak hoger omdat Claude''s redenering over fouten uitgebreid kan zijn.',
    'Ezek konzervatív becslések. A tényleges megtakarítások gyakran magasabbak, mert Claude hibákról való gondolkodása terjedelmes lehet.',
    'هذه تقديرات متحفظة. التوفير الفعلي غالبًا أعلى لأن تفكير Claude حول الأخطاء يمكن أن يكون مطولًا.',
    'اینها تخمین‌های محتاطانه هستند. صرفه‌جویی واقعی اغلب بیشتر است زیرا استدلال Claude درباره خطاها می‌تواند طولانی باشد.',
    'Bunlar muhafazakâr tahminlerdir. Gerçek tasarruflar genellikle daha yüksektir çünkü Claude''un hatalar hakkındaki muhakemesi ayrıntılı olabilir.',
    '이것은 보수적인 추정치입니다. Claude의 오류에 대한 추론이 장황할 수 있으므로 실제 절약량은 종종 더 높습니다.',
    'นี่เป็นการประมาณการแบบอนุรักษ์นิยม การประหยัดจริงมักสูงกว่าเพราะการให้เหตุผลของ Claude เกี่ยวกับข้อผิดพลาดอาจยาว',
    'ဤအရာများသည် ခန့်မှန်းချက်များဖြစ်ပြီး အမှန်တကယ်ချွေတာမှုသည် ပိုများနိုင်သည်။',
    'Эдгээр нь болгоомжтой тооцоолол юм. Бодит хэмнэлт нь ихэвчлэн илүү өндөр байдаг.',
    '',
    'Są to ostrożne szacunki. Rzeczywiste oszczędności są często wyższe, ponieważ rozumowanie Claude o błędach może być obszerne.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_cumulative_title',
    'Cumulative Savings',
    'Ahorros acumulados',
    'Kumulative Einsparungen',
    '累计节省',
    'Économies cumulées',
    'Economia acumulada',
    '累積節約',
    'Tiết kiệm tích lũy',
    'Cumulatieve besparingen',
    'Kumulatív megtakarítások',
    'التوفير التراكمي',
    'صرفه‌جویی تجمعی',
    'Kümülatif tasarruflar',
    '누적 절약',
    'การประหยัดสะสม',
    'စုဆောင်းချွေတာမှု',
    'Хуримтлагдсан хэмнэлт',
    '',
    'Skumulowane oszczędności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sav_cumulative_body',
    'Savings persist across sessions in the PRECC database. Over time, you can track the total impact:',
    'Los ahorros se mantienen entre sesiones en la base de datos de PRECC. Con el tiempo, puedes rastrear el impacto total:',
    'Einsparungen bleiben sitzungsübergreifend in der PRECC-Datenbank erhalten. Im Laufe der Zeit können Sie die Gesamtwirkung verfolgen:',
    '节省数据在PRECC数据库中跨会话持久化。随着时间推移，您可以跟踪总体影响：',
    'Les économies persistent entre les sessions dans la base de données PRECC. Au fil du temps, vous pouvez suivre l''impact total :',
    'As economias persistem entre sessões no banco de dados PRECC. Ao longo do tempo, você pode acompanhar o impacto total:',
    '節約はPRECCデータベースにセッション間で保持されます。時間の経過とともに、総合的な影響を追跡できます：',
    'Tiết kiệm được lưu giữ qua các phiên trong cơ sở dữ liệu PRECC. Theo thời gian, bạn có thể theo dõi tổng tác động:',
    'Besparingen blijven bewaard over sessies in de PRECC-database. Na verloop van tijd kunt u de totale impact volgen:',
    'A megtakarítások munkamenetek között megmaradnak a PRECC adatbázisban. Idővel nyomon követheti az összesített hatást:',
    'تستمر المدخرات عبر الجلسات في قاعدة بيانات PRECC. بمرور الوقت، يمكنك تتبع التأثير الإجمالي:',
    'صرفه‌جویی‌ها در پایگاه داده PRECC بین جلسات باقی می‌مانند. با گذشت زمان، می‌توانید تأثیر کلی را پیگیری کنید:',
    'Tasarruflar PRECC veritabanında oturumlar arasında kalıcıdır. Zamanla toplam etkiyi takip edebilirsiniz:',
    '절약량은 PRECC 데이터베이스에서 세션 간에 유지됩니다. 시간이 지나면서 전체적인 영향을 추적할 수 있습니다:',
    'การประหยัดจะคงอยู่ข้ามเซสชันในฐานข้อมูล PRECC เมื่อเวลาผ่านไปคุณสามารถติดตามผลกระทบทั้งหมด:',
    'ချွေတာမှုများသည် PRECC ဒေတာဘေ့စ်တွင် session များအကြား ဆက်လက်ရှိနေသည်။ အချိန်ကြာလာသည်နှင့်အမျှ စုစုပေါင်းသက်ရောက်မှုကို ခြေရာခံနိုင်သည်:',
    'Хэмнэлт нь PRECC-ийн мэдээллийн санд сессүүд хооронд хадгалагддаг. Цаг хугацаа өнгөрөхөд нийт нөлөөллийг хянах боломжтой:',
    '',
    'Oszczędności utrzymują się między sesjami w bazie danych PRECC. Z czasem możesz śledzić łączny wpływ:');
