-- Quickstart chapter strings
INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_title',
    'Quickstart',
    'Inicio rápido',
    'Schnellstart',
    '快速入门',
    'Démarrage rapide',
    'Início rápido',
    'クイックスタート',
    'Bắt đầu nhanh',
    'Snelstart',
    'Gyorsindítás',
    'البدء السريع',
    'شروع سریع',
    'Hızlı Başlangıç',
    '빠른 시작',
    'เริ่มต้นอย่างรวดเร็ว',
    'အမြန်စတင်ခြင်း',
    'Хурдан эхлэх',
    '',
    'Szybki start');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_subtitle',
    'Get PRECC running in 5 minutes.',
    'Pon PRECC en marcha en 5 minutos.',
    'PRECC in 5 Minuten zum Laufen bringen.',
    '5分钟内启动PRECC。',
    'Lancez PRECC en 5 minutes.',
    'Coloque o PRECC em funcionamento em 5 minutos.',
    '5分でPRECCを起動しましょう。',
    'Khởi chạy PRECC trong 5 phút.',
    'PRECC in 5 minuten operationeel.',
    'Indítsd el a PRECC-et 5 perc alatt.',
    'شغّل PRECC في 5 دقائق.',
    'PRECC را در ۵ دقیقه راه‌اندازی کنید.',
    'PRECC''i 5 dakikada çalıştırın.',
    '5분 안에 PRECC를 실행하세요.',
    'เริ่มใช้งาน PRECC ใน 5 นาที',
    'PRECC ကို မိနစ် ၅ အတွင်း စတင်ပါ။',
    'PRECC-ийг 5 минутад ажиллуулна уу.',
    '',
    'Uruchom PRECC w 5 minut.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_step1_title',
    'Step 1: Install',
    'Paso 1: Instalar',
    'Schritt 1: Installation',
    '步骤1：安装',
    'Étape 1 : Installation',
    'Passo 1: Instalar',
    'ステップ1：インストール',
    'Bước 1: Cài đặt',
    'Stap 1: Installeren',
    '1. lépés: Telepítés',
    'الخطوة 1: التثبيت',
    'مرحله ۱: نصب',
    'Adım 1: Kurulum',
    '1단계: 설치',
    'ขั้นตอนที่ 1: ติดตั้ง',
    'အဆင့် ၁: တပ်ဆင်ခြင်း',
    'Алхам 1: Суулгах',
    '',
    'Krok 1: Instalacja');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_step2_title',
    'Step 2: Initialize',
    'Paso 2: Inicializar',
    'Schritt 2: Initialisierung',
    '步骤2：初始化',
    'Étape 2 : Initialisation',
    'Passo 2: Inicializar',
    'ステップ2：初期化',
    'Bước 2: Khởi tạo',
    'Stap 2: Initialiseren',
    '2. lépés: Inicializálás',
    'الخطوة 2: التهيئة',
    'مرحله ۲: مقداردهی اولیه',
    'Adım 2: Başlatma',
    '2단계: 초기화',
    'ขั้นตอนที่ 2: เริ่มต้นระบบ',
    'အဆင့် ၂: စတင်ခြင်း',
    'Алхам 2: Эхлүүлэх',
    '',
    'Krok 2: Inicjalizacja');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_step3_title',
    'Step 3: Verify the Hook Is Active',
    'Paso 3: Verificar que el hook esté activo',
    'Schritt 3: Überprüfen, ob der Hook aktiv ist',
    '步骤3：验证Hook已激活',
    'Étape 3 : Vérifier que le hook est actif',
    'Passo 3: Verificar se o hook está ativo',
    'ステップ3：フックがアクティブか確認',
    'Bước 3: Xác minh hook đang hoạt động',
    'Stap 3: Controleer of de hook actief is',
    '3. lépés: Ellenőrizd, hogy a hook aktív',
    'الخطوة 3: تحقق من أن الخطاف نشط',
    'مرحله ۳: بررسی فعال بودن هوک',
    'Adım 3: Hook''un aktif olduğunu doğrulayın',
    '3단계: 훅이 활성 상태인지 확인',
    'ขั้นตอนที่ 3: ตรวจสอบว่า hook ทำงานอยู่',
    'အဆင့် ၃: Hook အလုပ်လုပ်နေသည်ကို စစ်ဆေးခြင်း',
    'Алхам 3: Hook идэвхтэй эсэхийг шалгах',
    '',
    'Krok 3: Sprawdź, czy hook jest aktywny');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_step4_title',
    'Step 4: Use Claude Code Normally',
    'Paso 4: Usar Claude Code normalmente',
    'Schritt 4: Claude Code normal verwenden',
    '步骤4：正常使用Claude Code',
    'Étape 4 : Utiliser Claude Code normalement',
    'Passo 4: Usar o Claude Code normalmente',
    'ステップ4：Claude Codeを通常通り使用',
    'Bước 4: Sử dụng Claude Code bình thường',
    'Stap 4: Gebruik Claude Code normaal',
    '4. lépés: Használd a Claude Code-ot a szokásos módon',
    'الخطوة 4: استخدم Claude Code بشكل طبيعي',
    'مرحله ۴: از Claude Code به طور عادی استفاده کنید',
    'Adım 4: Claude Code''u normal şekilde kullanın',
    '4단계: Claude Code를 평소처럼 사용',
    'ขั้นตอนที่ 4: ใช้ Claude Code ตามปกติ',
    'အဆင့် ၄: Claude Code ကို ပုံမှန်အတိုင်း အသုံးပြုခြင်း',
    'Алхам 4: Claude Code-ийг ердийнхөөрөө ашиглах',
    '',
    'Krok 4: Używaj Claude Code normalnie');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_step4_body',
    'Open Claude Code and work as usual. PRECC runs silently in the background. When Claude issues a command that would fail, PRECC corrects it before execution.',
    'Abre Claude Code y trabaja como siempre. PRECC se ejecuta silenciosamente en segundo plano. Cuando Claude emite un comando que fallaría, PRECC lo corrige antes de la ejecución.',
    'Öffne Claude Code und arbeite wie gewohnt. PRECC läuft still im Hintergrund. Wenn Claude einen Befehl ausgibt, der fehlschlagen würde, korrigiert PRECC ihn vor der Ausführung.',
    '打开Claude Code并照常工作。PRECC在后台静默运行。当Claude发出一个会失败的命令时，PRECC会在执行前修正它。',
    'Ouvrez Claude Code et travaillez normalement. PRECC s''exécute silencieusement en arrière-plan. Quand Claude émet une commande qui échouerait, PRECC la corrige avant l''exécution.',
    'Abra o Claude Code e trabalhe normalmente. O PRECC roda silenciosamente em segundo plano. Quando o Claude emite um comando que falharia, o PRECC o corrige antes da execução.',
    'Claude Codeを開いて通常通り作業してください。PRECCはバックグラウンドで静かに動作します。Claudeが失敗するコマンドを発行すると、PRECCが実行前に修正します。',
    'Mở Claude Code và làm việc bình thường. PRECC chạy ngầm trong nền. Khi Claude phát ra lệnh sẽ thất bại, PRECC sửa nó trước khi thực thi.',
    'Open Claude Code en werk zoals gewoonlijk. PRECC draait stil op de achtergrond. Wanneer Claude een commando geeft dat zou mislukken, corrigeert PRECC het vóór uitvoering.',
    'Nyisd meg a Claude Code-ot és dolgozz a szokásos módon. A PRECC csendben fut a háttérben. Amikor Claude egy sikertelen parancsot adna ki, a PRECC kijavítja végrehajtás előtt.',
    'افتح Claude Code واعمل كالمعتاد. يعمل PRECC بصمت في الخلفية. عندما يصدر Claude أمراً سيفشل، يقوم PRECC بتصحيحه قبل التنفيذ.',
    'Claude Code را باز کنید و طبق معمول کار کنید. PRECC بی‌صدا در پس‌زمینه اجرا می‌شود. وقتی Claude دستوری صادر می‌کند که شکست می‌خورد، PRECC آن را قبل از اجرا اصلاح می‌کند.',
    'Claude Code''u açın ve her zamanki gibi çalışın. PRECC arka planda sessizce çalışır. Claude başarısız olacak bir komut verdiğinde, PRECC bunu çalıştırmadan önce düzeltir.',
    'Claude Code를 열고 평소처럼 작업하세요. PRECC는 백그라운드에서 조용히 실행됩니다. Claude가 실패할 명령을 내리면 PRECC가 실행 전에 수정합니다.',
    'เปิด Claude Code แล้วทำงานตามปกติ PRECC ทำงานอยู่เบื้องหลังอย่างเงียบๆ เมื่อ Claude ออกคำสั่งที่จะล้มเหลว PRECC จะแก้ไขก่อนการดำเนินการ',
    'Claude Code ကိုဖွင့်ပြီး ပုံမှန်အတိုင်း အလုပ်လုပ်ပါ။ PRECC သည် နောက်ကွယ်တွင် တိတ်ဆိတ်စွာ အလုပ်လုပ်နေသည်။ Claude က ပျက်ကွက်မည့် command တစ်ခုကို ထုတ်သောအခါ PRECC က လုပ်ဆောင်မှုမတိုင်မီ ပြင်ဆင်ပေးသည်။',
    'Claude Code-ийг нээж ердийнхөөрөө ажиллана уу. PRECC арын дэвсгэр дээр чимээгүй ажиллана. Claude амжилтгүй болох тушаал өгөхөд PRECC гүйцэтгэхээс өмнө засна.',
    '',
    'Otwórz Claude Code i pracuj jak zwykle. PRECC działa cicho w tle. Gdy Claude wyda polecenie, które by się nie powiodło, PRECC poprawia je przed wykonaniem.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_example_title',
    'Example: Wrong-Directory Cargo Build',
    'Ejemplo: Cargo Build en directorio incorrecto',
    'Beispiel: Cargo Build im falschen Verzeichnis',
    '示例：错误目录的Cargo Build',
    'Exemple : Cargo Build dans le mauvais répertoire',
    'Exemplo: Cargo Build no diretório errado',
    '例：間違ったディレクトリでのCargo Build',
    'Ví dụ: Cargo Build sai thư mục',
    'Voorbeeld: Cargo Build in verkeerde map',
    'Példa: Cargo Build rossz könyvtárban',
    'مثال: تشغيل Cargo Build في المجلد الخطأ',
    'مثال: اجرای Cargo Build در پوشه اشتباه',
    'Örnek: Yanlış dizinde Cargo Build',
    '예시: 잘못된 디렉토리에서 Cargo Build',
    'ตัวอย่าง: Cargo Build ในไดเรกทอรีที่ผิด',
    'ဥပမာ: မှားယွင်းသော directory တွင် Cargo Build',
    'Жишээ: Буруу хавтаст Cargo Build хийх',
    '',
    'Przykład: Cargo Build w złym katalogu');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_example_setup',
    'Suppose your project is at `~/projects/myapp/` and Claude issues:',
    'Supón que tu proyecto está en `~/projects/myapp/` y Claude ejecuta:',
    'Angenommen, dein Projekt ist unter `~/projects/myapp/` und Claude gibt aus:',
    '假设你的项目在 `~/projects/myapp/`，Claude发出：',
    'Supposons que votre projet est dans `~/projects/myapp/` et Claude exécute :',
    'Suponha que seu projeto está em `~/projects/myapp/` e o Claude emite:',
    'プロジェクトが `~/projects/myapp/` にあり、Claudeが以下を実行するとします：',
    'Giả sử dự án của bạn ở `~/projects/myapp/` và Claude ra lệnh:',
    'Stel dat je project in `~/projects/myapp/` staat en Claude uitvoert:',
    'Tegyük fel, hogy a projekted a `~/projects/myapp/` helyen van, és Claude kiadja:',
    'افترض أن مشروعك في `~/projects/myapp/` وأصدر Claude:',
    'فرض کنید پروژه شما در `~/projects/myapp/` است و Claude دستور زیر را صادر می‌کند:',
    'Projenizin `~/projects/myapp/` konumunda olduğunu ve Claude''un şunu çalıştırdığını varsayın:',
    '프로젝트가 `~/projects/myapp/`에 있고 Claude가 다음을 실행한다고 가정합니다:',
    'สมมติว่าโปรเจกต์ของคุณอยู่ที่ `~/projects/myapp/` และ Claude ออกคำสั่ง:',
    'သင့်ပရောဂျက်သည် `~/projects/myapp/` တွင်ရှိပြီး Claude က အောက်ပါ command ကို ထုတ်သည်ဟု ယူဆပါ:',
    'Таны төсөл `~/projects/myapp/` дотор байгаа бөгөөд Claude дараахийг гүйцэтгэнэ гэж бодъё:',
    '',
    'Załóżmy, że twój projekt jest w `~/projects/myapp/`, a Claude wydaje:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_example_context',
    'from `~/projects/` (one level too high, no `Cargo.toml` there).',
    'desde `~/projects/` (un nivel demasiado alto, sin `Cargo.toml` allí).',
    'von `~/projects/` aus (eine Ebene zu hoch, kein `Cargo.toml` dort).',
    '从 `~/projects/`（高了一级，那里没有 `Cargo.toml`）。',
    'depuis `~/projects/` (un niveau trop haut, pas de `Cargo.toml` là).',
    'a partir de `~/projects/` (um nível acima, sem `Cargo.toml` lá).',
    '`~/projects/` から（1階層上で、そこに `Cargo.toml` はありません）。',
    'từ `~/projects/` (cao hơn một cấp, không có `Cargo.toml` ở đó).',
    'vanuit `~/projects/` (één niveau te hoog, geen `Cargo.toml` daar).',
    'a `~/projects/` könyvtárból (egy szinttel túl magas, nincs ott `Cargo.toml`).',
    'من `~/projects/` (مستوى واحد أعلى من اللازم، لا يوجد `Cargo.toml` هناك).',
    'از `~/projects/` (یک سطح بالاتر، بدون `Cargo.toml` در آنجا).',
    '`~/projects/` dizininden (bir seviye yukarıda, orada `Cargo.toml` yok).',
    '`~/projects/`에서 (한 단계 위, 거기에 `Cargo.toml` 없음).',
    'จาก `~/projects/` (สูงกว่าหนึ่งระดับ ไม่มี `Cargo.toml` ที่นั่น)',
    '`~/projects/` မှ (အဆင့်တစ်ခု မြင့်လွန်းပြီး ထိုနေရာတွင် `Cargo.toml` မရှိပါ)။',
    '`~/projects/` хавтаснаас (нэг түвшин өндөр, тэнд `Cargo.toml` байхгүй).',
    '',
    'z `~/projects/` (jeden poziom za wysoko, brak tam `Cargo.toml`).');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_without_precc',
    '**Without PRECC:** Claude gets the error `could not find Cargo.toml in /home/user/projects or any parent directory`, reads it, reasons about it, then retries with `cd myapp && cargo build`. Cost: ~2,000 tokens wasted.',
    '**Sin PRECC:** Claude recibe el error `could not find Cargo.toml in /home/user/projects or any parent directory`, lo lee, razona y reintenta con `cd myapp && cargo build`. Costo: ~2.000 tokens desperdiciados.',
    '**Ohne PRECC:** Claude erhält den Fehler `could not find Cargo.toml in /home/user/projects or any parent directory`, liest ihn, denkt darüber nach und versucht es mit `cd myapp && cargo build` erneut. Kosten: ~2.000 Token verschwendet.',
    '**没有PRECC：** Claude收到错误 `could not find Cargo.toml in /home/user/projects or any parent directory`，读取、推理，然后用 `cd myapp && cargo build` 重试。代价：浪费约2,000个token。',
    '**Sans PRECC :** Claude reçoit l''erreur `could not find Cargo.toml in /home/user/projects or any parent directory`, la lit, raisonne, puis réessaie avec `cd myapp && cargo build`. Coût : ~2 000 tokens gaspillés.',
    '**Sem PRECC:** Claude recebe o erro `could not find Cargo.toml in /home/user/projects or any parent directory`, lê, raciocina e tenta novamente com `cd myapp && cargo build`. Custo: ~2.000 tokens desperdiçados.',
    '**PRECCなし：** Claudeはエラー `could not find Cargo.toml in /home/user/projects or any parent directory` を受け取り、読んで推論し、`cd myapp && cargo build` で再試行します。コスト：約2,000トークンの無駄。',
    '**Không có PRECC:** Claude nhận lỗi `could not find Cargo.toml in /home/user/projects or any parent directory`, đọc, suy luận, rồi thử lại với `cd myapp && cargo build`. Chi phí: ~2.000 token lãng phí.',
    '**Zonder PRECC:** Claude krijgt de fout `could not find Cargo.toml in /home/user/projects or any parent directory`, leest deze, redeneert erover en probeert opnieuw met `cd myapp && cargo build`. Kosten: ~2.000 tokens verspild.',
    '**PRECC nélkül:** Claude megkapja a hibát `could not find Cargo.toml in /home/user/projects or any parent directory`, elolvassa, gondolkodik rajta, majd újrapróbálja: `cd myapp && cargo build`. Költség: ~2000 token elvesztegetva.',
    '**بدون PRECC:** يحصل Claude على الخطأ `could not find Cargo.toml in /home/user/projects or any parent directory`، يقرأه، يفكر فيه، ثم يعيد المحاولة بـ `cd myapp && cargo build`. التكلفة: ~2,000 رمز مهدر.',
    '**بدون PRECC:** Claude خطای `could not find Cargo.toml in /home/user/projects or any parent directory` را دریافت می‌کند، می‌خواند، استدلال می‌کند و با `cd myapp && cargo build` دوباره تلاش می‌کند. هزینه: حدود ۲۰۰۰ توکن هدر رفته.',
    '**PRECC olmadan:** Claude `could not find Cargo.toml in /home/user/projects or any parent directory` hatasını alır, okur, düşünür ve `cd myapp && cargo build` ile tekrar dener. Maliyet: ~2.000 token israf.',
    '**PRECC 없이:** Claude가 `could not find Cargo.toml in /home/user/projects or any parent directory` 오류를 받고, 읽고, 추론한 후 `cd myapp && cargo build`로 재시도합니다. 비용: ~2,000 토큰 낭비.',
    '**ไม่มี PRECC:** Claude ได้รับข้อผิดพลาด `could not find Cargo.toml in /home/user/projects or any parent directory` อ่าน วิเคราะห์ แล้วลองใหม่ด้วย `cd myapp && cargo build` ค่าใช้จ่าย: ~2,000 โทเค็นสูญเปล่า',
    '**PRECC မရှိဘဲ:** Claude သည် `could not find Cargo.toml in /home/user/projects or any parent directory` error ကိုရရှိပြီး ဖတ်ပြီး ခွဲခြမ်းစိတ်ဖြာကာ `cd myapp && cargo build` ဖြင့် ပြန်ကြိုးစားသည်။ ကုန်ကျစရိတ်: token ~၂,၀၀၀ ဖြုန်းတီး။',
    '**PRECC-гүйгээр:** Claude `could not find Cargo.toml in /home/user/projects or any parent directory` алдааг авч, уншиж, боддог, дараа нь `cd myapp && cargo build`-ээр дахин оролдоно. Зардал: ~2,000 токен үрэгдэнэ.',
    '',
    '**Bez PRECC:** Claude otrzymuje błąd `could not find Cargo.toml in /home/user/projects or any parent directory`, czyta go, analizuje i ponawia próbę z `cd myapp && cargo build`. Koszt: ~2000 tokenów zmarnowanych.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_with_precc',
    '**With PRECC:** The hook detects the missing `Cargo.toml`, finds it in `myapp/`, and rewrites the command to:',
    '**Con PRECC:** El hook detecta el `Cargo.toml` faltante, lo encuentra en `myapp/` y reescribe el comando a:',
    '**Mit PRECC:** Der Hook erkennt das fehlende `Cargo.toml`, findet es in `myapp/` und schreibt den Befehl um zu:',
    '**使用PRECC：** Hook检测到缺失的 `Cargo.toml`，在 `myapp/` 中找到它，并将命令重写为：',
    '**Avec PRECC :** Le hook détecte le `Cargo.toml` manquant, le trouve dans `myapp/` et réécrit la commande en :',
    '**Com PRECC:** O hook detecta o `Cargo.toml` ausente, encontra-o em `myapp/` e reescreve o comando para:',
    '**PRECCあり：** フックが `Cargo.toml` の欠如を検出し、`myapp/` で見つけ、コマンドを以下に書き換えます：',
    '**Với PRECC:** Hook phát hiện thiếu `Cargo.toml`, tìm thấy trong `myapp/` và viết lại lệnh thành:',
    '**Met PRECC:** De hook detecteert het ontbrekende `Cargo.toml`, vindt het in `myapp/` en herschrijft het commando naar:',
    '**PRECC-kel:** A hook észleli a hiányzó `Cargo.toml`-t, megtalálja a `myapp/` mappában, és átírja a parancsot:',
    '**مع PRECC:** يكتشف الخطاف `Cargo.toml` المفقود، يجده في `myapp/`، ويعيد كتابة الأمر إلى:',
    '**با PRECC:** هوک `Cargo.toml` گمشده را تشخیص می‌دهد، آن را در `myapp/` پیدا می‌کند و دستور را بازنویسی می‌کند به:',
    '**PRECC ile:** Hook eksik `Cargo.toml`''u algılar, `myapp/` içinde bulur ve komutu şu şekilde yeniden yazar:',
    '**PRECC 사용 시:** 훅이 누락된 `Cargo.toml`을 감지하고 `myapp/`에서 찾아 명령을 다음으로 재작성합니다:',
    '**ใช้ PRECC:** hook ตรวจพบว่าไม่มี `Cargo.toml` หาเจอใน `myapp/` และเขียนคำสั่งใหม่เป็น:',
    '**PRECC ဖြင့်:** Hook သည် ပျောက်ဆုံးနေသော `Cargo.toml` ကို ရှာဖွေတွေ့ရှိပြီး `myapp/` တွင် တွေ့ကာ command ကို ပြန်လည်ရေးသားသည်:',
    '**PRECC-тэй:** Hook дутуу `Cargo.toml`-ийг илрүүлж, `myapp/` дотор олж, тушаалыг дараах болгон дахин бичнэ:',
    '',
    '**Z PRECC:** Hook wykrywa brakujący `Cargo.toml`, znajduje go w `myapp/` i przepisuje polecenie na:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_example_result',
    'Claude never sees an error. Zero tokens wasted.',
    'Claude nunca ve un error. Cero tokens desperdiciados.',
    'Claude sieht nie einen Fehler. Null Token verschwendet.',
    'Claude永远看不到错误。零token浪费。',
    'Claude ne voit jamais d''erreur. Zéro token gaspillé.',
    'Claude nunca vê um erro. Zero tokens desperdiçados.',
    'Claudeはエラーを見ることがありません。トークンの無駄はゼロ。',
    'Claude không bao giờ thấy lỗi. Không lãng phí token nào.',
    'Claude ziet nooit een fout. Nul tokens verspild.',
    'Claude soha nem lát hibát. Nulla token elvesztegetva.',
    'لا يرى Claude أي خطأ أبداً. صفر رموز مهدرة.',
    'Claude هرگز خطایی نمی‌بیند. صفر توکن هدر رفته.',
    'Claude hiçbir zaman hata görmez. Sıfır token israf.',
    'Claude는 오류를 절대 보지 않습니다. 낭비되는 토큰 제로.',
    'Claude ไม่เห็นข้อผิดพลาดเลย ไม่มีโทเค็นสูญเปล่า',
    'Claude သည် error ကို ဘယ်တော့မှ မမြင်ရပါ။ token ဖြုန်းတီးမှု သုညဖြစ်သည်။',
    'Claude алдаа хэзээ ч харахгүй. Тэг токен үрэгдэнэ.',
    '',
    'Claude nigdy nie widzi błędu. Zero zmarnowanych tokenów.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_step5_title',
    'Step 5: Check Your Savings',
    'Paso 5: Comprueba tus ahorros',
    'Schritt 5: Ersparnisse überprüfen',
    '步骤5：查看节省情况',
    'Étape 5 : Vérifier vos économies',
    'Passo 5: Verifique suas economias',
    'ステップ5：節約を確認',
    'Bước 5: Kiểm tra tiết kiệm của bạn',
    'Stap 5: Controleer je besparingen',
    '5. lépés: Ellenőrizd a megtakarításokat',
    'الخطوة 5: تحقق من مدخراتك',
    'مرحله ۵: صرفه‌جویی خود را بررسی کنید',
    'Adım 5: Tasarruflarınızı kontrol edin',
    '5단계: 절약량 확인',
    'ขั้นตอนที่ 5: ตรวจสอบการประหยัดของคุณ',
    'အဆင့် ၅: သင့်ချွေတာမှုကို စစ်ဆေးခြင်း',
    'Алхам 5: Хэмнэлтээ шалгах',
    '',
    'Krok 5: Sprawdź oszczędności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_step5_body',
    'After a session, see how many tokens PRECC saved:',
    'Después de una sesión, mira cuántos tokens ahorró PRECC:',
    'Überprüfe nach einer Sitzung, wie viele Token PRECC gespart hat:',
    '会话结束后，查看PRECC节省了多少token：',
    'Après une session, voyez combien de tokens PRECC a économisé :',
    'Após uma sessão, veja quantos tokens o PRECC economizou:',
    'セッション後、PRECCがどれだけのトークンを節約したか確認してください：',
    'Sau một phiên làm việc, xem PRECC đã tiết kiệm bao nhiêu token:',
    'Bekijk na een sessie hoeveel tokens PRECC heeft bespaard:',
    'Egy munkamenet után nézd meg, hány tokent takarított meg a PRECC:',
    'بعد الجلسة، تحقق من عدد الرموز التي وفرها PRECC:',
    'پس از یک جلسه، ببینید PRECC چند توکن صرفه‌جویی کرده است:',
    'Bir oturumdan sonra PRECC''in kaç token tasarruf ettiğini görün:',
    '세션 후 PRECC가 절약한 토큰 수를 확인하세요:',
    'หลังจากเซสชัน ดูว่า PRECC ประหยัดโทเค็นได้เท่าไหร่:',
    'session တစ်ခုပြီးနောက် PRECC က token ဘယ်လောက် ချွေတာခဲ့သည်ကို ကြည့်ပါ:',
    'Сессийн дараа PRECC хэдэн токен хэмнэснийг харна уу:',
    '',
    'Po sesji sprawdź, ile tokenów zaoszczędził PRECC:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_next_steps_title',
    'Next Steps',
    'Próximos pasos',
    'Nächste Schritte',
    '后续步骤',
    'Étapes suivantes',
    'Próximos passos',
    '次のステップ',
    'Bước tiếp theo',
    'Volgende stappen',
    'Következő lépések',
    'الخطوات التالية',
    'مراحل بعدی',
    'Sonraki adımlar',
    '다음 단계',
    'ขั้นตอนถัดไป',
    'နောက်ထပ် အဆင့်များ',
    'Дараагийн алхамууд',
    '',
    'Kolejne kroki');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_link_skills',
    'Skills',
    'Habilidades',
    'Skills',
    '技能',
    'Compétences',
    'Habilidades',
    'スキル',
    'Kỹ năng',
    'Vaardigheden',
    'Képességek',
    'المهارات',
    'مهارت‌ها',
    'Yetenekler',
    '스킬',
    'ทักษะ',
    'ကျွမ်းကျင်မှုများ',
    'Чадварууд',
    '',
    'Umiejętności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_link_skills_desc',
    'See all available skills and how to create your own.',
    'Ver todas las habilidades disponibles y cómo crear las tuyas.',
    'Alle verfügbaren Skills und wie du eigene erstellen kannst.',
    '查看所有可用技能以及如何创建自己的技能。',
    'Voir toutes les compétences disponibles et comment créer les vôtres.',
    'Veja todas as habilidades disponíveis e como criar as suas.',
    '利用可能な全スキルと独自スキルの作成方法。',
    'Xem tất cả kỹ năng có sẵn và cách tạo kỹ năng riêng.',
    'Bekijk alle beschikbare vaardigheden en hoe je je eigen kunt maken.',
    'Az összes elérhető képesség és saját készítése.',
    'عرض جميع المهارات المتاحة وكيفية إنشاء مهاراتك الخاصة.',
    'مشاهده همه مهارت‌های موجود و نحوه ایجاد مهارت‌های خود.',
    'Tüm mevcut yetenekleri ve kendi yeteneklerinizi nasıl oluşturacağınızı görün.',
    '사용 가능한 모든 스킬과 직접 만드는 방법을 확인하세요.',
    'ดูทักษะทั้งหมดที่มีและวิธีสร้างทักษะของคุณเอง',
    'ရရှိနိုင်သော ကျွမ်းကျင်မှုအားလုံးနှင့် သင့်ကိုယ်ပိုင် ဖန်တီးနည်းကို ကြည့်ပါ။',
    'Бүх боломжтой чадваруудыг болон өөрийнхөө чадварыг хэрхэн үүсгэхийг харна уу.',
    '',
    'Zobacz wszystkie dostępne umiejętności i jak tworzyć własne.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_link_pipeline',
    'Hook Pipeline',
    'Pipeline del Hook',
    'Hook-Pipeline',
    'Hook管道',
    'Pipeline du hook',
    'Pipeline do Hook',
    'フックパイプライン',
    'Pipeline Hook',
    'Hook Pipeline',
    'Hook Pipeline',
    'خط أنابيب الخطاف',
    'خط لوله هوک',
    'Hook Pipeline',
    '훅 파이프라인',
    'Hook Pipeline',
    'Hook Pipeline',
    'Hook Pipeline',
    '',
    'Pipeline Hooka');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_link_pipeline_desc',
    'Understand what happens under the hood.',
    'Entiende qué sucede bajo el capó.',
    'Verstehe, was unter der Haube passiert.',
    '了解底层发生了什么。',
    'Comprenez ce qui se passe sous le capot.',
    'Entenda o que acontece por baixo dos panos.',
    'フードの下で何が起きているかを理解する。',
    'Hiểu những gì xảy ra bên trong.',
    'Begrijp wat er onder de motorkap gebeurt.',
    'Értsd meg, mi történik a háttérben.',
    'افهم ما يحدث خلف الكواليس.',
    'بفهمید در پشت صحنه چه اتفاقی می‌افتد.',
    'Kaputun altında neler olduğunu anlayın.',
    '내부에서 무슨 일이 일어나는지 이해하세요.',
    'เข้าใจว่าเกิดอะไรขึ้นเบื้องหลัง',
    'အတွင်းပိုင်းတွင် ဘာဖြစ်နေသည်ကို နားလည်ပါ။',
    'Дотор нь юу болж байгааг ойлго.',
    '',
    'Zrozum, co dzieje się pod maską.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_link_savings',
    'Savings',
    'Ahorros',
    'Ersparnisse',
    '节省',
    'Économies',
    'Economias',
    '節約',
    'Tiết kiệm',
    'Besparingen',
    'Megtakarítások',
    'المدخرات',
    'صرفه‌جویی',
    'Tasarruflar',
    '절약',
    'การประหยัด',
    'ချွေတာမှု',
    'Хэмнэлт',
    '',
    'Oszczędności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('qs_link_savings_desc',
    'Detailed token savings analysis.',
    'Análisis detallado de ahorro de tokens.',
    'Detaillierte Analyse der Token-Einsparungen.',
    '详细的token节省分析。',
    'Analyse détaillée des économies de tokens.',
    'Análise detalhada de economia de tokens.',
    'トークン節約の詳細分析。',
    'Phân tích chi tiết tiết kiệm token.',
    'Gedetailleerde analyse van tokenbesparingen.',
    'Részletes token-megtakarítási elemzés.',
    'تحليل مفصل لتوفير الرموز.',
    'تحلیل دقیق صرفه‌جویی توکن.',
    'Ayrıntılı token tasarruf analizi.',
    '상세한 토큰 절약 분석.',
    'การวิเคราะห์การประหยัดโทเค็นอย่างละเอียด',
    'Token ချွေတာမှု အသေးစိတ် ခွဲခြမ်းစိတ်ဖြာမှု။',
    'Токен хэмнэлтийн дэлгэрэнгүй шинжилгээ.',
    '',
    'Szczegółowa analiza oszczędności tokenów.');
