-- Installation chapter strings
INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo) VALUES
('install_title',
    'Installation',
    'Instalación',
    'Installation',
    '安装',
    'Installation',
    'Instalação',
    'インストール',
    'Cài đặt',
    'Installatie',
    'Telepítés',
    'التثبيت',
    'نصب',
    'Kurulum',
    '설치',
    'การติดตั้ง',
    'ထည့်သွင်းခြင်း',
    'Суулгах',
    'སྒྲིག་འཇུག'),
('install_quick_title',
    'Quick Install (Linux / macOS)',
    'Instalación rápida (Linux / macOS)',
    'Schnellinstallation (Linux / macOS)',
    '快速安装 (Linux / macOS)',
    'Installation rapide (Linux / macOS)',
    'Instalação rápida (Linux / macOS)',
    'クイックインストール (Linux / macOS)',
    'Cài đặt nhanh (Linux / macOS)',
    'Snelle installatie (Linux / macOS)',
    'Gyors telepítés (Linux / macOS)',
    'التثبيت السريع (Linux / macOS)',
    'نصب سریع (Linux / macOS)',
    'Hızlı Kurulum (Linux / macOS)',
    '빠른 설치 (Linux / macOS)',
    'ติดตั้งด่วน (Linux / macOS)',
    'အမြန်ထည့်သွင်းခြင်း (Linux / macOS)',
    'Хурдан суулгах (Linux / macOS)',
    ''),
('install_quick_body',
    'This downloads the latest release binary for your platform, verifies the SHA256 checksum, and places it in `~/.local/bin/`.',
    'Esto descarga el binario de la última versión para su plataforma, verifica la suma de comprobación SHA256 y lo coloca en `~/.local/bin/`.',
    'Dies lädt die neueste Release-Binary für Ihre Plattform herunter, verifiziert die SHA256-Prüfsumme und platziert sie in `~/.local/bin/`.',
    '这会下载适用于您平台的最新版本二进制文件，验证SHA256校验和，并将其放置在 `~/.local/bin/` 中。',
    'Cela télécharge le dernier binaire pour votre plateforme, vérifie la somme de contrôle SHA256 et le place dans `~/.local/bin/`.',
    'Isso baixa o binário da versão mais recente para sua plataforma, verifica a soma de verificação SHA256 e o coloca em `~/.local/bin/`.',
    'これはお使いのプラットフォーム用の最新リリースバイナリをダウンロードし、SHA256チェックサムを検証して `~/.local/bin/` に配置します。',
    'Lệnh này tải xuống bản phát hành mới nhất cho nền tảng của bạn, xác minh mã SHA256 và đặt vào `~/.local/bin/`.',
    'Dit downloadt de nieuwste release-binary voor uw platform, verifieert de SHA256-checksum en plaatst deze in `~/.local/bin/`.',
    'Ez letölti a legújabb kiadás binárisát az Ön platformjára, ellenőrzi a SHA256 ellenőrző összeget, és a `~/.local/bin/` könyvtárba helyezi.',
    'يقوم هذا بتنزيل أحدث إصدار ثنائي لمنصتك، والتحقق من المجموع الاختباري SHA256، ووضعه في `~/.local/bin/`.',
    'این فایل باینری آخرین نسخه را برای پلتفرم شما دانلود می‌کند، جمع‌آزمای SHA256 را تأیید می‌کند و آن را در `~/.local/bin/` قرار می‌دهد.',
    'Bu, platformunuz için en son sürüm ikili dosyasını indirir, SHA256 sağlama toplamını doğrular ve `~/.local/bin/` dizinine yerleştirir.',
    '이 명령은 플랫폼에 맞는 최신 릴리스 바이너리를 다운로드하고, SHA256 체크섬을 확인한 후, `~/.local/bin/`에 배치합니다.',
    'คำสั่งนี้จะดาวน์โหลดไบนารีเวอร์ชันล่าสุดสำหรับแพลตฟอร์มของคุณ ตรวจสอบ SHA256 checksum และวางไว้ใน `~/.local/bin/`',
    'ဤအရာသည် သင့်ပလက်ဖောင်းအတွက် နောက်ဆုံးထွက်ဗားရှင်းကို ဒေါင်းလုဒ်လုပ်ပြီး SHA256 checksum ကို စစ်ဆေးကာ `~/.local/bin/` တွင် ထားပေးပါသည်။',
    'Энэ нь таны платформд зориулсан хамгийн сүүлийн хувилбарыг татаж, SHA256 шалгах нийлбэрийг баталгаажуулж, `~/.local/bin/` руу байрлуулна.',
    ''),
('install_after_init',
    'After installation, initialize PRECC:',
    'Después de la instalación, inicialice PRECC:',
    'Nach der Installation initialisieren Sie PRECC:',
    '安装后，初始化PRECC：',
    'Après l''installation, initialisez PRECC :',
    'Após a instalação, inicialize o PRECC:',
    'インストール後、PRECCを初期化します：',
    'Sau khi cài đặt, khởi tạo PRECC:',
    'Initialiseer PRECC na de installatie:',
    'A telepítés után inicializálja a PRECC-et:',
    'بعد التثبيت، قم بتهيئة PRECC:',
    'پس از نصب، PRECC را مقداردهی اولیه کنید:',
    'Kurulumdan sonra PRECC''yi başlatın:',
    '설치 후 PRECC를 초기화하세요:',
    'หลังจากติดตั้งแล้ว ให้เริ่มต้น PRECC:',
    'ထည့်သွင်းပြီးနောက် PRECC ကို စတင်ပါ:',
    'Суулгасны дараа PRECC-ийг эхлүүлнэ:',
    ''),
('install_init_desc',
    '`precc init` registers the PreToolUse hook with Claude Code, creates the data directories, and initializes the skills database.',
    '`precc init` registra el hook PreToolUse con Claude Code, crea los directorios de datos e inicializa la base de datos de habilidades.',
    '`precc init` registriert den PreToolUse-Hook bei Claude Code, erstellt die Datenverzeichnisse und initialisiert die Skills-Datenbank.',
    '`precc init` 在Claude Code中注册PreToolUse钩子，创建数据目录，并初始化技能数据库。',
    '`precc init` enregistre le hook PreToolUse avec Claude Code, crée les répertoires de données et initialise la base de données des compétences.',
    '`precc init` registra o hook PreToolUse no Claude Code, cria os diretórios de dados e inicializa o banco de dados de habilidades.',
    '`precc init` はPreToolUseフックをClaude Codeに登録し、データディレクトリを作成し、スキルデータベースを初期化します。',
    '`precc init` đăng ký hook PreToolUse với Claude Code, tạo các thư mục dữ liệu và khởi tạo cơ sở dữ liệu kỹ năng.',
    '`precc init` registreert de PreToolUse-hook bij Claude Code, maakt de gegevensmappen aan en initialiseert de skills-database.',
    'A `precc init` regisztrálja a PreToolUse hookot a Claude Code-ban, létrehozza az adatkönyvtárakat és inicializálja a készségadatbázist.',
    'يقوم `precc init` بتسجيل خطاف PreToolUse مع Claude Code، وإنشاء أدلة البيانات، وتهيئة قاعدة بيانات المهارات.',
    '`precc init` هوک PreToolUse را در Claude Code ثبت می‌کند، پوشه‌های داده را ایجاد می‌کند و پایگاه داده مهارت‌ها را مقداردهی اولیه می‌کند.',
    '`precc init` PreToolUse hook''unu Claude Code''a kaydeder, veri dizinlerini oluşturur ve beceri veritabanını başlatır.',
    '`precc init`은 Claude Code에 PreToolUse 훅을 등록하고, 데이터 디렉토리를 생성하며, 스킬 데이터베이스를 초기화합니다.',
    '`precc init` ลงทะเบียน hook PreToolUse กับ Claude Code สร้างไดเรกทอรีข้อมูล และเริ่มต้นฐานข้อมูลทักษะ',
    '`precc init` သည် PreToolUse hook ကို Claude Code တွင် မှတ်ပုံတင်ပြီး ဒေတာလမ်းညွှန်များ ဖန်တီးကာ ကျွမ်းကျင်မှုဒေတာဘေ့စ်ကို စတင်ပါသည်။',
    '`precc init` нь PreToolUse hook-ийг Claude Code-д бүртгэж, өгөгдлийн сангуудыг үүсгэж, ур чадварын мэдээллийн санг эхлүүлнэ.',
    ''),
('install_options_title',
    'Install Options',
    'Opciones de instalación',
    'Installationsoptionen',
    '安装选项',
    'Options d''installation',
    'Opções de instalação',
    'インストールオプション',
    'Tùy chọn cài đặt',
    'Installatieopties',
    'Telepítési lehetőségek',
    'خيارات التثبيت',
    'گزینه‌های نصب',
    'Kurulum Seçenekleri',
    '설치 옵션',
    'ตัวเลือกการติดตั้ง',
    'ထည့်သွင်းမှုရွေးချယ်စရာများ',
    'Суулгах сонголтууд',
    ''),
('install_sha256_title',
    'SHA256 Verification',
    'Verificación SHA256',
    'SHA256-Verifizierung',
    'SHA256验证',
    'Vérification SHA256',
    'Verificação SHA256',
    'SHA256検証',
    'Xác minh SHA256',
    'SHA256-verificatie',
    'SHA256 ellenőrzés',
    'التحقق من SHA256',
    'تأیید SHA256',
    'SHA256 Doğrulama',
    'SHA256 검증',
    'การตรวจสอบ SHA256',
    'SHA256 အတည်ပြုခြင်း',
    'SHA256 баталгаажуулалт',
    ''),
('install_sha256_body',
    'By default, the installer verifies the binary checksum against the published SHA256 sum. To skip verification (not recommended):',
    'Por defecto, el instalador verifica la suma de comprobación del binario contra la suma SHA256 publicada. Para omitir la verificación (no recomendado):',
    'Standardmäßig verifiziert der Installer die Binär-Prüfsumme gegen die veröffentlichte SHA256-Summe. Um die Verifizierung zu überspringen (nicht empfohlen):',
    '默认情况下，安装程序会根据已发布的SHA256校验和验证二进制文件。要跳过验证（不推荐）：',
    'Par défaut, l''installateur vérifie la somme de contrôle du binaire par rapport à la somme SHA256 publiée. Pour ignorer la vérification (non recommandé) :',
    'Por padrão, o instalador verifica a soma de verificação do binário contra a soma SHA256 publicada. Para pular a verificação (não recomendado):',
    'デフォルトでは、インストーラーは公開されたSHA256サムに対してバイナリチェックサムを検証します。検証をスキップするには（非推奨）：',
    'Mặc định, trình cài đặt xác minh mã checksum của tệp nhị phân với SHA256 đã công bố. Để bỏ qua xác minh (không khuyến nghị):',
    'Standaard verifieert het installatieprogramma de binaire checksum tegen de gepubliceerde SHA256-som. Om verificatie over te slaan (niet aanbevolen):',
    'Alapértelmezés szerint a telepítő ellenőrzi a bináris ellenőrző összegét a közzétett SHA256 összeg alapján. Az ellenőrzés kihagyásához (nem ajánlott):',
    'بشكل افتراضي، يتحقق المثبت من المجموع الاختباري للملف الثنائي مقابل مجموع SHA256 المنشور. لتخطي التحقق (غير مستحسن):',
    'به طور پیش‌فرض، نصب‌کننده جمع‌آزمای باینری را با SHA256 منتشر شده تأیید می‌کند. برای رد شدن از تأیید (توصیه نمی‌شود):',
    'Varsayılan olarak, yükleyici ikili dosyanın sağlama toplamını yayımlanan SHA256 toplamıyla doğrular. Doğrulamayı atlamak için (önerilmez):',
    '기본적으로 설치 프로그램은 게시된 SHA256 합계와 바이너리 체크섬을 검증합니다. 검증을 건너뛰려면(권장하지 않음):',
    'ตามค่าเริ่มต้น ตัวติดตั้งจะตรวจสอบ checksum ของไบนารีกับ SHA256 ที่เผยแพร่ หากต้องการข้ามการตรวจสอบ (ไม่แนะนำ):',
    'ပုံမှန်အားဖြင့် installer သည် ထုတ်ဝေထားသော SHA256 နှင့် binary checksum ကို စစ်ဆေးပါသည်။ စစ်ဆေးခြင်းကို ကျော်လွှားရန် (အကြံပြုမထားပါ):',
    'Анхдагч байдлаар суулгагч нь нийтлэгдсэн SHA256 нийлбэртэй харьцуулж шалгана. Шалгалтыг алгасахын тулд (зөвлөдөггүй):',
    ''),
('install_prefix_title',
    'Custom Install Prefix',
    'Prefijo de instalación personalizado',
    'Benutzerdefiniertes Installationspräfix',
    '自定义安装前缀',
    'Préfixe d''installation personnalisé',
    'Prefixo de instalação personalizado',
    'カスタムインストールプレフィックス',
    'Tiền tố cài đặt tùy chỉnh',
    'Aangepast installatieprefix',
    'Egyéni telepítési előtag',
    'بادئة تثبيت مخصصة',
    'پیشوند نصب سفارشی',
    'Özel Kurulum Öneki',
    '사용자 지정 설치 경로',
    'คำนำหน้าการติดตั้งแบบกำหนดเอง',
    'စိတ်ကြိုက်ထည့်သွင်းမှုလမ်းကြောင်း',
    'Тохируулсан суулгах зам',
    ''),
('install_prefix_body',
    'Install to a custom location:',
    'Instalar en una ubicación personalizada:',
    'In ein benutzerdefiniertes Verzeichnis installieren:',
    '安装到自定义位置：',
    'Installer dans un emplacement personnalisé :',
    'Instalar em um local personalizado:',
    'カスタムの場所にインストール：',
    'Cài đặt vào vị trí tùy chỉnh:',
    'Installeren op een aangepaste locatie:',
    'Telepítés egyéni helyre:',
    'التثبيت في موقع مخصص:',
    'نصب در مسیر دلخواه:',
    'Özel bir konuma kurulum:',
    '사용자 지정 위치에 설치:',
    'ติดตั้งในตำแหน่งที่กำหนดเอง:',
    'စိတ်ကြိုက်နေရာတွင် ထည့်သွင်းရန်:',
    'Тохируулсан байршилд суулгах:',
    ''),
('install_extras_title',
    'Companion Tools (--extras)',
    'Herramientas complementarias (--extras)',
    'Begleit-Tools (--extras)',
    '附加工具 (--extras)',
    'Outils compagnons (--extras)',
    'Ferramentas complementares (--extras)',
    'コンパニオンツール (--extras)',
    'Công cụ đi kèm (--extras)',
    'Bijkomende tools (--extras)',
    'Kiegészítő eszközök (--extras)',
    'أدوات مصاحبة (--extras)',
    'ابزارهای همراه (--extras)',
    'Yardımcı Araçlar (--extras)',
    '동반 도구 (--extras)',
    'เครื่องมือเสริม (--extras)',
    'လက်တွဲကိရိယာများ (--extras)',
    'Нэмэлт хэрэгслүүд (--extras)',
    ''),
('install_extras_body',
    'PRECC ships with optional companion tools. Install them with `--extras`:',
    'PRECC incluye herramientas complementarias opcionales. Instálelas con `--extras`:',
    'PRECC wird mit optionalen Begleit-Tools ausgeliefert. Installieren Sie diese mit `--extras`:',
    'PRECC附带可选的附加工具。使用 `--extras` 安装它们：',
    'PRECC est livré avec des outils compagnons optionnels. Installez-les avec `--extras` :',
    'O PRECC inclui ferramentas complementares opcionais. Instale-as com `--extras`:',
    'PRECCにはオプションのコンパニオンツールが付属しています。`--extras` でインストールします：',
    'PRECC đi kèm với các công cụ tùy chọn. Cài đặt chúng với `--extras`:',
    'PRECC wordt geleverd met optionele bijkomende tools. Installeer ze met `--extras`:',
    'A PRECC opcionális kiegészítő eszközökkel érkezik. Telepítse őket a `--extras` kapcsolóval:',
    'يأتي PRECC مع أدوات مصاحبة اختيارية. قم بتثبيتها باستخدام `--extras`:',
    'PRECC با ابزارهای همراه اختیاری ارائه می‌شود. آنها را با `--extras` نصب کنید:',
    'PRECC isteğe bağlı yardımcı araçlarla birlikte gelir. Bunları `--extras` ile kurun:',
    'PRECC에는 선택적 동반 도구가 포함되어 있습니다. `--extras`로 설치하세요:',
    'PRECC มาพร้อมกับเครื่องมือเสริมที่เลือกได้ ติดตั้งด้วย `--extras`:',
    'PRECC တွင် ရွေးချယ်နိုင်သော လက်တွဲကိရိယာများ ပါဝင်ပါသည်။ `--extras` ဖြင့် ထည့်သွင်းပါ:',
    'PRECC нь нэмэлт хэрэгслүүдтэй ирдэг. `--extras` ашиглан суулгана:',
    ''),
('install_extras_installs',
    'This installs:',
    'Esto instala:',
    'Dies installiert:',
    '这将安装：',
    'Cela installe :',
    'Isso instala:',
    'これにより以下がインストールされます：',
    'Lệnh này cài đặt:',
    'Dit installeert:',
    'Ez a következőket telepíti:',
    'هذا يثبت:',
    'این موارد زیر را نصب می‌کند:',
    'Bu şunları kurar:',
    '다음을 설치합니다:',
    'คำสั่งนี้จะติดตั้ง:',
    'ဤအရာသည် အောက်ပါတို့ကို ထည့်သွင်းပါသည်:',
    'Энэ нь дараахыг суулгана:',
    ''),
('install_tool_col',
    'Tool',
    'Herramienta',
    'Tool',
    '工具',
    'Outil',
    'Ferramenta',
    'ツール',
    'Công cụ',
    'Tool',
    'Eszköz',
    'أداة',
    'ابزار',
    'Araç',
    '도구',
    'เครื่องมือ',
    'ကိရိယာ',
    'Хэрэгсэл',
    ''),
('install_purpose_col',
    'Purpose',
    'Propósito',
    'Zweck',
    '用途',
    'Fonction',
    'Finalidade',
    '用途',
    'Mục đích',
    'Doel',
    'Cél',
    'الغرض',
    'کاربرد',
    'Amaç',
    '용도',
    'วัตถุประสงค์',
    'ရည်ရွယ်ချက်',
    'Зорилго',
    ''),
('install_rtk_desc',
    'Command rewriting toolkit',
    'Kit de reescritura de comandos',
    'Befehlsumschreibungs-Toolkit',
    '命令重写工具包',
    'Kit de réécriture de commandes',
    'Kit de reescrita de comandos',
    'コマンド書き換えツールキット',
    'Bộ công cụ viết lại lệnh',
    'Toolkit voor herschrijven van commando''s',
    'Parancs-újraíró eszközkészlet',
    'مجموعة أدوات إعادة كتابة الأوامر',
    'مجموعه ابزار بازنویسی دستورات',
    'Komut yeniden yazma araç seti',
    '명령어 재작성 도구 모음',
    'ชุดเครื่องมือเขียนคำสั่งใหม่',
    'Command ပြန်လည်ရေးသားခြင်း toolkit',
    'Командыг дахин бичих хэрэгсэл',
    ''),
('install_leanctx_desc',
    'Context compression for CLAUDE.md and prompt files',
    'Compresión de contexto para CLAUDE.md y archivos de prompt',
    'Kontextkomprimierung für CLAUDE.md und Prompt-Dateien',
    'CLAUDE.md和提示文件的上下文压缩',
    'Compression de contexte pour CLAUDE.md et les fichiers de prompt',
    'Compressão de contexto para CLAUDE.md e arquivos de prompt',
    'CLAUDE.mdおよびプロンプトファイルのコンテキスト圧縮',
    'Nén ngữ cảnh cho CLAUDE.md và các tệp prompt',
    'Contextcompressie voor CLAUDE.md en promptbestanden',
    'Kontextus tömörítés CLAUDE.md és prompt fájlokhoz',
    'ضغط السياق لملفات CLAUDE.md والتعليمات',
    'فشرده‌سازی زمینه برای CLAUDE.md و فایل‌های prompt',
    'CLAUDE.md ve prompt dosyaları için bağlam sıkıştırma',
    'CLAUDE.md 및 프롬프트 파일용 컨텍스트 압축',
    'การบีบอัดบริบทสำหรับ CLAUDE.md และไฟล์ prompt',
    'CLAUDE.md နှင့် prompt ဖိုင်များအတွက် context ချုံ့ခြင်း',
    'CLAUDE.md болон prompt файлуудын контекст шахалт',
    ''),
('install_nushell_desc',
    'Structured shell for advanced pipelines',
    'Shell estructurado para pipelines avanzados',
    'Strukturierte Shell für erweiterte Pipelines',
    '用于高级管道的结构化Shell',
    'Shell structuré pour les pipelines avancés',
    'Shell estruturado para pipelines avançados',
    '高度なパイプライン用の構造化シェル',
    'Shell có cấu trúc cho pipeline nâng cao',
    'Gestructureerde shell voor geavanceerde pipelines',
    'Strukturált shell fejlett pipeline-okhoz',
    'صدفة منظمة لخطوط الأنابيب المتقدمة',
    'شل ساختاریافته برای پایپلاین‌های پیشرفته',
    'Gelişmiş boru hatları için yapılandırılmış kabuk',
    '고급 파이프라인을 위한 구조화된 셸',
    'เชลล์แบบมีโครงสร้างสำหรับ pipeline ขั้นสูง',
    'အဆင့်မြင့် pipeline များအတွက် ဖွဲ့စည်းထားသော shell',
    'Дэвшилтэт pipeline-д зориулсан бүтэцтэй shell',
    ''),
('install_cocoindex_desc',
    'Code indexing for faster context resolution',
    'Indexación de código para una resolución de contexto más rápida',
    'Code-Indexierung für schnellere Kontextauflösung',
    '代码索引以加快上下文解析',
    'Indexation du code pour une résolution de contexte plus rapide',
    'Indexação de código para resolução de contexto mais rápida',
    'より高速なコンテキスト解決のためのコードインデックス',
    'Lập chỉ mục mã để giải quyết ngữ cảnh nhanh hơn',
    'Code-indexering voor snellere contextresolutie',
    'Kódindexelés a gyorsabb kontextusfeloldáshoz',
    'فهرسة الكود لحل السياق بشكل أسرع',
    'نمایه‌سازی کد برای حل سریع‌تر زمینه',
    'Daha hızlı bağlam çözümleme için kod indeksleme',
    '더 빠른 컨텍스트 해결을 위한 코드 인덱싱',
    'การจัดทำดัชนีโค้ดเพื่อการแก้ไขบริบทที่เร็วขึ้น',
    'ပိုမြန်သော context ဖြေရှင်းခြင်းအတွက် code indexing',
    'Контекстыг хурдан шийдвэрлэхэд зориулсан код индекслэл',
    ''),
('install_windows_title',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    'Windows (PowerShell)',
    ''),
('install_windows_then',
    'Then initialize:',
    'Luego inicialice:',
    'Dann initialisieren:',
    '然后初始化：',
    'Puis initialisez :',
    'Em seguida, inicialize:',
    '次に初期化します：',
    'Sau đó khởi tạo:',
    'Vervolgens initialiseren:',
    'Ezután inicializálja:',
    'ثم قم بالتهيئة:',
    'سپس مقداردهی اولیه کنید:',
    'Ardından başlatın:',
    '그런 다음 초기화하세요:',
    'จากนั้นเริ่มต้น:',
    'ထို့နောက် စတင်ပါ:',
    'Дараа нь эхлүүлнэ:',
    ''),
('install_manual_title',
    'Manual Install',
    'Instalación manual',
    'Manuelle Installation',
    '手动安装',
    'Installation manuelle',
    'Instalação manual',
    '手動インストール',
    'Cài đặt thủ công',
    'Handmatige installatie',
    'Kézi telepítés',
    'التثبيت اليدوي',
    'نصب دستی',
    'Manuel Kurulum',
    '수동 설치',
    'การติดตั้งด้วยตนเอง',
    'လက်ဖြင့်ထည့်သွင်းခြင်း',
    'Гараар суулгах',
    ''),
('install_manual_step1',
    'Download the release binary for your platform from [GitHub Releases](https://github.com/peria-ai/precc-cc/releases).',
    'Descargue el binario de lanzamiento para su plataforma desde [GitHub Releases](https://github.com/peria-ai/precc-cc/releases).',
    'Laden Sie die Release-Binary für Ihre Plattform von [GitHub Releases](https://github.com/peria-ai/precc-cc/releases) herunter.',
    '从 [GitHub Releases](https://github.com/peria-ai/precc-cc/releases) 下载适用于您平台的发布二进制文件。',
    'Téléchargez le binaire pour votre plateforme depuis [GitHub Releases](https://github.com/peria-ai/precc-cc/releases).',
    'Baixe o binário de lançamento para sua plataforma em [GitHub Releases](https://github.com/peria-ai/precc-cc/releases).',
    'お使いのプラットフォーム用のリリースバイナリを [GitHub Releases](https://github.com/peria-ai/precc-cc/releases) からダウンロードします。',
    'Tải xuống tệp nhị phân cho nền tảng của bạn từ [GitHub Releases](https://github.com/peria-ai/precc-cc/releases).',
    'Download de release-binary voor uw platform van [GitHub Releases](https://github.com/peria-ai/precc-cc/releases).',
    'Töltse le a kiadás binárisát platformjához a [GitHub Releases](https://github.com/peria-ai/precc-cc/releases) oldalról.',
    'قم بتنزيل الملف الثنائي لمنصتك من [GitHub Releases](https://github.com/peria-ai/precc-cc/releases).',
    'فایل باینری نسخه مربوط به پلتفرم خود را از [GitHub Releases](https://github.com/peria-ai/precc-cc/releases) دانلود کنید.',
    'Platformunuz için sürüm ikili dosyasını [GitHub Releases](https://github.com/peria-ai/precc-cc/releases) adresinden indirin.',
    '플랫폼에 맞는 릴리스 바이너리를 [GitHub Releases](https://github.com/peria-ai/precc-cc/releases)에서 다운로드하세요.',
    'ดาวน์โหลดไบนารีสำหรับแพลตฟอร์มของคุณจาก [GitHub Releases](https://github.com/peria-ai/precc-cc/releases)',
    'သင့်ပလက်ဖောင်းအတွက် release binary ကို [GitHub Releases](https://github.com/peria-ai/precc-cc/releases) မှ ဒေါင်းလုဒ်လုပ်ပါ။',
    'Платформдоо зориулсан хувилбарыг [GitHub Releases](https://github.com/peria-ai/precc-cc/releases) хуудаснаас татаж авна.',
    ''),
('install_manual_step2',
    'Verify the SHA256 checksum against the `.sha256` file in the release.',
    'Verifique la suma de comprobación SHA256 contra el archivo `.sha256` del lanzamiento.',
    'Verifizieren Sie die SHA256-Prüfsumme anhand der `.sha256`-Datei im Release.',
    '根据版本中的 `.sha256` 文件验证SHA256校验和。',
    'Vérifiez la somme de contrôle SHA256 par rapport au fichier `.sha256` de la version.',
    'Verifique a soma de verificação SHA256 com o arquivo `.sha256` da versão.',
    'リリースの `.sha256` ファイルに対してSHA256チェックサムを検証します。',
    'Xác minh mã SHA256 với tệp `.sha256` trong bản phát hành.',
    'Verifieer de SHA256-checksum tegen het `.sha256`-bestand in de release.',
    'Ellenőrizze a SHA256 ellenőrző összeget a kiadás `.sha256` fájljával.',
    'تحقق من المجموع الاختباري SHA256 مقابل ملف `.sha256` في الإصدار.',
    'جمع‌آزمای SHA256 را با فایل `.sha256` در نسخه تأیید کنید.',
    'SHA256 sağlama toplamını sürümdeki `.sha256` dosyasıyla doğrulayın.',
    '릴리스의 `.sha256` 파일과 SHA256 체크섬을 확인하세요.',
    'ตรวจสอบ SHA256 checksum กับไฟล์ `.sha256` ในรุ่นที่เผยแพร่',
    'release ရှိ `.sha256` ဖိုင်နှင့် SHA256 checksum ကို စစ်ဆေးပါ။',
    'SHA256 шалгах нийлбэрийг хувилбар дахь `.sha256` файлтай тулгаж шалгана.',
    ''),
('install_manual_step3',
    'Place the binary in a directory on your `PATH` (e.g., `~/.local/bin/`).',
    'Coloque el binario en un directorio de su `PATH` (p. ej., `~/.local/bin/`).',
    'Platzieren Sie die Binary in einem Verzeichnis in Ihrem `PATH` (z.B. `~/.local/bin/`).',
    '将二进制文件放置在 `PATH` 中的目录中（例如 `~/.local/bin/`）。',
    'Placez le binaire dans un répertoire de votre `PATH` (par ex., `~/.local/bin/`).',
    'Coloque o binário em um diretório no seu `PATH` (ex.: `~/.local/bin/`).',
    'バイナリを `PATH` 上のディレクトリ（例：`~/.local/bin/`）に配置します。',
    'Đặt tệp nhị phân vào thư mục trong `PATH` của bạn (ví dụ: `~/.local/bin/`).',
    'Plaats de binary in een map op uw `PATH` (bijv. `~/.local/bin/`).',
    'Helyezze a binárist a `PATH`-on lévő könyvtárba (pl. `~/.local/bin/`).',
    'ضع الملف الثنائي في دليل ضمن `PATH` الخاص بك (مثل `~/.local/bin/`).',
    'فایل باینری را در پوشه‌ای در `PATH` خود قرار دهید (مثلاً `~/.local/bin/`).',
    'İkili dosyayı `PATH` üzerindeki bir dizine yerleştirin (örn. `~/.local/bin/`).',
    '바이너리를 `PATH`에 있는 디렉토리(예: `~/.local/bin/`)에 배치하세요.',
    'วางไบนารีในไดเรกทอรีบน `PATH` ของคุณ (เช่น `~/.local/bin/`)',
    'binary ကို သင့် `PATH` ရှိ directory တွင် ထားပါ (ဥပမာ `~/.local/bin/`)။',
    'Бинари файлыг `PATH` дээрх хавтаст байрлуулна (жнь `~/.local/bin/`).',
    ''),
('install_manual_step4',
    'Run `precc init`.',
    'Ejecute `precc init`.',
    'Führen Sie `precc init` aus.',
    '运行 `precc init`。',
    'Exécutez `precc init`.',
    'Execute `precc init`.',
    '`precc init` を実行します。',
    'Chạy `precc init`.',
    'Voer `precc init` uit.',
    'Futtassa a `precc init` parancsot.',
    'قم بتشغيل `precc init`.',
    '`precc init` را اجرا کنید.',
    '`precc init` komutunu çalıştırın.',
    '`precc init`을 실행하세요.',
    'รัน `precc init`',
    '`precc init` ကို run ပါ။',
    '`precc init` ажиллуулна.',
    ''),
('install_updating_title',
    'Updating',
    'Actualización',
    'Aktualisierung',
    '更新',
    'Mise à jour',
    'Atualização',
    'アップデート',
    'Cập nhật',
    'Bijwerken',
    'Frissítés',
    'التحديث',
    'به‌روزرسانی',
    'Güncelleme',
    '업데이트',
    'การอัปเดต',
    'အပ်ဒိတ်လုပ်ခြင်း',
    'Шинэчлэх',
    ''),
('install_update_force',
    'Force update to a specific version:',
    'Forzar la actualización a una versión específica:',
    'Erzwinge ein Update auf eine bestimmte Version:',
    '强制更新到特定版本：',
    'Forcer la mise à jour vers une version spécifique :',
    'Forçar atualização para uma versão específica:',
    '特定のバージョンへ強制アップデート：',
    'Buộc cập nhật lên phiên bản cụ thể:',
    'Forceer een update naar een specifieke versie:',
    'Kényszerített frissítés egy adott verzióra:',
    'فرض التحديث إلى إصدار محدد:',
    'به‌روزرسانی اجباری به نسخه مشخص:',
    'Belirli bir sürüme zorla güncelleme:',
    '특정 버전으로 강제 업데이트:',
    'บังคับอัปเดตเป็นเวอร์ชันเฉพาะ:',
    'အတိအကျ version တစ်ခုသို့ အတင်း update လုပ်ရန်:',
    'Тодорхой хувилбар руу албадан шинэчлэх:',
    ''),
('install_update_auto',
    'Enable automatic updates:',
    'Habilitar actualizaciones automáticas:',
    'Automatische Updates aktivieren:',
    '启用自动更新：',
    'Activer les mises à jour automatiques :',
    'Ativar atualizações automáticas:',
    '自動アップデートを有効にする：',
    'Bật cập nhật tự động:',
    'Automatische updates inschakelen:',
    'Automatikus frissítések engedélyezése:',
    'تمكين التحديثات التلقائية:',
    'فعال‌سازی به‌روزرسانی خودکار:',
    'Otomatik güncellemeleri etkinleştir:',
    '자동 업데이트 활성화:',
    'เปิดใช้งานการอัปเดตอัตโนมัติ:',
    'အလိုအလျောက် update များကို ဖွင့်ရန်:',
    'Автомат шинэчлэлтийг идэвхжүүлэх:',
    ''),
('install_verify_title',
    'Verifying Installation',
    'Verificación de la instalación',
    'Installation überprüfen',
    '验证安装',
    'Vérification de l''installation',
    'Verificando a instalação',
    'インストールの確認',
    'Xác minh cài đặt',
    'Installatie verifiëren',
    'Telepítés ellenőrzése',
    'التحقق من التثبيت',
    'تأیید نصب',
    'Kurulumu Doğrulama',
    '설치 확인',
    'การตรวจสอบการติดตั้ง',
    'ထည့်သွင်းမှုကို အတည်ပြုခြင်း',
    'Суулгалтыг шалгах',
    ''),
('install_verify_path_note',
    'If `precc` is not found, ensure `~/.local/bin` is on your `PATH`.',
    'Si `precc` no se encuentra, asegúrese de que `~/.local/bin` esté en su `PATH`.',
    'Wenn `precc` nicht gefunden wird, stellen Sie sicher, dass `~/.local/bin` in Ihrem `PATH` ist.',
    '如果找不到 `precc`，请确保 `~/.local/bin` 在您的 `PATH` 中。',
    'Si `precc` n''est pas trouvé, assurez-vous que `~/.local/bin` est dans votre `PATH`.',
    'Se `precc` não for encontrado, certifique-se de que `~/.local/bin` está no seu `PATH`.',
    '`precc` が見つからない場合は、`~/.local/bin` が `PATH` に含まれていることを確認してください。',
    'Nếu không tìm thấy `precc`, hãy đảm bảo `~/.local/bin` nằm trong `PATH` của bạn.',
    'Als `precc` niet wordt gevonden, zorg ervoor dat `~/.local/bin` op uw `PATH` staat.',
    'Ha a `precc` nem található, győződjön meg arról, hogy a `~/.local/bin` rajta van a `PATH`-on.',
    'إذا لم يتم العثور على `precc`، تأكد من أن `~/.local/bin` موجود في `PATH` الخاص بك.',
    'اگر `precc` پیدا نشد، مطمئن شوید که `~/.local/bin` در `PATH` شما قرار دارد.',
    '`precc` bulunamazsa, `~/.local/bin` dizininin `PATH` üzerinde olduğundan emin olun.',
    '`precc`를 찾을 수 없는 경우 `~/.local/bin`이 `PATH`에 포함되어 있는지 확인하세요.',
    'หากไม่พบ `precc` ให้ตรวจสอบว่า `~/.local/bin` อยู่ใน `PATH` ของคุณ',
    '`precc` ကို ရှာမတွေ့ပါက `~/.local/bin` သည် သင့် `PATH` တွင် ရှိမရှိ စစ်ဆေးပါ။',
    '`precc` олдохгүй бол `~/.local/bin` таны `PATH` дээр байгаа эсэхийг шалгана уу.',
    '');
