-- Hook Pipeline chapter strings
INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_title',
    'Hook Pipeline',
    'Pipeline del Hook',
    'Hook-Pipeline',
    '钩子管道',
    'Pipeline du Hook',
    'Pipeline do Hook',
    'フックパイプライン',
    'Đường ống Hook',
    'Hook Pipeline',
    'Hook Pipeline',
    'أنبوب الخطاف',
    'خط لوله هوک',
    'Hook Pipeline',
    '훅 파이프라인',
    'ไปป์ไลน์ Hook',
    'Hook Pipeline',
    'Hook Pipeline',
    '',
    'Pipeline Hooka');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_intro',
    'The `precc-hook` binary is the core of PRECC. It sits between Claude Code and the shell, processing every bash command in under 5 milliseconds.',
    'El binario `precc-hook` es el núcleo de PRECC. Se sitúa entre Claude Code y el shell, procesando cada comando bash en menos de 5 milisegundos.',
    'Die `precc-hook`-Binary ist der Kern von PRECC. Sie sitzt zwischen Claude Code und der Shell und verarbeitet jeden Bash-Befehl in unter 5 Millisekunden.',
    '`precc-hook` 二进制文件是PRECC的核心。它位于Claude Code和shell之间，在5毫秒内处理每个bash命令。',
    'Le binaire `precc-hook` est le cœur de PRECC. Il se place entre Claude Code et le shell, traitant chaque commande bash en moins de 5 millisecondes.',
    'O binário `precc-hook` é o núcleo do PRECC. Ele fica entre o Claude Code e o shell, processando cada comando bash em menos de 5 milissegundos.',
    '`precc-hook` バイナリはPRECCの中核です。Claude Codeとシェルの間に位置し、すべてのbashコマンドを5ミリ秒以内に処理します。',
    'Binary `precc-hook` là cốt lõi của PRECC. Nó nằm giữa Claude Code và shell, xử lý mọi lệnh bash trong vòng dưới 5 mili giây.',
    'Het `precc-hook` binary is de kern van PRECC. Het zit tussen Claude Code en de shell en verwerkt elk bash-commando in minder dan 5 milliseconden.',
    'A `precc-hook` bináris a PRECC magja. A Claude Code és a shell között helyezkedik el, és minden bash parancsot 5 milliszekundum alatt dolgoz fel.',
    'ملف `precc-hook` الثنائي هو جوهر PRECC. يقع بين Claude Code والصدفة، ويعالج كل أمر bash في أقل من 5 ميلي ثانية.',
    'باینری `precc-hook` هسته PRECC است. بین Claude Code و شل قرار می‌گیرد و هر دستور bash را در کمتر از ۵ میلی‌ثانیه پردازش می‌کند.',
    '`precc-hook` ikili dosyası PRECC''nin çekirdeğidir. Claude Code ile kabuk arasında yer alır ve her bash komutunu 5 milisaniyenin altında işler.',
    '`precc-hook` 바이너리는 PRECC의 핵심입니다. Claude Code와 셸 사이에 위치하여 모든 bash 명령을 5밀리초 이내에 처리합니다.',
    'ไบนารี `precc-hook` เป็นแกนหลักของ PRECC อยู่ระหว่าง Claude Code กับ shell ประมวลผลทุกคำสั่ง bash ภายใน 5 มิลลิวินาที',
    '`precc-hook` binary သည် PRECC ၏ အဓိကအစိတ်အပိုင်းဖြစ်သည်။ Claude Code နှင့် shell ကြားတွင်ရှိပြီး bash command တိုင်းကို 5 millisecond အတွင်း လုပ်ဆောင်သည်။',
    '`precc-hook` хоёртын файл нь PRECC-ийн цөм юм. Claude Code болон shell-ийн хооронд байрлаж, bash команд бүрийг 5 миллисекундын дотор боловсруулна.',
    '',
    'Plik binarny `precc-hook` jest rdzeniem PRECC. Znajduje się między Claude Code a powłoką, przetwarzając każde polecenie bash w mniej niż 5 milisekund.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_invocation_title',
    'How Claude Code Invokes the Hook',
    'Cómo Claude Code invoca el Hook',
    'Wie Claude Code den Hook aufruft',
    'Claude Code如何调用钩子',
    'Comment Claude Code invoque le Hook',
    'Como o Claude Code invoca o Hook',
    'Claude Codeがフックを呼び出す方法',
    'Cách Claude Code gọi Hook',
    'Hoe Claude Code de Hook aanroept',
    'Hogyan hívja meg a Claude Code a Hookot',
    'كيف يستدعي Claude Code الخطاف',
    'نحوه فراخوانی هوک توسط Claude Code',
    'Claude Code Hook''u nasıl çağırır',
    'Claude Code가 훅을 호출하는 방법',
    'วิธีที่ Claude Code เรียกใช้ Hook',
    'Claude Code က Hook ကို ခေါ်ယူပုံ',
    'Claude Code Hook-ийг хэрхэн дуудах вэ',
    '',
    'Jak Claude Code wywołuje Hook');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_invocation_body',
    'Claude Code supports PreToolUse hooks -- external programs that can inspect and modify tool inputs before execution. When Claude is about to run a bash command, it sends JSON to `precc-hook` on stdin and reads the response from stdout.',
    'Claude Code soporta hooks PreToolUse -- programas externos que pueden inspeccionar y modificar las entradas de herramientas antes de la ejecución. Cuando Claude está a punto de ejecutar un comando bash, envía JSON a `precc-hook` por stdin y lee la respuesta de stdout.',
    'Claude Code unterstützt PreToolUse-Hooks -- externe Programme, die Werkzeugeingaben vor der Ausführung inspizieren und ändern können. Wenn Claude einen Bash-Befehl ausführen will, sendet es JSON an `precc-hook` über stdin und liest die Antwort von stdout.',
    'Claude Code支持PreToolUse钩子——可以在执行前检查和修改工具输入的外部程序。当Claude即将运行bash命令时，它通过stdin将JSON发送给 `precc-hook` 并从stdout读取响应。',
    'Claude Code prend en charge les hooks PreToolUse -- des programmes externes qui peuvent inspecter et modifier les entrées d''outils avant l''exécution. Quand Claude est sur le point d''exécuter une commande bash, il envoie du JSON à `precc-hook` sur stdin et lit la réponse depuis stdout.',
    'O Claude Code suporta hooks PreToolUse -- programas externos que podem inspecionar e modificar entradas de ferramentas antes da execução. Quando o Claude está prestes a executar um comando bash, ele envia JSON para `precc-hook` via stdin e lê a resposta de stdout.',
    'Claude CodeはPreToolUseフックをサポートしています。これは実行前にツール入力を検査・変更できる外部プログラムです。Claudeがbashコマンドを実行しようとすると、stdinで `precc-hook` にJSONを送信し、stdoutからレスポンスを読み取ります。',
    'Claude Code hỗ trợ các hook PreToolUse -- chương trình bên ngoài có thể kiểm tra và sửa đổi đầu vào công cụ trước khi thực thi. Khi Claude sắp chạy lệnh bash, nó gửi JSON đến `precc-hook` qua stdin và đọc phản hồi từ stdout.',
    'Claude Code ondersteunt PreToolUse hooks -- externe programma''s die tool-invoer kunnen inspecteren en wijzigen vóór uitvoering. Wanneer Claude een bash-commando gaat uitvoeren, stuurt het JSON naar `precc-hook` op stdin en leest het antwoord van stdout.',
    'A Claude Code támogatja a PreToolUse hookokat -- külső programokat, amelyek a végrehajtás előtt megvizsgálhatják és módosíthatják az eszközbemeneteket. Amikor a Claude bash parancsot készül futtatni, JSON-t küld a `precc-hook`-nak stdin-en és kiolvassa a választ stdout-ról.',
    'يدعم Claude Code خطافات PreToolUse -- برامج خارجية يمكنها فحص وتعديل مدخلات الأدوات قبل التنفيذ. عندما يكون Claude على وشك تشغيل أمر bash، يرسل JSON إلى `precc-hook` عبر stdin ويقرأ الاستجابة من stdout.',
    'Claude Code از هوک‌های PreToolUse پشتیبانی می‌کند -- برنامه‌های خارجی که می‌توانند ورودی‌های ابزار را قبل از اجرا بررسی و تغییر دهند. وقتی Claude قصد اجرای دستور bash را دارد، JSON را به `precc-hook` از طریق stdin ارسال و پاسخ را از stdout می‌خواند.',
    'Claude Code, PreToolUse hook''larını destekler -- yürütmeden önce araç girdilerini inceleyip değiştirebilen harici programlar. Claude bir bash komutu çalıştırmak üzereyken, stdin üzerinden `precc-hook`''a JSON gönderir ve stdout''dan yanıtı okur.',
    'Claude Code는 PreToolUse 훅을 지원합니다 -- 실행 전에 도구 입력을 검사하고 수정할 수 있는 외부 프로그램입니다. Claude가 bash 명령을 실행하려 할 때, stdin으로 `precc-hook`에 JSON을 보내고 stdout에서 응답을 읽습니다.',
    'Claude Code รองรับ hook PreToolUse -- โปรแกรมภายนอกที่สามารถตรวจสอบและแก้ไขอินพุตของเครื่องมือก่อนการทำงาน เมื่อ Claude กำลังจะรันคำสั่ง bash จะส่ง JSON ไปยัง `precc-hook` ผ่าน stdin และอ่านผลลัพธ์จาก stdout',
    'Claude Code သည် PreToolUse hook များကို ပံ့ပိုးသည် -- လုပ်ဆောင်မှုမတိုင်မီ tool input များကို စစ်ဆေးပြီး ပြင်ဆင်နိုင်သော ပြင်ပပရိုဂရမ်များဖြစ်သည်။ Claude က bash command ကို run မည့်အခါ stdin မှတဆင့် `precc-hook` သို့ JSON ပေးပို့ပြီး stdout မှ တုံ့ပြန်မှုကို ဖတ်သည်။',
    'Claude Code нь PreToolUse hook-уудыг дэмждэг -- гүйцэтгэхээс өмнө хэрэгслийн оролтыг шалгаж, өөрчилж чадах гадаад программууд. Claude bash команд ажиллуулах гэж байгаа үед stdin-ээр `precc-hook`-д JSON илгээж, stdout-аас хариуг уншина.',
    '',
    'Claude Code obsługuje hooki PreToolUse -- zewnętrzne programy, które mogą sprawdzać i modyfikować dane wejściowe narzędzi przed wykonaniem. Gdy Claude zamierza uruchomić polecenie bash, wysyła JSON do `precc-hook` na stdin i odczytuje odpowiedź ze stdout.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stages_title',
    'Pipeline Stages',
    'Etapas del Pipeline',
    'Pipeline-Stufen',
    '管道阶段',
    'Étapes du Pipeline',
    'Estágios do Pipeline',
    'パイプラインステージ',
    'Các giai đoạn Pipeline',
    'Pipeline Stappen',
    'Pipeline szakaszok',
    'مراحل الأنبوب',
    'مراحل خط لوله',
    'Pipeline Aşamaları',
    '파이프라인 단계',
    'ขั้นตอน Pipeline',
    'Pipeline အဆင့်များ',
    'Pipeline-ийн үе шатууд',
    '',
    'Etapy Pipeline');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_example_title',
    'Example: JSON Input and Output',
    'Ejemplo: Entrada y salida JSON',
    'Beispiel: JSON Ein- und Ausgabe',
    '示例：JSON输入和输出',
    'Exemple : Entrée et sortie JSON',
    'Exemplo: Entrada e saída JSON',
    '例：JSONの入出力',
    'Ví dụ: Đầu vào và đầu ra JSON',
    'Voorbeeld: JSON invoer en uitvoer',
    'Példa: JSON bemenet és kimenet',
    'مثال: إدخال وإخراج JSON',
    'مثال: ورودی و خروجی JSON',
    'Örnek: JSON Girdi ve Çıktı',
    '예제: JSON 입력 및 출력',
    'ตัวอย่าง: อินพุตและเอาต์พุต JSON',
    'ဥပမာ: JSON Input နှင့် Output',
    'Жишээ: JSON оролт ба гаралт',
    '',
    'Przykład: Wejście i wyjście JSON');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_example_input',
    'Input (from Claude Code)',
    'Entrada (desde Claude Code)',
    'Eingabe (von Claude Code)',
    '输入（来自Claude Code）',
    'Entrée (depuis Claude Code)',
    'Entrada (do Claude Code)',
    '入力（Claude Codeから）',
    'Đầu vào (từ Claude Code)',
    'Invoer (van Claude Code)',
    'Bemenet (Claude Code-tól)',
    'الإدخال (من Claude Code)',
    'ورودی (از Claude Code)',
    'Girdi (Claude Code''dan)',
    '입력 (Claude Code에서)',
    'อินพุต (จาก Claude Code)',
    'Input (Claude Code မှ)',
    'Оролт (Claude Code-оос)',
    '',
    'Wejście (z Claude Code)');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_example_explanation',
    'PRECC detects that the current directory has no `Cargo.toml`, but `./myapp/Cargo.toml` exists.',
    'PRECC detecta que el directorio actual no tiene `Cargo.toml`, pero `./myapp/Cargo.toml` existe.',
    'PRECC erkennt, dass das aktuelle Verzeichnis kein `Cargo.toml` hat, aber `./myapp/Cargo.toml` existiert.',
    'PRECC检测到当前目录没有 `Cargo.toml`，但 `./myapp/Cargo.toml` 存在。',
    'PRECC détecte que le répertoire actuel n''a pas de `Cargo.toml`, mais `./myapp/Cargo.toml` existe.',
    'O PRECC detecta que o diretório atual não tem `Cargo.toml`, mas `./myapp/Cargo.toml` existe.',
    'PRECCは現在のディレクトリに `Cargo.toml` がないが、`./myapp/Cargo.toml` が存在することを検出します。',
    'PRECC phát hiện thư mục hiện tại không có `Cargo.toml`, nhưng `./myapp/Cargo.toml` tồn tại.',
    'PRECC detecteert dat de huidige map geen `Cargo.toml` heeft, maar `./myapp/Cargo.toml` wel bestaat.',
    'A PRECC észleli, hogy az aktuális könyvtárban nincs `Cargo.toml`, de `./myapp/Cargo.toml` létezik.',
    'يكتشف PRECC أن الدليل الحالي لا يحتوي على `Cargo.toml`، لكن `./myapp/Cargo.toml` موجود.',
    'PRECC تشخیص می‌دهد که دایرکتوری فعلی `Cargo.toml` ندارد، اما `./myapp/Cargo.toml` وجود دارد.',
    'PRECC, geçerli dizinde `Cargo.toml` olmadığını ancak `./myapp/Cargo.toml` dosyasının var olduğunu tespit eder.',
    'PRECC는 현재 디렉토리에 `Cargo.toml`이 없지만 `./myapp/Cargo.toml`이 존재함을 감지합니다.',
    'PRECC ตรวจพบว่าไดเรกทอรีปัจจุบันไม่มี `Cargo.toml` แต่ `./myapp/Cargo.toml` มีอยู่',
    'PRECC သည် လက်ရှိ directory တွင် `Cargo.toml` မရှိသော်လည်း `./myapp/Cargo.toml` ရှိကြောင်း ရှာဖွေတွေ့ရှိသည်။',
    'PRECC одоогийн хавтаст `Cargo.toml` байхгүйг, гэхдээ `./myapp/Cargo.toml` байгааг илрүүлнэ.',
    '',
    'PRECC wykrywa, że bieżący katalog nie ma `Cargo.toml`, ale `./myapp/Cargo.toml` istnieje.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_example_output',
    'Output (to Claude Code)',
    'Salida (a Claude Code)',
    'Ausgabe (an Claude Code)',
    '输出（到Claude Code）',
    'Sortie (vers Claude Code)',
    'Saída (para o Claude Code)',
    '出力（Claude Codeへ）',
    'Đầu ra (đến Claude Code)',
    'Uitvoer (naar Claude Code)',
    'Kimenet (Claude Code-nak)',
    'الإخراج (إلى Claude Code)',
    'خروجی (به Claude Code)',
    'Çıktı (Claude Code''a)',
    '출력 (Claude Code로)',
    'เอาต์พุต (ไปยัง Claude Code)',
    'Output (Claude Code သို့)',
    'Гаралт (Claude Code руу)',
    '',
    'Wyjście (do Claude Code)');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_no_modification_note',
    'If no modification is needed, `updatedInput.command` is empty and Claude Code uses the original command.',
    'Si no se necesita modificación, `updatedInput.command` está vacío y Claude Code usa el comando original.',
    'Wenn keine Änderung nötig ist, ist `updatedInput.command` leer und Claude Code verwendet den ursprünglichen Befehl.',
    '如果不需要修改，`updatedInput.command` 为空，Claude Code使用原始命令。',
    'Si aucune modification n''est nécessaire, `updatedInput.command` est vide et Claude Code utilise la commande originale.',
    'Se nenhuma modificação for necessária, `updatedInput.command` estará vazio e o Claude Code usará o comando original.',
    '変更が不要な場合、`updatedInput.command` は空となり、Claude Codeは元のコマンドを使用します。',
    'Nếu không cần sửa đổi, `updatedInput.command` sẽ trống và Claude Code sử dụng lệnh gốc.',
    'Als er geen wijziging nodig is, is `updatedInput.command` leeg en gebruikt Claude Code het oorspronkelijke commando.',
    'Ha nincs szükség módosításra, az `updatedInput.command` üres, és a Claude Code az eredeti parancsot használja.',
    'إذا لم تكن هناك حاجة للتعديل، يكون `updatedInput.command` فارغًا ويستخدم Claude Code الأمر الأصلي.',
    'اگر نیازی به تغییر نباشد، `updatedInput.command` خالی است و Claude Code از دستور اصلی استفاده می‌کند.',
    'Değişiklik gerekmiyorsa, `updatedInput.command` boş olur ve Claude Code orijinal komutu kullanır.',
    '수정이 필요하지 않으면 `updatedInput.command`가 비어 있고 Claude Code는 원래 명령을 사용합니다.',
    'หากไม่จำเป็นต้องแก้ไข `updatedInput.command` จะว่างเปล่าและ Claude Code จะใช้คำสั่งเดิม',
    'ပြင်ဆင်ရန် မလိုအပ်ပါက `updatedInput.command` သည် ဗလာဖြစ်ပြီး Claude Code သည် မူရင်း command ကို အသုံးပြုသည်။',
    'Өөрчлөлт шаардлагагүй бол `updatedInput.command` хоосон байх ба Claude Code анхны командыг ашиглана.',
    '',
    'Jeśli nie jest potrzebna modyfikacja, `updatedInput.command` jest pusty i Claude Code używa oryginalnego polecenia.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage_details_title',
    'Stage Details',
    'Detalles de las etapas',
    'Stufendetails',
    '阶段详情',
    'Détails des étapes',
    'Detalhes dos estágios',
    'ステージ詳細',
    'Chi tiết các giai đoạn',
    'Stap Details',
    'Szakasz részletei',
    'تفاصيل المراحل',
    'جزئیات مراحل',
    'Aşama Detayları',
    '단계 세부 정보',
    'รายละเอียดขั้นตอน',
    'အဆင့်အသေးစိတ်',
    'Үе шатны дэлгэрэнгүй',
    '',
    'Szczegóły etapów');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage1_title',
    'Stage 1: Parse JSON',
    'Etapa 1: Analizar JSON',
    'Stufe 1: JSON parsen',
    '阶段1：解析JSON',
    'Étape 1 : Analyser le JSON',
    'Estágio 1: Analisar JSON',
    'ステージ1：JSON解析',
    'Giai đoạn 1: Phân tích JSON',
    'Stap 1: JSON Parsen',
    '1. szakasz: JSON elemzés',
    'المرحلة 1: تحليل JSON',
    'مرحله ۱: تجزیه JSON',
    'Aşama 1: JSON Ayrıştırma',
    '단계 1: JSON 파싱',
    'ขั้นตอนที่ 1: แยกวิเคราะห์ JSON',
    'အဆင့် 1: JSON ခွဲခြမ်းစိတ်ဖြာ',
    'Үе шат 1: JSON задлах',
    '',
    'Etap 1: Parsowanie JSON');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage1_body',
    'Reads the full JSON object from stdin. Extracts `tool_input.command`. If parsing fails, the hook exits immediately and Claude Code uses the original command (fail-open design).',
    'Lee el objeto JSON completo desde stdin. Extrae `tool_input.command`. Si el análisis falla, el hook sale inmediatamente y Claude Code usa el comando original (diseño fail-open).',
    'Liest das vollständige JSON-Objekt von stdin. Extrahiert `tool_input.command`. Bei einem Parsing-Fehler beendet sich der Hook sofort und Claude Code verwendet den ursprünglichen Befehl (Fail-Open-Design).',
    '从stdin读取完整的JSON对象。提取 `tool_input.command`。如果解析失败，钩子立即退出，Claude Code使用原始命令（fail-open设计）。',
    'Lit l''objet JSON complet depuis stdin. Extrait `tool_input.command`. Si l''analyse échoue, le hook se termine immédiatement et Claude Code utilise la commande originale (conception fail-open).',
    'Lê o objeto JSON completo do stdin. Extrai `tool_input.command`. Se a análise falhar, o hook sai imediatamente e o Claude Code usa o comando original (design fail-open).',
    'stdinから完全なJSONオブジェクトを読み取ります。`tool_input.command` を抽出します。パースに失敗した場合、フックは即座に終了し、Claude Codeは元のコマンドを使用します（フェイルオープン設計）。',
    'Đọc toàn bộ đối tượng JSON từ stdin. Trích xuất `tool_input.command`. Nếu phân tích thất bại, hook thoát ngay lập tức và Claude Code sử dụng lệnh gốc (thiết kế fail-open).',
    'Leest het volledige JSON-object van stdin. Extraheert `tool_input.command`. Als het parsen mislukt, stopt de hook onmiddellijk en gebruikt Claude Code het oorspronkelijke commando (fail-open ontwerp).',
    'Beolvassa a teljes JSON objektumot stdin-ről. Kinyeri a `tool_input.command` értéket. Ha az elemzés sikertelen, a hook azonnal kilép, és a Claude Code az eredeti parancsot használja (fail-open tervezés).',
    'يقرأ كائن JSON الكامل من stdin. يستخرج `tool_input.command`. إذا فشل التحليل، يخرج الخطاف فورًا ويستخدم Claude Code الأمر الأصلي (تصميم fail-open).',
    'شیء JSON کامل را از stdin می‌خواند. `tool_input.command` را استخراج می‌کند. اگر تجزیه شکست بخورد، هوک فوراً خارج می‌شود و Claude Code از دستور اصلی استفاده می‌کند (طراحی fail-open).',
    'Stdin''den tam JSON nesnesini okur. `tool_input.command` değerini çıkarır. Ayrıştırma başarısız olursa, hook hemen çıkar ve Claude Code orijinal komutu kullanır (fail-open tasarım).',
    'stdin에서 전체 JSON 객체를 읽습니다. `tool_input.command`를 추출합니다. 파싱에 실패하면 훅이 즉시 종료되고 Claude Code는 원래 명령을 사용합니다(fail-open 설계).',
    'อ่านอ็อบเจกต์ JSON ทั้งหมดจาก stdin ดึงค่า `tool_input.command` หากการแยกวิเคราะห์ล้มเหลว hook จะออกทันทีและ Claude Code จะใช้คำสั่งเดิม (การออกแบบ fail-open)',
    'stdin မှ JSON object အပြည့်အစုံကို ဖတ်သည်။ `tool_input.command` ကို ထုတ်ယူသည်။ parsing မအောင်မြင်ပါက hook ချက်ချင်းထွက်ပြီး Claude Code သည် မူရင်း command ကို အသုံးပြုသည် (fail-open ဒီဇိုင်း)။',
    'stdin-ээс бүтэн JSON объектыг уншина. `tool_input.command`-ыг ялгаж авна. Задлал амжилтгүй болвол hook шууд гарч, Claude Code анхны командыг ашиглана (fail-open загвар).',
    '',
    'Odczytuje pełny obiekt JSON ze stdin. Wyodrębnia `tool_input.command`. Jeśli parsowanie się nie powiedzie, hook natychmiast się kończy i Claude Code używa oryginalnego polecenia (projekt fail-open).');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage2_title',
    'Stage 2: Skill Matching',
    'Etapa 2: Coincidencia de habilidades',
    'Stufe 2: Skill-Matching',
    '阶段2：技能匹配',
    'Étape 2 : Correspondance des compétences',
    'Estágio 2: Correspondência de habilidades',
    'ステージ2：スキルマッチング',
    'Giai đoạn 2: Khớp kỹ năng',
    'Stap 2: Skill Matching',
    '2. szakasz: Skill illesztés',
    'المرحلة 2: مطابقة المهارات',
    'مرحله ۲: تطبیق مهارت‌ها',
    'Aşama 2: Beceri Eşleştirme',
    '단계 2: 스킬 매칭',
    'ขั้นตอนที่ 2: การจับคู่ Skill',
    'အဆင့် 2: Skill တိုက်ဆိုင်ခြင်း',
    'Үе шат 2: Skill тааруулалт',
    '',
    'Etap 2: Dopasowanie umiejętności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage2_body',
    'Queries the SQLite heuristics database for skills whose trigger pattern matches the command. Skills are checked in priority order. Both built-in TOML skills and mined skills are evaluated.',
    'Consulta la base de datos heurística SQLite para habilidades cuyo patrón de activación coincida con el comando. Las habilidades se verifican en orden de prioridad. Se evalúan tanto las habilidades TOML integradas como las minadas.',
    'Fragt die SQLite-Heuristik-Datenbank nach Skills ab, deren Trigger-Muster zum Befehl passt. Skills werden in Prioritätsreihenfolge geprüft. Sowohl eingebaute TOML-Skills als auch geminte Skills werden ausgewertet.',
    '查询SQLite启发式数据库，寻找触发模式与命令匹配的技能。技能按优先级顺序检查。内置TOML技能和挖掘的技能都会被评估。',
    'Interroge la base de données heuristique SQLite pour les compétences dont le modèle de déclenchement correspond à la commande. Les compétences sont vérifiées par ordre de priorité. Les compétences TOML intégrées et les compétences extraites sont évaluées.',
    'Consulta o banco de dados heurístico SQLite para habilidades cujo padrão de gatilho corresponda ao comando. As habilidades são verificadas em ordem de prioridade. Tanto habilidades TOML integradas quanto mineradas são avaliadas.',
    'SQLiteヒューリスティクスデータベースに、トリガーパターンがコマンドに一致するスキルを問い合わせます。スキルは優先度順にチェックされます。組み込みTOMLスキルとマイニングされたスキルの両方が評価されます。',
    'Truy vấn cơ sở dữ liệu heuristic SQLite để tìm các kỹ năng có mẫu kích hoạt khớp với lệnh. Các kỹ năng được kiểm tra theo thứ tự ưu tiên. Cả kỹ năng TOML tích hợp và kỹ năng đã khai thác đều được đánh giá.',
    'Bevraagt de SQLite heuristics-database voor skills waarvan het triggerpatroon overeenkomt met het commando. Skills worden in prioriteitsvolgorde gecontroleerd. Zowel ingebouwde TOML-skills als geminde skills worden geëvalueerd.',
    'Lekérdezi az SQLite heurisztikus adatbázisból azokat a skilleket, amelyek trigger mintája illeszkedik a parancsra. A skillek prioritás szerint kerülnek ellenőrzésre. Mind a beépített TOML skillek, mind a bányászott skillek kiértékelésre kerülnek.',
    'يستعلم قاعدة بيانات SQLite الاستدلالية عن المهارات التي يتطابق نمط تشغيلها مع الأمر. يتم التحقق من المهارات بترتيب الأولوية. يتم تقييم مهارات TOML المدمجة والمهارات المستخرجة.',
    'پایگاه داده اکتشافی SQLite را برای مهارت‌هایی که الگوی فعال‌سازی آنها با دستور مطابقت دارد جستجو می‌کند. مهارت‌ها به ترتیب اولویت بررسی می‌شوند.',
    'Komutun tetikleme deseniyle eşleşen beceriler için SQLite buluşsal veritabanını sorgular. Beceriler öncelik sırasına göre kontrol edilir. Hem yerleşik TOML becerileri hem de çıkarılmış beceriler değerlendirilir.',
    'SQLite 휴리스틱 데이터베이스에서 트리거 패턴이 명령과 일치하는 스킬을 쿼리합니다. 스킬은 우선순위 순서로 확인됩니다. 내장 TOML 스킬과 마이닝된 스킬 모두 평가됩니다.',
    'สอบถามฐานข้อมูล heuristic ของ SQLite เพื่อหา skill ที่มีรูปแบบทริกเกอร์ตรงกับคำสั่ง ตรวจสอบ skill ตามลำดับความสำคัญ ทั้ง skill TOML ในตัวและ skill ที่ขุดได้จะถูกประเมิน',
    'trigger pattern နှင့် command ကိုက်ညီသော skill များအတွက် SQLite heuristics database ကို query လုပ်သည်။ Skill များကို ဦးစားပေးအစီအစဥ်အတိုင်း စစ်ဆေးသည်။',
    'Команд дээр trigger хэв маяг таарах skill-үүдийг SQLite heuristics мэдээллийн сангаас хайна. Skill-үүдийг эрэмбээр шалгана.',
    '',
    'Odpytuje bazę heurystyk SQLite o umiejętności, których wzorzec wyzwalania pasuje do polecenia. Umiejętności sprawdzane są w kolejności priorytetów. Oceniane są zarówno wbudowane umiejętności TOML, jak i wydobyte.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage3_title',
    'Stage 3: Directory Correction',
    'Etapa 3: Corrección de directorio',
    'Stufe 3: Verzeichniskorrektur',
    '阶段3：目录修正',
    'Étape 3 : Correction de répertoire',
    'Estágio 3: Correção de diretório',
    'ステージ3：ディレクトリ修正',
    'Giai đoạn 3: Sửa thư mục',
    'Stap 3: Directory Correctie',
    '3. szakasz: Könyvtárjavítás',
    'المرحلة 3: تصحيح الدليل',
    'مرحله ۳: اصلاح دایرکتوری',
    'Aşama 3: Dizin Düzeltme',
    '단계 3: 디렉토리 수정',
    'ขั้นตอนที่ 3: การแก้ไขไดเรกทอรี',
    'အဆင့် 3: Directory ပြင်ဆင်ခြင်း',
    'Үе шат 3: Хавтас засвар',
    '',
    'Etap 3: Korekta katalogu');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage3_body',
    'For build commands (`cargo`, `go`, `make`, `npm`, `python`, etc.), checks whether the expected project file exists in the current directory. If not, scans nearby directories for the closest match and prepends `cd <dir> &&`.',
    'Para comandos de compilación (`cargo`, `go`, `make`, `npm`, `python`, etc.), verifica si el archivo de proyecto esperado existe en el directorio actual. Si no, escanea directorios cercanos buscando la coincidencia más cercana y antepone `cd <dir> &&`.',
    'Prüft bei Build-Befehlen (`cargo`, `go`, `make`, `npm`, `python` usw.), ob die erwartete Projektdatei im aktuellen Verzeichnis existiert. Falls nicht, durchsucht es benachbarte Verzeichnisse nach der nächstgelegenen Übereinstimmung und stellt `cd <dir> &&` voran.',
    '对于构建命令（`cargo`、`go`、`make`、`npm`、`python` 等），检查预期的项目文件是否存在于当前目录中。如果不存在，扫描附近目录寻找最近匹配并添加 `cd <dir> &&` 前缀。',
    'Pour les commandes de build (`cargo`, `go`, `make`, `npm`, `python`, etc.), vérifie si le fichier projet attendu existe dans le répertoire actuel. Sinon, analyse les répertoires voisins pour trouver la correspondance la plus proche et ajoute `cd <dir> &&` en préfixe.',
    'Para comandos de build (`cargo`, `go`, `make`, `npm`, `python`, etc.), verifica se o arquivo de projeto esperado existe no diretório atual. Se não, escaneia diretórios próximos para a correspondência mais próxima e adiciona `cd <dir> &&` no início.',
    'ビルドコマンド（`cargo`、`go`、`make`、`npm`、`python` など）に対して、期待されるプロジェクトファイルが現在のディレクトリに存在するかチェックします。存在しない場合、近くのディレクトリをスキャンして最も近い一致を見つけ、`cd <dir> &&` を先頭に追加します。',
    'Đối với các lệnh build (`cargo`, `go`, `make`, `npm`, `python`, v.v.), kiểm tra xem tệp dự án mong đợi có tồn tại trong thư mục hiện tại không. Nếu không, quét các thư mục lân cận để tìm kết quả khớp gần nhất và thêm `cd <dir> &&` vào đầu.',
    'Voor build-commando''s (`cargo`, `go`, `make`, `npm`, `python`, enz.) controleert of het verwachte projectbestand bestaat in de huidige map. Zo niet, scant nabijgelegen mappen voor de dichtstbijzijnde match en voegt `cd <dir> &&` toe aan het begin.',
    'Build parancsok (`cargo`, `go`, `make`, `npm`, `python` stb.) esetén ellenőrzi, hogy a várt projektfájl létezik-e az aktuális könyvtárban. Ha nem, a közeli könyvtárakat átvizsgálja a legközelebbi egyezésért és `cd <dir> &&` előtagot ad hozzá.',
    'لأوامر البناء (`cargo`، `go`، `make`، `npm`، `python`، إلخ)، يتحقق مما إذا كان ملف المشروع المتوقع موجودًا في الدليل الحالي. إذا لم يكن كذلك، يفحص الدلائل القريبة للعثور على أقرب تطابق ويضيف `cd <dir> &&` في البداية.',
    'برای دستورات ساخت (`cargo`، `go`، `make`، `npm`، `python` و غیره)، بررسی می‌کند که آیا فایل پروژه مورد انتظار در دایرکتوری فعلی وجود دارد. اگر نه، دایرکتوری‌های نزدیک را برای نزدیک‌ترین تطابق اسکن و `cd <dir> &&` را در ابتدا اضافه می‌کند.',
    'Build komutları (`cargo`, `go`, `make`, `npm`, `python` vb.) için beklenen proje dosyasının geçerli dizinde olup olmadığını kontrol eder. Yoksa, en yakın eşleşme için yakın dizinleri tarar ve başına `cd <dir> &&` ekler.',
    '빌드 명령(`cargo`, `go`, `make`, `npm`, `python` 등)에 대해 예상 프로젝트 파일이 현재 디렉토리에 있는지 확인합니다. 없으면 인근 디렉토리를 스캔하여 가장 가까운 일치를 찾고 `cd <dir> &&`를 앞에 추가합니다.',
    'สำหรับคำสั่ง build (`cargo`, `go`, `make`, `npm`, `python` ฯลฯ) ตรวจสอบว่าไฟล์โปรเจกต์ที่คาดหวังมีอยู่ในไดเรกทอรีปัจจุบันหรือไม่ หากไม่มี จะสแกนไดเรกทอรีใกล้เคียงเพื่อหาผลลัพธ์ที่ตรงที่สุดและเติม `cd <dir> &&` ข้างหน้า',
    'Build command များ (`cargo`, `go`, `make`, `npm`, `python` စသည်) အတွက် လက်ရှိ directory တွင် မျှော်လင့်ထားသော project file ရှိမရှိ စစ်ဆေးသည်။ မရှိပါက အနီးအနား directory များကို scan ပြီး `cd <dir> &&` ကို ရှေ့တွင် ထည့်သည်။',
    'Build командуудын хувьд (`cargo`, `go`, `make`, `npm`, `python` гэх мэт) одоогийн хавтаст хүлээгдэж буй төслийн файл байгаа эсэхийг шалгана. Байхгүй бол ойролцоох хавтсуудаас хамгийн ойр тааралтыг хайж `cd <dir> &&` нэмнэ.',
    '',
    'Dla poleceń budowania (`cargo`, `go`, `make`, `npm`, `python` itd.) sprawdza, czy oczekiwany plik projektu istnieje w bieżącym katalogu. Jeśli nie, skanuje pobliskie katalogi w poszukiwaniu najbliższego dopasowania i dodaje `cd <dir> &&` na początku.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage3_cache_note',
    'The directory scan uses a cached filesystem index with a 5-second TTL to stay fast.',
    'El escaneo de directorios usa un índice de sistema de archivos en caché con un TTL de 5 segundos para mantenerse rápido.',
    'Der Verzeichnisscan verwendet einen zwischengespeicherten Dateisystemindex mit 5 Sekunden TTL für hohe Geschwindigkeit.',
    '目录扫描使用缓存的文件系统索引，TTL为5秒，以保持高速。',
    'L''analyse de répertoire utilise un index de système de fichiers en cache avec un TTL de 5 secondes pour rester rapide.',
    'A varredura de diretório usa um índice de sistema de arquivos em cache com TTL de 5 segundos para manter a velocidade.',
    'ディレクトリスキャンは5秒のTTLを持つキャッシュされたファイルシステムインデックスを使用して高速を維持します。',
    'Quá trình quét thư mục sử dụng chỉ mục hệ thống tệp được lưu trong bộ nhớ đệm với TTL 5 giây để duy trì tốc độ.',
    'De directoryscan gebruikt een gecachte bestandssysteemindex met een 5 seconden TTL om snel te blijven.',
    'A könyvtárvizsgálat gyorsítótárazott fájlrendszer-indexet használ 5 másodperces TTL-lel a gyorsaság érdekében.',
    'يستخدم مسح الدليل فهرس نظام ملفات مخزنًا مؤقتًا مع TTL مدته 5 ثوانٍ للحفاظ على السرعة.',
    'اسکن دایرکتوری از یک شاخص سیستم فایل کش شده با TTL پنج ثانیه‌ای برای حفظ سرعت استفاده می‌کند.',
    'Dizin taraması, hızlı kalmak için 5 saniyelik TTL''ye sahip önbelleğe alınmış bir dosya sistemi dizini kullanır.',
    '디렉토리 스캔은 5초 TTL을 가진 캐시된 파일 시스템 인덱스를 사용하여 빠른 속도를 유지합니다.',
    'การสแกนไดเรกทอรีใช้ดัชนีระบบไฟล์ที่แคชไว้โดยมี TTL 5 วินาทีเพื่อรักษาความเร็ว',
    'Directory scan သည် မြန်ဆန်မှုကို ထိန်းသိမ်းရန် 5 စက္ကန့် TTL ပါသော cached filesystem index ကို အသုံးပြုသည်။',
    'Хавтас сканнер нь хурдыг хадгалахын тулд 5 секундын TTL-тэй кэшлэгдсэн файлын системийн индекс ашигладаг.',
    '',
    'Skanowanie katalogów wykorzystuje buforowany indeks systemu plików z TTL wynoszącym 5 sekund, aby zachować szybkość.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage4_title',
    'Stage 4: GDB Check',
    'Etapa 4: Verificación GDB',
    'Stufe 4: GDB-Prüfung',
    '阶段4：GDB检查',
    'Étape 4 : Vérification GDB',
    'Estágio 4: Verificação GDB',
    'ステージ4：GDBチェック',
    'Giai đoạn 4: Kiểm tra GDB',
    'Stap 4: GDB Controle',
    '4. szakasz: GDB ellenőrzés',
    'المرحلة 4: فحص GDB',
    'مرحله ۴: بررسی GDB',
    'Aşama 4: GDB Kontrolü',
    '단계 4: GDB 확인',
    'ขั้นตอนที่ 4: ตรวจสอบ GDB',
    'အဆင့် 4: GDB စစ်ဆေးခြင်း',
    'Үе шат 4: GDB шалгалт',
    '',
    'Etap 4: Sprawdzenie GDB');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage4_body',
    'If the command is likely to produce a crash (e.g., running a debug binary), PRECC can suggest or inject GDB wrappers to capture structured debug output instead of raw crash logs.',
    'Si el comando probablemente producirá un fallo (p. ej., ejecutar un binario de depuración), PRECC puede sugerir o inyectar envoltorios GDB para capturar salida de depuración estructurada en lugar de registros de fallos sin procesar.',
    'Wenn der Befehl wahrscheinlich einen Absturz verursacht (z.B. Ausführen einer Debug-Binary), kann PRECC GDB-Wrapper vorschlagen oder injizieren, um strukturierte Debug-Ausgaben statt roher Absturz-Logs zu erfassen.',
    '如果命令可能产生崩溃（例如运行调试二进制文件），PRECC可以建议或注入GDB包装器来捕获结构化的调试输出，而不是原始崩溃日志。',
    'Si la commande est susceptible de produire un crash (ex. exécution d''un binaire de débogage), PRECC peut suggérer ou injecter des wrappers GDB pour capturer une sortie de débogage structurée au lieu de logs de crash bruts.',
    'Se o comando provavelmente produzirá um crash (ex., executar um binário de depuração), o PRECC pode sugerir ou injetar wrappers GDB para capturar saída de depuração estruturada em vez de logs de crash brutos.',
    'コマンドがクラッシュを引き起こす可能性がある場合（例：デバッグバイナリの実行）、PRECCはGDBラッパーを提案または注入して、生のクラッシュログの代わりに構造化されたデバッグ出力をキャプチャできます。',
    'Nếu lệnh có khả năng gây ra sự cố (ví dụ: chạy binary debug), PRECC có thể đề xuất hoặc chèn các wrapper GDB để thu thập đầu ra debug có cấu trúc thay vì log crash thô.',
    'Als het commando waarschijnlijk een crash veroorzaakt (bijv. het uitvoeren van een debug binary), kan PRECC GDB-wrappers voorstellen of injecteren om gestructureerde debug-uitvoer vast te leggen in plaats van ruwe crash-logs.',
    'Ha a parancs valószínűleg összeomlást okoz (pl. debug bináris futtatása), a PRECC GDB-wrappereket javasolhat vagy injektálhat strukturált debug kimenet rögzítéséhez a nyers összeomlás-naplók helyett.',
    'إذا كان من المحتمل أن ينتج الأمر عطلًا (مثل تشغيل ملف ثنائي للتصحيح)، يمكن لـ PRECC اقتراح أو حقن أغلفة GDB لالتقاط مخرجات تصحيح منظمة بدلاً من سجلات الأعطال الخام.',
    'اگر احتمال دارد دستور باعث خرابی شود (مثلاً اجرای باینری debug)، PRECC می‌تواند wrapper‌های GDB را پیشنهاد یا تزریق کند تا خروجی debug ساختاریافته به جای لاگ‌های خرابی خام ثبت شود.',
    'Komutun bir çökme üretmesi muhtemelse (ör. debug binary çalıştırma), PRECC ham çökme günlükleri yerine yapılandırılmış debug çıktısı yakalamak için GDB sarmalayıcıları önerebilir veya enjekte edebilir.',
    '명령이 크래시를 일으킬 가능성이 있는 경우(예: 디버그 바이너리 실행), PRECC는 원시 크래시 로그 대신 구조화된 디버그 출력을 캡처하기 위해 GDB 래퍼를 제안하거나 주입할 수 있습니다.',
    'หากคำสั่งมีแนวโน้มที่จะทำให้เกิด crash (เช่น รัน debug binary) PRECC สามารถแนะนำหรือแทรก GDB wrapper เพื่อจับเอาต์พุต debug แบบมีโครงสร้างแทน crash log ดิบ',
    'Command သည် crash ဖြစ်နိုင်ခြေရှိပါက (ဥပမာ debug binary run ခြင်း)၊ PRECC သည် raw crash log များအစား structured debug output ကို ဖမ်းယူရန် GDB wrapper များကို အကြံပြုခြင်း သို့မဟုတ် ထည့်သွင်းနိုင်သည်။',
    'Хэрэв команд нь гэмтэл үүсгэх магадлалтай бол (жишээ нь debug binary ажиллуулах), PRECC нь бүдүүлэг гэмтлийн бүртгэлийн оронд бүтэцлэгдсэн debug гаралтыг авахын тулд GDB wrapper санал болгож болно.',
    '',
    'Jeśli polecenie prawdopodobnie spowoduje awarię (np. uruchomienie binarki debug), PRECC może zasugerować lub wstrzyknąć wrappery GDB, aby przechwycić ustrukturyzowane dane debugowania zamiast surowych logów awarii.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage5_title',
    'Stage 5: RTK Rewriting',
    'Etapa 5: Reescritura RTK',
    'Stufe 5: RTK-Umschreibung',
    '阶段5：RTK重写',
    'Étape 5 : Réécriture RTK',
    'Estágio 5: Reescrita RTK',
    'ステージ5：RTK書き換え',
    'Giai đoạn 5: Viết lại RTK',
    'Stap 5: RTK Herschrijving',
    '5. szakasz: RTK átírás',
    'المرحلة 5: إعادة كتابة RTK',
    'مرحله ۵: بازنویسی RTK',
    'Aşama 5: RTK Yeniden Yazma',
    '단계 5: RTK 재작성',
    'ขั้นตอนที่ 5: การเขียนใหม่ RTK',
    'အဆင့် 5: RTK ပြန်လည်ရေးသားခြင်း',
    'Үе шат 5: RTK дахин бичих',
    '',
    'Etap 5: Przepisywanie RTK');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage5_body',
    'Applies RTK (Rewrite Toolkit) rules that shorten verbose commands, suppress noisy output, or restructure commands for token efficiency.',
    'Aplica reglas RTK (Rewrite Toolkit) que acortan comandos verbosos, suprimen salida ruidosa o reestructuran comandos para eficiencia de tokens.',
    'Wendet RTK-Regeln (Rewrite Toolkit) an, die ausführliche Befehle kürzen, verrauschte Ausgaben unterdrücken oder Befehle für Token-Effizienz umstrukturieren.',
    '应用RTK（重写工具包）规则，缩短冗长命令、抑制嘈杂输出或重构命令以提高token效率。',
    'Applique les règles RTK (Rewrite Toolkit) qui raccourcissent les commandes verbeuses, suppriment les sorties bruyantes ou restructurent les commandes pour l''efficacité des tokens.',
    'Aplica regras RTK (Rewrite Toolkit) que encurtam comandos verbosos, suprimem saída ruidosa ou reestruturam comandos para eficiência de tokens.',
    'RTK（Rewrite Toolkit）ルールを適用して、冗長なコマンドを短縮し、ノイズの多い出力を抑制し、トークン効率のためにコマンドを再構成します。',
    'Áp dụng các quy tắc RTK (Rewrite Toolkit) để rút ngắn lệnh dài dòng, loại bỏ đầu ra nhiễu hoặc tái cấu trúc lệnh để tiết kiệm token.',
    'Past RTK (Rewrite Toolkit) regels toe die uitgebreide commando''s verkorten, ruis in uitvoer onderdrukken of commando''s herstructureren voor token-efficiëntie.',
    'RTK (Rewrite Toolkit) szabályokat alkalmaz, amelyek rövidítik a bőbeszédű parancsokat, elnyomják a zajos kimenetet, vagy átstrukturálják a parancsokat a token-hatékonyság érdekében.',
    'يطبق قواعد RTK (مجموعة أدوات إعادة الكتابة) التي تختصر الأوامر المطولة وتقمع المخرجات المزعجة أو تعيد هيكلة الأوامر لكفاءة الرموز.',
    'قوانین RTK (جعبه ابزار بازنویسی) را اعمال می‌کند که دستورات طولانی را کوتاه، خروجی‌های پر سر و صدا را سرکوب یا دستورات را برای بهره‌وری توکن بازسازی می‌کند.',
    'Ayrıntılı komutları kısaltan, gürültülü çıktıyı bastıran veya token verimliliği için komutları yeniden yapılandıran RTK (Rewrite Toolkit) kurallarını uygular.',
    '장황한 명령을 단축하고, 노이즈가 많은 출력을 억제하거나, 토큰 효율성을 위해 명령을 재구성하는 RTK(Rewrite Toolkit) 규칙을 적용합니다.',
    'ใช้กฎ RTK (Rewrite Toolkit) ที่ย่อคำสั่งที่ยาว ระงับเอาต์พุตที่มีเสียงรบกวน หรือปรับโครงสร้างคำสั่งเพื่อประสิทธิภาพของ token',
    'RTK (Rewrite Toolkit) စည်းမျဉ်းများကို အသုံးပြုပြီး verbose command များကို အတိုချုံ့ခြင်း၊ noisy output ကို ဖိနှိပ်ခြင်း သို့မဟုတ် token efficiency အတွက် command များကို ပြန်လည်ဖွဲ့စည်းခြင်း ပြုလုပ်သည်။',
    'Урт командуудыг богиносгох, шуугиантай гаралтыг дарах, эсвэл токен үр ашгийн тулд командуудыг дахин бүтэцлэх RTK (Rewrite Toolkit) дүрмүүдийг хэрэглэнэ.',
    '',
    'Stosuje reguły RTK (Rewrite Toolkit), które skracają rozwlekłe polecenia, tłumią hałaśliwe wyjście lub restrukturyzują polecenia dla wydajności tokenów.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage6_title',
    'Stage 6: Emit JSON',
    'Etapa 6: Emitir JSON',
    'Stufe 6: JSON ausgeben',
    '阶段6：输出JSON',
    'Étape 6 : Émettre le JSON',
    'Estágio 6: Emitir JSON',
    'ステージ6：JSON出力',
    'Giai đoạn 6: Phát JSON',
    'Stap 6: JSON Uitvoer',
    '6. szakasz: JSON kibocsátás',
    'المرحلة 6: إصدار JSON',
    'مرحله ۶: ارسال JSON',
    'Aşama 6: JSON Çıktısı',
    '단계 6: JSON 출력',
    'ขั้นตอนที่ 6: ส่งออก JSON',
    'အဆင့် 6: JSON ထုတ်လွှတ်ခြင်း',
    'Үе шат 6: JSON гаргах',
    '',
    'Etap 6: Emisja JSON');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_stage6_body',
    'Serializes the modified command back to JSON and writes it to stdout. If no changes were made, the output signals Claude Code to use the original command.',
    'Serializa el comando modificado de vuelta a JSON y lo escribe en stdout. Si no se realizaron cambios, la salida señala a Claude Code que use el comando original.',
    'Serialisiert den geänderten Befehl zurück zu JSON und schreibt ihn auf stdout. Wenn keine Änderungen vorgenommen wurden, signalisiert die Ausgabe Claude Code, den ursprünglichen Befehl zu verwenden.',
    '将修改后的命令序列化回JSON并写入stdout。如果没有更改，输出信号Claude Code使用原始命令。',
    'Sérialise la commande modifiée en JSON et l''écrit sur stdout. Si aucun changement n''a été effectué, la sortie signale à Claude Code d''utiliser la commande originale.',
    'Serializa o comando modificado de volta para JSON e escreve no stdout. Se nenhuma alteração foi feita, a saída sinaliza ao Claude Code para usar o comando original.',
    '変更されたコマンドをJSONにシリアライズしてstdoutに書き込みます。変更がなかった場合、出力はClaude Codeに元のコマンドを使用するよう信号を送ります。',
    'Tuần tự hóa lệnh đã sửa đổi thành JSON và ghi ra stdout. Nếu không có thay đổi, đầu ra báo hiệu cho Claude Code sử dụng lệnh gốc.',
    'Serialiseert het gewijzigde commando terug naar JSON en schrijft het naar stdout. Als er geen wijzigingen zijn aangebracht, signaleert de uitvoer Claude Code om het oorspronkelijke commando te gebruiken.',
    'A módosított parancsot JSON-be sorosítja és stdout-ra írja. Ha nem történt változás, a kimenet jelzi a Claude Code-nak, hogy az eredeti parancsot használja.',
    'يُسلسل الأمر المعدل مرة أخرى إلى JSON ويكتبه إلى stdout. إذا لم يتم إجراء تغييرات، تشير المخرجات إلى Claude Code لاستخدام الأمر الأصلي.',
    'دستور تغییریافته را به JSON سریال‌سازی کرده و روی stdout می‌نویسد. اگر تغییری ایجاد نشده باشد، خروجی به Claude Code سیگنال می‌دهد که از دستور اصلی استفاده کند.',
    'Değiştirilen komutu JSON''a geri serileştirir ve stdout''a yazar. Değişiklik yapılmadıysa, çıktı Claude Code''a orijinal komutu kullanmasını bildirir.',
    '수정된 명령을 JSON으로 직렬화하여 stdout에 씁니다. 변경 사항이 없으면 출력은 Claude Code에 원래 명령을 사용하도록 신호를 보냅니다.',
    'ซีเรียลไลซ์คำสั่งที่แก้ไขกลับเป็น JSON และเขียนลง stdout หากไม่มีการเปลี่ยนแปลง เอาต์พุตจะส่งสัญญาณให้ Claude Code ใช้คำสั่งเดิม',
    'ပြင်ဆင်ထားသော command ကို JSON သို့ ပြန်လည် serialize ပြုလုပ်ပြီး stdout သို့ ရေးသည်။ ပြောင်းလဲမှုမရှိပါက output သည် Claude Code ကို မူရင်း command အသုံးပြုရန် အချက်ပြသည်။',
    'Өөрчлөгдсөн командыг JSON руу буцааж цуваачилж stdout руу бичнэ. Өөрчлөлт хийгээгүй бол гаралт нь Claude Code-д анхны командыг ашиглахыг дохионо.',
    '',
    'Serializuje zmodyfikowane polecenie z powrotem do JSON i zapisuje je na stdout. Jeśli nie wprowadzono zmian, wyjście sygnalizuje Claude Code, aby użył oryginalnego polecenia.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_performance_title',
    'Performance',
    'Rendimiento',
    'Leistung',
    '性能',
    'Performance',
    'Desempenho',
    'パフォーマンス',
    'Hiệu suất',
    'Prestaties',
    'Teljesítmény',
    'الأداء',
    'عملکرد',
    'Performans',
    '성능',
    'ประสิทธิภาพ',
    'စွမ်းဆောင်ရည်',
    'Гүйцэтгэл',
    '',
    'Wydajność');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_performance_intro',
    'The entire pipeline completes in under 5 milliseconds (p99). Key optimizations:',
    'Todo el pipeline se completa en menos de 5 milisegundos (p99). Optimizaciones clave:',
    'Die gesamte Pipeline wird in unter 5 Millisekunden (p99) abgeschlossen. Wichtige Optimierungen:',
    '整个管道在5毫秒（p99）内完成。关键优化：',
    'L''ensemble du pipeline s''exécute en moins de 5 millisecondes (p99). Optimisations clés :',
    'Todo o pipeline é concluído em menos de 5 milissegundos (p99). Otimizações principais:',
    'パイプライン全体が5ミリ秒（p99）以内に完了します。主な最適化：',
    'Toàn bộ pipeline hoàn thành trong dưới 5 mili giây (p99). Các tối ưu hóa chính:',
    'De volledige pipeline wordt voltooid in minder dan 5 milliseconden (p99). Belangrijke optimalisaties:',
    'A teljes pipeline 5 milliszekundum (p99) alatt fejeződik be. Főbb optimalizációk:',
    'يكتمل الأنبوب بأكمله في أقل من 5 ميلي ثانية (p99). التحسينات الرئيسية:',
    'کل خط لوله در کمتر از ۵ میلی‌ثانیه (p99) تکمیل می‌شود. بهینه‌سازی‌های کلیدی:',
    'Tüm pipeline 5 milisaniyenin altında (p99) tamamlanır. Temel optimizasyonlar:',
    '전체 파이프라인이 5밀리초(p99) 이내에 완료됩니다. 주요 최적화:',
    'ไปป์ไลน์ทั้งหมดเสร็จสิ้นภายใน 5 มิลลิวินาที (p99) การเพิ่มประสิทธิภาพหลัก:',
    'Pipeline တစ်ခုလုံးသည် 5 millisecond (p99) အတွင်း ပြီးမြောက်သည်။ အဓိက optimization များ:',
    'Бүх pipeline 5 миллисекундын дотор (p99) дуусна. Гол оновчлолууд:',
    '',
    'Cały pipeline kończy się w mniej niż 5 milisekund (p99). Kluczowe optymalizacje:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_perf_wal',
    'SQLite in WAL mode for lock-free concurrent reads',
    'SQLite en modo WAL para lecturas concurrentes sin bloqueo',
    'SQLite im WAL-Modus für sperrfreie parallele Lesezugriffe',
    'SQLite使用WAL模式实现无锁并发读取',
    'SQLite en mode WAL pour des lectures concurrentes sans verrou',
    'SQLite em modo WAL para leituras concorrentes sem bloqueio',
    'ロックフリーの並行読み取りのためのSQLite WALモード',
    'SQLite ở chế độ WAL cho đọc đồng thời không khóa',
    'SQLite in WAL-modus voor lockvrije gelijktijdige leesbewerkingen',
    'SQLite WAL módban zárolás nélküli párhuzamos olvasáshoz',
    'SQLite في وضع WAL للقراءات المتزامنة بدون قفل',
    'SQLite در حالت WAL برای خواندن همزمان بدون قفل',
    'Kilitsiz eşzamanlı okumalar için WAL modunda SQLite',
    '잠금 없는 동시 읽기를 위한 WAL 모드의 SQLite',
    'SQLite ในโหมด WAL สำหรับการอ่านพร้อมกันแบบไม่ล็อก',
    'Lock-free concurrent reads အတွက် WAL mode ဖြင့် SQLite',
    'Түгжээгүй зэрэгцээ уншилтын төлөө WAL горимтой SQLite',
    '',
    'SQLite w trybie WAL dla odczytów współbieżnych bez blokad');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_perf_regex',
    'Pre-compiled regex patterns for skill matching',
    'Patrones regex precompilados para coincidencia de habilidades',
    'Vorkompilierte Regex-Muster für Skill-Matching',
    '预编译的正则表达式模式用于技能匹配',
    'Modèles regex précompilés pour la correspondance des compétences',
    'Padrões regex pré-compilados para correspondência de habilidades',
    'スキルマッチングのためのプリコンパイル済み正規表現パターン',
    'Các mẫu regex biên dịch trước để khớp kỹ năng',
    'Voorgecompileerde regex-patronen voor skill matching',
    'Előre fordított regex minták skill illesztéshez',
    'أنماط regex مترجمة مسبقًا لمطابقة المهارات',
    'الگوهای regex از پیش کامپایل شده برای تطبیق مهارت‌ها',
    'Beceri eşleştirme için önceden derlenmiş regex kalıpları',
    '스킬 매칭을 위한 사전 컴파일된 정규식 패턴',
    'รูปแบบ regex ที่คอมไพล์ล่วงหน้าสำหรับการจับคู่ skill',
    'Skill matching အတွက် ကြိုတင် compile ပြုလုပ်ထားသော regex pattern များ',
    'Skill тааруулалтад зориулсан урьдчилан хөрвүүлсэн regex загварууд',
    '',
    'Prekompilowane wzorce regex do dopasowywania umiejętności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_perf_cache',
    'Cached filesystem scans (5-second TTL)',
    'Escaneos de sistema de archivos en caché (TTL de 5 segundos)',
    'Zwischengespeicherte Dateisystem-Scans (5 Sekunden TTL)',
    '缓存的文件系统扫描（5秒TTL）',
    'Scans du système de fichiers en cache (TTL de 5 secondes)',
    'Varreduras de sistema de arquivos em cache (TTL de 5 segundos)',
    'キャッシュされたファイルシステムスキャン（5秒TTL）',
    'Quét hệ thống tệp được lưu trong bộ nhớ đệm (TTL 5 giây)',
    'Gecachte bestandssysteemscans (5 seconden TTL)',
    'Gyorsítótárazott fájlrendszer-vizsgálatok (5 másodperces TTL)',
    'عمليات مسح نظام الملفات المخزنة مؤقتًا (TTL مدته 5 ثوانٍ)',
    'اسکن‌های سیستم فایل کش شده (TTL پنج ثانیه‌ای)',
    'Önbelleğe alınmış dosya sistemi taramaları (5 saniyelik TTL)',
    '캐시된 파일 시스템 스캔(5초 TTL)',
    'การสแกนระบบไฟล์ที่แคชไว้ (TTL 5 วินาที)',
    'Cached filesystem scans (5 စက္ကန့် TTL)',
    'Кэшлэгдсэн файлын системийн сканнер (5 секундын TTL)',
    '',
    'Buforowane skany systemu plików (TTL 5 sekund)');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_perf_no_network',
    'No network calls in the hot path',
    'Sin llamadas de red en la ruta crítica',
    'Keine Netzwerkaufrufe im Hot Path',
    '热路径中无网络调用',
    'Aucun appel réseau dans le chemin critique',
    'Nenhuma chamada de rede no caminho quente',
    'ホットパスにネットワーク呼び出しなし',
    'Không có cuộc gọi mạng trong đường dẫn nóng',
    'Geen netwerkoproepen in het hot path',
    'Nincs hálózati hívás a hot path-ban',
    'لا توجد مكالمات شبكة في المسار الساخن',
    'بدون فراخوانی شبکه در مسیر اصلی',
    'Sıcak yolda ağ çağrısı yok',
    '핫 경로에 네트워크 호출 없음',
    'ไม่มีการเรียกเครือข่ายใน hot path',
    'Hot path တွင် network call များမရှိ',
    'Халуун замд сүлжээний дуудлага байхгүй',
    '',
    'Brak wywołań sieciowych na gorącej ścieżce');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_perf_failopen',
    'Fail-open: any error falls through to the original command',
    'Fail-open: cualquier error pasa al comando original',
    'Fail-Open: Jeder Fehler fällt auf den ursprünglichen Befehl zurück',
    'Fail-open：任何错误都回退到原始命令',
    'Fail-open : toute erreur retombe sur la commande originale',
    'Fail-open: qualquer erro retorna ao comando original',
    'フェイルオープン：エラーが発生しても元のコマンドにフォールスルー',
    'Fail-open: mọi lỗi đều chuyển về lệnh gốc',
    'Fail-open: elke fout valt terug op het oorspronkelijke commando',
    'Fail-open: bármely hiba esetén az eredeti parancs fut le',
    'Fail-open: أي خطأ يعود إلى الأمر الأصلي',
    'Fail-open: هر خطایی به دستور اصلی بازمی‌گردد',
    'Fail-open: herhangi bir hata orijinal komuta geri döner',
    'Fail-open: 모든 오류는 원래 명령으로 넘어감',
    'Fail-open: ข้อผิดพลาดใดๆ จะกลับไปใช้คำสั่งเดิม',
    'Fail-open: error တစ်ခုခုဖြစ်ပါက မူရင်း command သို့ ပြန်သွားသည်',
    'Fail-open: аливаа алдаа нь анхны команд руу шилжинэ',
    '',
    'Fail-open: każdy błąd przechodzi do oryginalnego polecenia');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_testing_title',
    'Testing the Hook Manually',
    'Probar el Hook manualmente',
    'Den Hook manuell testen',
    '手动测试钩子',
    'Tester le Hook manuellement',
    'Testando o Hook manualmente',
    'フックの手動テスト',
    'Kiểm tra Hook thủ công',
    'De Hook handmatig testen',
    'A Hook manuális tesztelése',
    'اختبار الخطاف يدويًا',
    'تست دستی هوک',
    'Hook''u Manuel Test Etme',
    '훅 수동 테스트',
    'ทดสอบ Hook ด้วยตนเอง',
    'Hook ကို လက်ဖြင့် စမ်းသပ်ခြင်း',
    'Hook-ийг гараар шалгах',
    '',
    'Ręczne testowanie Hooka');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('hp_testing_body',
    'You can invoke the hook directly:',
    'Puedes invocar el hook directamente:',
    'Sie können den Hook direkt aufrufen:',
    '你可以直接调用钩子：',
    'Vous pouvez invoquer le hook directement :',
    'Você pode invocar o hook diretamente:',
    'フックを直接呼び出すことができます：',
    'Bạn có thể gọi hook trực tiếp:',
    'U kunt de hook direct aanroepen:',
    'A hookot közvetlenül meghívhatja:',
    'يمكنك استدعاء الخطاف مباشرة:',
    'می‌توانید هوک را مستقیماً فراخوانی کنید:',
    'Hook''u doğrudan çağırabilirsiniz:',
    '훅을 직접 호출할 수 있습니다:',
    'คุณสามารถเรียกใช้ hook โดยตรง:',
    'Hook ကို တိုက်ရိုက် ခေါ်ယူနိုင်သည်:',
    'Hook-ийг шууд дуудаж болно:',
    '',
    'Możesz wywołać hook bezpośrednio:');
