-- Geofence chapter strings
INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_title',
    'Geofence',
    'Geocerca',
    'Geofence',
    '地理围栏',
    'Géorepérage',
    'Geocerca',
    'ジオフェンス',
    'Hàng rào địa lý',
    'Geofence',
    'Geofence',
    'السياج الجغرافي',
    'حصار جغرافیایی',
    'Coğrafi sınır',
    '지오펜스',
    'รั้วภูมิศาสตร์',
    'Geofence',
    'Геофенс',
    '',
    'Geofence');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_intro',
    'PRECC includes IP geofence compliance checking for regulated environments. This is a Pro feature.',
    'PRECC incluye verificación de cumplimiento de geocerca IP para entornos regulados. Esta es una función Pro.',
    'PRECC enthält IP-Geofence-Compliance-Prüfung für regulierte Umgebungen. Dies ist eine Pro-Funktion.',
    'PRECC包含用于受监管环境的IP地理围栏合规性检查。这是Pro功能。',
    'PRECC inclut la vérification de conformité de géorepérage IP pour les environnements réglementés. C''est une fonctionnalité Pro.',
    'PRECC inclui verificação de conformidade de geocerca IP para ambientes regulados. Este é um recurso Pro.',
    'PRECCは規制環境向けのIPジオフェンスコンプライアンスチェックを含みます。これはPro機能です。',
    'PRECC bao gồm kiểm tra tuân thủ hàng rào địa lý IP cho các môi trường được quản lý. Đây là tính năng Pro.',
    'PRECC bevat IP-geofence-nalevingscontrole voor gereguleerde omgevingen. Dit is een Pro-functie.',
    'A PRECC IP geofence megfelelőségi ellenőrzést tartalmaz szabályozott környezetekhez. Ez egy Pro funkció.',
    'يتضمن PRECC فحص الامتثال للسياج الجغرافي IP للبيئات المنظمة. هذه ميزة Pro.',
    'PRECC شامل بررسی انطباق حصار جغرافیایی IP برای محیط‌های تحت نظارت است. این یک ویژگی Pro است.',
    'PRECC, düzenlenmiş ortamlar için IP coğrafi sınır uyumluluk denetimi içerir. Bu bir Pro özelliğidir.',
    'PRECC는 규제 환경을 위한 IP 지오펜스 규정 준수 검사를 포함합니다. Pro 기능입니다.',
    'PRECC รวมการตรวจสอบการปฏิบัติตาม IP geofence สำหรับสภาพแวดล้อมที่มีการควบคุม นี่เป็นฟีเจอร์ Pro',
    'PRECC တွင် ထိန်းချုပ်ထားသော ပတ်ဝန်းကျင်များအတွက် IP geofence လိုက်နာမှု စစ်ဆေးခြင်း ပါဝင်သည်။ ၎င်းသည် Pro အင်္ဂါရပ်ဖြစ်သည်။',
    'PRECC нь зохицуулалттай орчинд зориулсан IP geofence нийцлийн шалгалтыг агуулна. Энэ нь Pro боломж юм.',
    '',
    'PRECC zawiera sprawdzanie zgodności geofence IP dla środowisk regulowanych. To funkcja Pro.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_overview_title',
    'Overview',
    'Descripción general',
    'Überblick',
    '概述',
    'Vue d''ensemble',
    'Visão geral',
    '概要',
    'Tổng quan',
    'Overzicht',
    'Áttekintés',
    'نظرة عامة',
    'مرور کلی',
    'Genel bakış',
    '개요',
    'ภาพรวม',
    'ခြုံငုံသုံးသပ်ချက်',
    'Тойм',
    '',
    'Przegląd');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_overview_body',
    'Some organizations require that development tools only operate within approved geographic regions. PRECC''s geofence feature verifies that the current machine''s IP address falls within an allowed region list.',
    'Algunas organizaciones requieren que las herramientas de desarrollo solo operen dentro de regiones geográficas aprobadas. La función de geocerca de PRECC verifica que la dirección IP de la máquina actual esté dentro de una lista de regiones permitidas.',
    'Einige Organisationen verlangen, dass Entwicklungswerkzeuge nur innerhalb genehmigter geografischer Regionen betrieben werden. Die Geofence-Funktion von PRECC überprüft, ob die IP-Adresse des aktuellen Rechners in einer Liste erlaubter Regionen liegt.',
    '一些组织要求开发工具仅在批准的地理区域内运行。PRECC的地理围栏功能验证当前机器的IP地址是否在允许的区域列表中。',
    'Certaines organisations exigent que les outils de développement ne fonctionnent que dans des régions géographiques approuvées. La fonctionnalité de géorepérage de PRECC vérifie que l''adresse IP de la machine actuelle se trouve dans une liste de régions autorisées.',
    'Algumas organizações exigem que ferramentas de desenvolvimento operem apenas dentro de regiões geográficas aprovadas. O recurso de geocerca do PRECC verifica se o endereço IP da máquina atual está dentro de uma lista de regiões permitidas.',
    '一部の組織は、開発ツールが承認された地理的リージョン内でのみ動作することを要求しています。PRECCのジオフェンス機能は、現在のマシンのIPアドレスが許可されたリージョンリスト内にあることを検証します。',
    'Một số tổ chức yêu cầu các công cụ phát triển chỉ hoạt động trong các vùng địa lý được phê duyệt. Tính năng hàng rào địa lý của PRECC xác minh rằng địa chỉ IP của máy hiện tại nằm trong danh sách vùng được phép.',
    'Sommige organisaties vereisen dat ontwikkeltools alleen binnen goedgekeurde geografische regio''s werken. De geofence-functie van PRECC verifieert dat het IP-adres van de huidige machine binnen een toegestane regiolijst valt.',
    'Egyes szervezetek megkövetelik, hogy a fejlesztőeszközök csak jóváhagyott földrajzi régiókban működjenek. A PRECC geofence funkciója ellenőrzi, hogy a jelenlegi gép IP-címe az engedélyezett régiók listáján belül van-e.',
    'تتطلب بعض المنظمات أن تعمل أدوات التطوير فقط ضمن مناطق جغرافية معتمدة. تتحقق ميزة السياج الجغرافي في PRECC من أن عنوان IP للجهاز الحالي يقع ضمن قائمة المناطق المسموح بها.',
    'برخی سازمان‌ها نیاز دارند که ابزارهای توسعه فقط در مناطق جغرافیایی تایید شده کار کنند. ویژگی حصار جغرافیایی PRECC تأیید می‌کند که آدرس IP دستگاه فعلی در لیست مناطق مجاز قرار دارد.',
    'Bazı kuruluşlar, geliştirme araçlarının yalnızca onaylı coğrafi bölgelerde çalışmasını gerektirir. PRECC''nin coğrafi sınır özelliği, mevcut makinenin IP adresinin izin verilen bölge listesinde olduğunu doğrular.',
    '일부 조직은 개발 도구가 승인된 지리적 리전 내에서만 작동하도록 요구합니다. PRECC의 지오펜스 기능은 현재 기기의 IP 주소가 허용된 리전 목록 내에 있는지 확인합니다.',
    'บางองค์กรกำหนดให้เครื่องมือพัฒนาทำงานเฉพาะในภูมิภาคที่ได้รับอนุมัติเท่านั้น ฟีเจอร์ geofence ของ PRECC จะตรวจสอบว่าที่อยู่ IP ของเครื่องปัจจุบันอยู่ในรายการภูมิภาคที่อนุญาต',
    'အချို့အဖွဲ့အစည်းများသည် ဖွံ့ဖြိုးရေးကိရိယာများ အတည်ပြုထားသော ပထဝီဝင်ဒေသများအတွင်းသာ အလုပ်လုပ်ရန် လိုအပ်သည်။ PRECC ၏ geofence feature သည် လက်ရှိစက်၏ IP လိပ်စာ ခွင့်ပြုထားသော ဒေသစာရင်းအတွင်း ရှိမရှိ စစ်ဆေးသည်။',
    'Зарим байгууллагууд хөгжүүлэлтийн хэрэгслүүд зөвхөн зөвшөөрөгдсөн газарзүйн бүс нутагт ажиллахыг шаарддаг. PRECC-ийн geofence боломж нь одоогийн машины IP хаяг зөвшөөрөгдсөн бүсийн жагсаалтад байгаа эсэхийг шалгана.',
    '',
    'Niektóre organizacje wymagają, aby narzędzia programistyczne działały tylko w zatwierdzonych regionach geograficznych. Funkcja geofence PRECC sprawdza, czy adres IP bieżącej maszyny znajduje się na liście dozwolonych regionów.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_check_title',
    'Checking Compliance',
    'Verificación de cumplimiento',
    'Compliance-Prüfung',
    '检查合规性',
    'Vérification de la conformité',
    'Verificando conformidade',
    'コンプライアンスチェック',
    'Kiểm tra tuân thủ',
    'Nalevingscontrole',
    'Megfelelőségi ellenőrzés',
    'التحقق من الامتثال',
    'بررسی انطباق',
    'Uyumluluk kontrolü',
    '규정 준수 확인',
    'การตรวจสอบการปฏิบัติตาม',
    'လိုက်နာမှု စစ်ဆေးခြင်း',
    'Нийцлийн шалгалт',
    '',
    'Sprawdzanie zgodności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_check_noncompliant',
    'If the machine is outside the allowed regions:',
    'Si la máquina está fuera de las regiones permitidas:',
    'Wenn sich der Rechner außerhalb der erlaubten Regionen befindet:',
    '如果机器在允许的区域之外：',
    'Si la machine est en dehors des régions autorisées :',
    'Se a máquina estiver fora das regiões permitidas:',
    'マシンが許可されたリージョンの外にある場合：',
    'Nếu máy nằm ngoài các vùng được phép:',
    'Als de machine buiten de toegestane regio''s is:',
    'Ha a gép az engedélyezett régiókon kívül van:',
    'إذا كان الجهاز خارج المناطق المسموح بها:',
    'اگر دستگاه خارج از مناطق مجاز باشد:',
    'Makine izin verilen bölgelerin dışındaysa:',
    '기기가 허용된 리전 외부에 있는 경우:',
    'หากเครื่องอยู่นอกภูมิภาคที่อนุญาต:',
    'စက်သည် ခွင့်ပြုထားသော ဒေသများ ပြင်ပတွင် ရှိပါက:',
    'Хэрэв машин зөвшөөрөгдсөн бүс нутгийн гадна байвал:',
    '',
    'Jeśli maszyna jest poza dozwolonymi regionami:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_refresh_title',
    'Refreshing Geofence Data',
    'Actualización de datos de geocerca',
    'Geofence-Daten aktualisieren',
    '刷新地理围栏数据',
    'Actualisation des données de géorepérage',
    'Atualizando dados de geocerca',
    'ジオフェンスデータの更新',
    'Làm mới dữ liệu hàng rào địa lý',
    'Geofence-gegevens vernieuwen',
    'Geofence adatok frissítése',
    'تحديث بيانات السياج الجغرافي',
    'بروزرسانی داده‌های حصار جغرافیایی',
    'Coğrafi sınır verilerini yenileme',
    '지오펜스 데이터 새로고침',
    'การรีเฟรชข้อมูล geofence',
    'Geofence ဒေတာ ပြန်လည်ရယူခြင်း',
    'Геофенс өгөгдлийг шинэчлэх',
    '',
    'Odświeżanie danych geofence');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_info_title',
    'Viewing Geofence Info',
    'Ver información de geocerca',
    'Geofence-Informationen anzeigen',
    '查看地理围栏信息',
    'Affichage des informations de géorepérage',
    'Visualizando informações de geocerca',
    'ジオフェンス情報の表示',
    'Xem thông tin hàng rào địa lý',
    'Geofence-informatie bekijken',
    'Geofence információk megtekintése',
    'عرض معلومات السياج الجغرافي',
    'مشاهده اطلاعات حصار جغرافیایی',
    'Coğrafi sınır bilgilerini görüntüleme',
    '지오펜스 정보 보기',
    'ดูข้อมูล geofence',
    'Geofence အချက်အလက် ကြည့်ရှုခြင်း',
    'Геофенс мэдээлэл харах',
    '',
    'Wyświetlanie informacji geofence');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_clear_title',
    'Clearing Cache',
    'Borrar caché',
    'Cache leeren',
    '清除缓存',
    'Vider le cache',
    'Limpando cache',
    'キャッシュのクリア',
    'Xóa bộ nhớ đệm',
    'Cache wissen',
    'Gyorsítótár törlése',
    'مسح ذاكرة التخزين المؤقت',
    'پاک کردن حافظه پنهان',
    'Önbelleği temizleme',
    '캐시 지우기',
    'การล้างแคช',
    'Cache ရှင်းလင်းခြင်း',
    'Кэш цэвэрлэх',
    '',
    'Czyszczenie pamięci podręcznej');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_config_title',
    'Configuration',
    'Configuración',
    'Konfiguration',
    '配置',
    'Configuration',
    'Configuração',
    '設定',
    'Cấu hình',
    'Configuratie',
    'Konfiguráció',
    'التكوين',
    'پیکربندی',
    'Yapılandırma',
    '구성',
    'การกำหนดค่า',
    'ပြင်ဆင်သတ်မှတ်ခြင်း',
    'Тохиргоо',
    '',
    'Konfiguracja');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_config_body',
    'The geofence policy is defined in `~/.config/precc/geofence.toml`:',
    'La política de geocerca se define en `~/.config/precc/geofence.toml`:',
    'Die Geofence-Richtlinie wird in `~/.config/precc/geofence.toml` definiert:',
    '地理围栏策略在 `~/.config/precc/geofence.toml` 中定义：',
    'La politique de géorepérage est définie dans `~/.config/precc/geofence.toml` :',
    'A política de geocerca é definida em `~/.config/precc/geofence.toml`:',
    'ジオフェンスポリシーは `~/.config/precc/geofence.toml` で定義されます：',
    'Chính sách hàng rào địa lý được định nghĩa trong `~/.config/precc/geofence.toml`:',
    'Het geofence-beleid wordt gedefinieerd in `~/.config/precc/geofence.toml`:',
    'A geofence-szabályzat a `~/.config/precc/geofence.toml` fájlban van meghatározva:',
    'يتم تعريف سياسة السياج الجغرافي في `~/.config/precc/geofence.toml`:',
    'سیاست حصار جغرافیایی در `~/.config/precc/geofence.toml` تعریف شده است:',
    'Coğrafi sınır politikası `~/.config/precc/geofence.toml` dosyasında tanımlanır:',
    '지오펜스 정책은 `~/.config/precc/geofence.toml`에 정의됩니다:',
    'นโยบาย geofence ถูกกำหนดใน `~/.config/precc/geofence.toml`:',
    'Geofence မူဝါဒကို `~/.config/precc/geofence.toml` တွင် သတ်မှတ်ထားသည်:',
    'Геофенс бодлогыг `~/.config/precc/geofence.toml` файлд тодорхойлно:',
    '',
    'Polityka geofence jest zdefiniowana w `~/.config/precc/geofence.toml`:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('geo_config_block',
    'Set `block_on_violation = true` to prevent PRECC from operating when outside allowed regions.',
    'Establezca `block_on_violation = true` para evitar que PRECC opere cuando esté fuera de las regiones permitidas.',
    'Setzen Sie `block_on_violation = true`, um zu verhindern, dass PRECC außerhalb der erlaubten Regionen arbeitet.',
    '设置 `block_on_violation = true` 以阻止PRECC在允许区域外运行。',
    'Définissez `block_on_violation = true` pour empêcher PRECC de fonctionner en dehors des régions autorisées.',
    'Defina `block_on_violation = true` para impedir que PRECC opere fora das regiões permitidas.',
    '`block_on_violation = true` を設定すると、許可されたリージョン外でPRECCの動作を防止します。',
    'Đặt `block_on_violation = true` để ngăn PRECC hoạt động khi nằm ngoài các vùng được phép.',
    'Stel `block_on_violation = true` in om te voorkomen dat PRECC werkt buiten toegestane regio''s.',
    'Állítsa a `block_on_violation = true` értéket, hogy megakadályozza a PRECC működését az engedélyezett régiókon kívül.',
    'اضبط `block_on_violation = true` لمنع PRECC من العمل عند التواجد خارج المناطق المسموح بها.',
    'مقدار `block_on_violation = true` را تنظیم کنید تا از عملکرد PRECC در خارج از مناطق مجاز جلوگیری شود.',
    'İzin verilen bölgelerin dışındayken PRECC''nin çalışmasını önlemek için `block_on_violation = true` olarak ayarlayın.',
    '허용된 리전 외부에서 PRECC가 작동하지 않도록 `block_on_violation = true`를 설정하세요.',
    'ตั้งค่า `block_on_violation = true` เพื่อป้องกันไม่ให้ PRECC ทำงานเมื่ออยู่นอกภูมิภาคที่อนุญาต',
    'ခွင့်ပြုထားသော ဒေသများ ပြင်ပတွင် PRECC အလုပ်မလုပ်စေရန် `block_on_violation = true` ကို သတ်မှတ်ပါ။',
    'Зөвшөөрөгдсөн бүс нутгийн гадна PRECC ажиллахаас сэргийлэхийн тулд `block_on_violation = true` гэж тохируулна.',
    '',
    'Ustaw `block_on_violation = true`, aby zapobiec działaniu PRECC poza dozwolonymi regionami.');
