-- License chapter strings
INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_title',
    'License',
    'Licencia',
    'Lizenz',
    '许可证',
    'Licence',
    'Licença',
    'ライセンス',
    'Giấy phép',
    'Licentie',
    'Licenc',
    'الترخيص',
    'مجوز',
    'Lisans',
    '라이선스',
    'ใบอนุญาต',
    'လိုင်စင်',
    'Лиценз',
    '',
    'Licencja');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_intro',
    'PRECC offers two tiers: Community (free) and Pro.',
    'PRECC ofrece dos niveles: Community (gratuito) y Pro.',
    'PRECC bietet zwei Stufen: Community (kostenlos) und Pro.',
    'PRECC提供两个层级：Community（免费）和Pro。',
    'PRECC propose deux niveaux : Community (gratuit) et Pro.',
    'PRECC oferece dois níveis: Community (gratuito) e Pro.',
    'PRECCは2つのティアを提供します：Community（無料）とPro。',
    'PRECC cung cấp hai cấp: Community (miễn phí) và Pro.',
    'PRECC biedt twee niveaus: Community (gratis) en Pro.',
    'A PRECC két szintet kínál: Community (ingyenes) és Pro.',
    'يقدم PRECC مستويين: Community (مجاني) و Pro.',
    'PRECC دو سطح ارائه می‌دهد: Community (رایگان) و Pro.',
    'PRECC iki seviye sunar: Community (ücretsiz) ve Pro.',
    'PRECC는 두 가지 티어를 제공합니다: Community(무료)와 Pro.',
    'PRECC เสนอสองระดับ: Community (ฟรี) และ Pro',
    'PRECC သည် အဆင့်နှစ်ခုပေးသည်: Community (အခမဲ့) နှင့် Pro။',
    'PRECC хоёр түвшин санал болгодог: Community (үнэгүй) ба Pro.',
    '',
    'PRECC oferuje dwa poziomy: Community (darmowy) i Pro.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_community_title',
    'Community Tier (Free)',
    'Nivel Community (gratuito)',
    'Community-Stufe (kostenlos)',
    'Community层（免费）',
    'Niveau Community (gratuit)',
    'Nível Community (gratuito)',
    'Communityティア（無料）',
    'Cấp Community (miễn phí)',
    'Community-niveau (gratis)',
    'Community szint (ingyenes)',
    'مستوى Community (مجاني)',
    'سطح Community (رایگان)',
    'Community seviyesi (ücretsiz)',
    'Community 티어 (무료)',
    'ระดับ Community (ฟรี)',
    'Community အဆင့် (အခမဲ့)',
    'Community түвшин (үнэгүй)',
    '',
    'Poziom Community (darmowy)');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_community_includes',
    'The Community tier includes:',
    'El nivel Community incluye:',
    'Die Community-Stufe umfasst:',
    'Community层包括：',
    'Le niveau Community comprend :',
    'O nível Community inclui:',
    'Communityティアには以下が含まれます：',
    'Cấp Community bao gồm:',
    'Het Community-niveau omvat:',
    'A Community szint tartalmazza:',
    'يتضمن مستوى Community:',
    'سطح Community شامل:',
    'Community seviyesi şunları içerir:',
    'Community 티어에는 다음이 포함됩니다:',
    'ระดับ Community ประกอบด้วย:',
    'Community အဆင့်တွင် ပါဝင်သည်:',
    'Community түвшинд багтана:',
    '',
    'Poziom Community obejmuje:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_community_skills',
    'All built-in skills (wrong-directory correction, jj translation, etc.)',
    'Todas las habilidades integradas (corrección de directorio, traducción jj, etc.)',
    'Alle integrierten Skills (Verzeichniskorrektur, jj-Übersetzung usw.)',
    '所有内置技能（错误目录修正、jj翻译等）',
    'Toutes les compétences intégrées (correction de répertoire, traduction jj, etc.)',
    'Todas as habilidades integradas (correção de diretório, tradução jj, etc.)',
    'すべての組み込みスキル（ディレクトリ修正、jj変換など）',
    'Tất cả kỹ năng tích hợp (sửa thư mục sai, dịch jj, v.v.)',
    'Alle ingebouwde vaardigheden (directoryfouten, jj-vertaling, enz.)',
    'Minden beépített képesség (könyvtárjavítás, jj fordítás stb.)',
    'جميع المهارات المدمجة (تصحيح الدليل الخاطئ، ترجمة jj، إلخ)',
    'تمام مهارت‌های داخلی (اصلاح دایرکتوری اشتباه، ترجمه jj و غیره)',
    'Tüm yerleşik beceriler (dizin düzeltme, jj çevirisi vb.)',
    '모든 내장 스킬 (잘못된 디렉토리 수정, jj 변환 등)',
    'ทักษะในตัวทั้งหมด (แก้ไขไดเรกทอรีผิด, แปล jj ฯลฯ)',
    'ပါဝင်သော ကျွမ်းကျင်မှုအားလုံး (directory ပြင်ဆင်ခြင်း၊ jj ဘာသာပြန်ခြင်း စသည်)',
    'Бүх суулгагдсан ур чадвар (директорын засвар, jj орчуулга г.м.)',
    '',
    'Wszystkie wbudowane umiejętności (korekta katalogu, tłumaczenie jj itp.)');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_community_pipeline',
    'Hook pipeline with full Pillar 1 and Pillar 4 support',
    'Pipeline de hooks con soporte completo de Pillar 1 y Pillar 4',
    'Hook-Pipeline mit voller Pillar-1- und Pillar-4-Unterstützung',
    '支持完整Pillar 1和Pillar 4的Hook管道',
    'Pipeline de hooks avec support complet Pillar 1 et Pillar 4',
    'Pipeline de hooks com suporte completo a Pillar 1 e Pillar 4',
    'Pillar 1とPillar 4を完全サポートするフックパイプライン',
    'Pipeline hook với hỗ trợ đầy đủ Pillar 1 và Pillar 4',
    'Hook-pipeline met volledige Pillar 1- en Pillar 4-ondersteuning',
    'Hook pipeline teljes Pillar 1 és Pillar 4 támogatással',
    'خط أنابيب الخطاف مع دعم كامل لـ Pillar 1 و Pillar 4',
    'خط لوله hook با پشتیبانی کامل Pillar 1 و Pillar 4',
    'Tam Pillar 1 ve Pillar 4 desteğiyle hook hattı',
    'Pillar 1 및 Pillar 4를 완전히 지원하는 Hook 파이프라인',
    'ท่อ hook ที่รองรับ Pillar 1 และ Pillar 4 อย่างเต็มที่',
    'Pillar 1 နှင့် Pillar 4 အပြည့်အဝ ထောက်ပံ့သည့် Hook pipeline',
    'Pillar 1, Pillar 4-ийг бүрэн дэмждэг Hook pipeline',
    '',
    'Pipeline hooków z pełnym wsparciem Pillar 1 i Pillar 4');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_community_savings',
    'Basic `precc savings` summary',
    'Resumen básico de `precc savings`',
    'Grundlegende `precc savings`-Zusammenfassung',
    '基本的 `precc savings` 摘要',
    'Résumé de base de `precc savings`',
    'Resumo básico de `precc savings`',
    '基本的な `precc savings` サマリー',
    'Tóm tắt cơ bản `precc savings`',
    'Basis `precc savings` samenvatting',
    'Alapszintű `precc savings` összefoglaló',
    'ملخص أساسي لـ `precc savings`',
    'خلاصه پایه `precc savings`',
    'Temel `precc savings` özeti',
    '기본 `precc savings` 요약',
    'สรุปพื้นฐานของ `precc savings`',
    'အခြေခံ `precc savings` အကျဉ်းချုပ်',
    'Үндсэн `precc savings` товч',
    '',
    'Podstawowe podsumowanie `precc savings`');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_community_mining',
    'Session mining with `precc ingest`',
    'Minería de sesiones con `precc ingest`',
    'Session-Mining mit `precc ingest`',
    '使用 `precc ingest` 进行会话挖掘',
    'Exploration de sessions avec `precc ingest`',
    'Mineração de sessões com `precc ingest`',
    '`precc ingest` によるセッションマイニング',
    'Khai thác phiên với `precc ingest`',
    'Sessiemining met `precc ingest`',
    'Munkamenet-bányászat a `precc ingest` segítségével',
    'تنقيب الجلسات مع `precc ingest`',
    'استخراج جلسه با `precc ingest`',
    '`precc ingest` ile oturum madenciliği',
    '`precc ingest`를 사용한 세션 마이닝',
    'การขุดเซสชันด้วย `precc ingest`',
    '`precc ingest` ဖြင့် session mining',
    '`precc ingest` ашиглан сессийн олборлолт',
    '',
    'Eksploracja sesji za pomocą `precc ingest`');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_community_unlimited',
    'Unlimited local usage',
    'Uso local ilimitado',
    'Unbegrenzte lokale Nutzung',
    '无限本地使用',
    'Utilisation locale illimitée',
    'Uso local ilimitado',
    '無制限のローカル使用',
    'Sử dụng cục bộ không giới hạn',
    'Onbeperkt lokaal gebruik',
    'Korlátlan helyi használat',
    'استخدام محلي غير محدود',
    'استفاده محلی نامحدود',
    'Sınırsız yerel kullanım',
    '무제한 로컬 사용',
    'ใช้งานในเครื่องไม่จำกัด',
    'အကန့်အသတ်မရှိ local အသုံးပြုမှု',
    'Хязгааргүй орон нутгийн хэрэглээ',
    '',
    'Nieograniczone lokalne użycie');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_title',
    'Pro Tier',
    'Nivel Pro',
    'Pro-Stufe',
    'Pro层',
    'Niveau Pro',
    'Nível Pro',
    'Proティア',
    'Cấp Pro',
    'Pro-niveau',
    'Pro szint',
    'مستوى Pro',
    'سطح Pro',
    'Pro seviyesi',
    'Pro 티어',
    'ระดับ Pro',
    'Pro အဆင့်',
    'Pro түвшин',
    '',
    'Poziom Pro');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_unlocks',
    'Pro unlocks additional features:',
    'Pro desbloquea funciones adicionales:',
    'Pro schaltet zusätzliche Funktionen frei:',
    'Pro解锁额外功能：',
    'Pro débloque des fonctionnalités supplémentaires :',
    'Pro desbloqueia recursos adicionais:',
    'Proは追加機能をアンロックします：',
    'Pro mở khóa các tính năng bổ sung:',
    'Pro ontgrendelt extra functies:',
    'A Pro további funkciókat nyit meg:',
    'يفتح Pro ميزات إضافية:',
    'Pro ویژگی‌های اضافی را باز می‌کند:',
    'Pro ek özelliklerin kilidini açar:',
    'Pro는 추가 기능을 잠금 해제합니다:',
    'Pro ปลดล็อกฟีเจอร์เพิ่มเติม:',
    'Pro သည် အပိုအင်္ဂါရပ်များကို ဖွင့်ပေးသည်:',
    'Pro нэмэлт боломжуудыг нээдэг:',
    '',
    'Pro odblokowuje dodatkowe funkcje:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_detailed',
    'Detailed savings breakdown',
    'Desglose detallado de ahorros',
    'Detaillierte Einsparungsaufschlüsselung',
    '详细节省分析',
    'Ventilation détaillée des économies',
    'Detalhamento de economias',
    '詳細な節約内訳',
    'Phân tích chi tiết tiết kiệm',
    'Gedetailleerd besparingsoverzicht',
    'Részletes megtakarítás-bontás',
    'تفصيل مفصل للتوفير',
    'جزئیات صرفه‌جویی',
    'Ayrıntılı tasarruf dökümü',
    '상세 절약 분석',
    'รายละเอียดการประหยัด',
    'အသေးစိတ်ချွေတာမှုခွဲခြမ်းစိတ်ဖြာမှု',
    'Хэмнэлтийн дэлгэрэнгүй задаргаа',
    '',
    'Szczegółowy rozkład oszczędności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_detailed_desc',
    'with per-command analysis',
    'con análisis por comando',
    'mit Analyse pro Befehl',
    '逐命令分析',
    'avec analyse par commande',
    'com análise por comando',
    'コマンドごとの分析付き',
    'với phân tích theo lệnh',
    'met analyse per commando',
    'parancsonkénti elemzéssel',
    'مع تحليل لكل أمر',
    'با تحلیل هر دستور',
    'komut bazlı analizle',
    '명령별 분석 포함',
    'พร้อมการวิเคราะห์ต่อคำสั่ง',
    'command တစ်ခုချင်းစီ ခွဲခြမ်းစိတ်ဖြာမှုနှင့်',
    'тушаал тус бүрийн шинжилгээтэй',
    '',
    'z analizą per polecenie');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_gif',
    'GIF recording',
    'Grabación de GIF',
    'GIF-Aufnahme',
    'GIF录制',
    'Enregistrement GIF',
    'Gravação de GIF',
    'GIF録画',
    'Ghi GIF',
    'GIF-opname',
    'GIF felvétel',
    'تسجيل GIF',
    'ضبط GIF',
    'GIF kaydı',
    'GIF 녹화',
    'บันทึก GIF',
    'GIF မှတ်တမ်းတင်ခြင်း',
    'GIF бичлэг',
    '',
    'Nagrywanie GIF');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_gif_desc',
    'for creating animated terminal GIFs',
    'para crear GIFs animados de terminal',
    'zum Erstellen animierter Terminal-GIFs',
    '用于创建终端动画GIF',
    'pour créer des GIFs animés de terminal',
    'para criar GIFs animados de terminal',
    'アニメーションターミナルGIFの作成用',
    'để tạo GIF động terminal',
    'voor het maken van geanimeerde terminal-GIF''s',
    'animált terminál GIF-ek készítéséhez',
    'لإنشاء صور GIF متحركة للطرفية',
    'برای ایجاد GIF متحرک ترمینال',
    'animasyonlu terminal GIF''leri oluşturmak için',
    '애니메이션 터미널 GIF 생성용',
    'สำหรับสร้าง GIF แอนิเมชันของเทอร์มินัล',
    'animated terminal GIF များ ဖန်တီးရန်',
    'Анимацитай терминалын GIF үүсгэхэд',
    '',
    'do tworzenia animowanych GIF-ów terminala');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_geofence',
    'IP geofence compliance',
    'Cumplimiento de geovalla IP',
    'IP-Geofence-Compliance',
    'IP地理围栏合规',
    'Conformité géobarrière IP',
    'Conformidade de geofence IP',
    'IPジオフェンスコンプライアンス',
    'Tuân thủ geofence IP',
    'IP-geofence compliance',
    'IP geofence megfelelőség',
    'الامتثال للسياج الجغرافي IP',
    'انطباق geofence IP',
    'IP coğrafi sınır uyumluluğu',
    'IP 지오펜스 규정 준수',
    'การปฏิบัติตาม IP geofence',
    'IP geofence လိုက်နာမှု',
    'IP geofence нийцэл',
    '',
    'Zgodność z geofence IP');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_geofence_desc',
    'For regulated environments',
    'Para entornos regulados',
    'Für regulierte Umgebungen',
    '适用于受监管的环境',
    'Pour les environnements réglementés',
    'Para ambientes regulamentados',
    '規制環境向け',
    'Cho môi trường được quản lý',
    'Voor gereguleerde omgevingen',
    'Szabályozott környezetekhez',
    'للبيئات المنظمة',
    'برای محیط‌های تحت نظارت',
    'Düzenlenmiş ortamlar için',
    '규제 환경용',
    'สำหรับสภาพแวดล้อมที่ถูกควบคุม',
    'ထိန်းချုပ်ထားသော ပတ်ဝန်းကျင်များအတွက်',
    'Зохицуулалттай орчинд зориулсан',
    '',
    'Dla środowisk regulowanych');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_email',
    'Email reports',
    'Informes por correo',
    'E-Mail-Berichte',
    '电子邮件报告',
    'Rapports par e-mail',
    'Relatórios por e-mail',
    'メールレポート',
    'Báo cáo email',
    'E-mailrapporten',
    'E-mail jelentések',
    'تقارير البريد الإلكتروني',
    'گزارش‌های ایمیلی',
    'E-posta raporları',
    '이메일 보고서',
    'รายงานอีเมล',
    'အီးမေးလ် အစီရင်ခံစာများ',
    'Имэйл тайлан',
    '',
    'Raporty e-mail');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_email_desc',
    'to send analytics',
    'para enviar analíticas',
    'zum Senden von Analysen',
    '发送分析报告',
    'pour envoyer des analyses',
    'para enviar análises',
    'アナリティクスを送信',
    'để gửi phân tích',
    'om analyses te versturen',
    'elemzések küldéséhez',
    'لإرسال التحليلات',
    'برای ارسال تحلیل‌ها',
    'analitik göndermek için',
    '분석 전송용',
    'เพื่อส่งการวิเคราะห์',
    'analytics ပို့ရန်',
    'Аналитик илгээхэд',
    '',
    'do wysyłania analiz');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_gha',
    'GitHub Actions analysis',
    'Análisis de GitHub Actions',
    'GitHub-Actions-Analyse',
    'GitHub Actions分析',
    'Analyse GitHub Actions',
    'Análise de GitHub Actions',
    'GitHub Actions分析',
    'Phân tích GitHub Actions',
    'GitHub Actions-analyse',
    'GitHub Actions elemzés',
    'تحليل GitHub Actions',
    'تحلیل GitHub Actions',
    'GitHub Actions analizi',
    'GitHub Actions 분석',
    'การวิเคราะห์ GitHub Actions',
    'GitHub Actions ခွဲခြမ်းစိတ်ဖြာမှု',
    'GitHub Actions шинжилгээ',
    '',
    'Analiza GitHub Actions');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_gha_desc',
    'for failed workflow debugging',
    'para depuración de workflows fallidos',
    'zum Debuggen fehlgeschlagener Workflows',
    '用于调试失败的工作流',
    'pour le débogage des workflows échoués',
    'para depuração de workflows falhados',
    '失敗したワークフローのデバッグ用',
    'để gỡ lỗi workflow thất bại',
    'voor foutopsporing in mislukte workflows',
    'sikertelen munkafolyamatok hibakereséséhez',
    'لتصحيح أخطاء سير العمل الفاشلة',
    'برای رفع اشکال گردش کار ناموفق',
    'başarısız iş akışı hata ayıklaması için',
    '실패한 워크플로 디버깅용',
    'สำหรับการแก้จุดบกพร่องของเวิร์กโฟลว์ที่ล้มเหลว',
    'မအောင်မြင်သော workflow debugging အတွက်',
    'Амжилтгүй workflow дибаг хийхэд',
    '',
    'do debugowania nieudanych workflow');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_compress',
    'Context compression',
    'Compresión de contexto',
    'Kontextkomprimierung',
    '上下文压缩',
    'Compression de contexte',
    'Compressão de contexto',
    'コンテキスト圧縮',
    'Nén ngữ cảnh',
    'Contextcompressie',
    'Kontextus tömörítés',
    'ضغط السياق',
    'فشرده‌سازی زمینه',
    'Bağlam sıkıştırma',
    '컨텍스트 압축',
    'การบีบอัดบริบท',
    'Context ချုံ့ခြင်း',
    'Контекст шахалт',
    '',
    'Kompresja kontekstu');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_compress_desc',
    'for CLAUDE.md optimization',
    'para optimización de CLAUDE.md',
    'zur CLAUDE.md-Optimierung',
    '用于CLAUDE.md优化',
    'pour l''optimisation de CLAUDE.md',
    'para otimização do CLAUDE.md',
    'CLAUDE.mdの最適化用',
    'để tối ưu hóa CLAUDE.md',
    'voor CLAUDE.md-optimalisatie',
    'a CLAUDE.md optimalizálásához',
    'لتحسين CLAUDE.md',
    'برای بهینه‌سازی CLAUDE.md',
    'CLAUDE.md optimizasyonu için',
    'CLAUDE.md 최적화용',
    'สำหรับการเพิ่มประสิทธิภาพ CLAUDE.md',
    'CLAUDE.md optimization အတွက်',
    'CLAUDE.md оновчлолд',
    '',
    'do optymalizacji CLAUDE.md');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_pro_support',
    'Priority support',
    'Soporte prioritario',
    'Prioritäts-Support',
    '优先支持',
    'Support prioritaire',
    'Suporte prioritário',
    '優先サポート',
    'Hỗ trợ ưu tiên',
    'Prioriteitsondersteuning',
    'Elsőbbségi támogatás',
    'دعم ذو أولوية',
    'پشتیبانی اولویت‌دار',
    'Öncelikli destek',
    '우선 지원',
    'การสนับสนุนแบบเร่งด่วน',
    'ဦးစားပေး ပံ့ပိုးမှု',
    'Тэргүүлэх дэмжлэг',
    '',
    'Priorytetowe wsparcie');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_activate_title',
    'Activating a License',
    'Activar una licencia',
    'Eine Lizenz aktivieren',
    '激活许可证',
    'Activer une licence',
    'Ativando uma licença',
    'ライセンスの有効化',
    'Kích hoạt giấy phép',
    'Een licentie activeren',
    'Licenc aktiválása',
    'تفعيل الترخيص',
    'فعال‌سازی مجوز',
    'Lisans etkinleştirme',
    '라이선스 활성화',
    'การเปิดใช้งานใบอนุญาต',
    'လိုင်စင် အသက်သွင်းခြင်း',
    'Лиценз идэвхжүүлэх',
    '',
    'Aktywacja licencji');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_status_title',
    'Checking License Status',
    'Verificar el estado de la licencia',
    'Lizenzstatus prüfen',
    '检查许可证状态',
    'Vérifier le statut de la licence',
    'Verificando o status da licença',
    'ライセンスステータスの確認',
    'Kiểm tra trạng thái giấy phép',
    'Licentiestatus controleren',
    'Licenc állapot ellenőrzése',
    'التحقق من حالة الترخيص',
    'بررسی وضعیت مجوز',
    'Lisans durumunu kontrol etme',
    '라이선스 상태 확인',
    'ตรวจสอบสถานะใบอนุญาต',
    'လိုင်စင်အခြေအနေ စစ်ဆေးခြင်း',
    'Лицензийн төлөв шалгах',
    '',
    'Sprawdzanie statusu licencji');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_sponsors_title',
    'GitHub Sponsors Activation',
    'Activación por GitHub Sponsors',
    'GitHub-Sponsors-Aktivierung',
    'GitHub Sponsors激活',
    'Activation GitHub Sponsors',
    'Ativação por GitHub Sponsors',
    'GitHub Sponsorsアクティベーション',
    'Kích hoạt GitHub Sponsors',
    'GitHub Sponsors-activering',
    'GitHub Sponsors aktiválás',
    'تفعيل GitHub Sponsors',
    'فعال‌سازی GitHub Sponsors',
    'GitHub Sponsors etkinleştirme',
    'GitHub Sponsors 활성화',
    'การเปิดใช้งาน GitHub Sponsors',
    'GitHub Sponsors အသက်သွင်းခြင်း',
    'GitHub Sponsors идэвхжүүлэлт',
    '',
    'Aktywacja GitHub Sponsors');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_sponsors_body',
    'If you sponsor PRECC through GitHub Sponsors, your license is activated automatically via your GitHub email. No key required -- just ensure your sponsor email matches:',
    'Si patrocinas PRECC a través de GitHub Sponsors, tu licencia se activa automáticamente con tu correo de GitHub. No se necesita clave -- solo asegúrate de que tu correo de patrocinador coincida:',
    'Wenn Sie PRECC über GitHub Sponsors sponsern, wird Ihre Lizenz automatisch über Ihre GitHub-E-Mail aktiviert. Kein Schlüssel erforderlich -- stellen Sie nur sicher, dass Ihre Sponsor-E-Mail übereinstimmt:',
    '如果您通过GitHub Sponsors赞助PRECC，您的许可证将通过您的GitHub邮箱自动激活。无需密钥——只需确保您的赞助者邮箱匹配：',
    'Si vous parrainez PRECC via GitHub Sponsors, votre licence est activée automatiquement via votre e-mail GitHub. Pas de clé requise -- assurez-vous simplement que votre e-mail de parrainage correspond :',
    'Se você patrocina PRECC pelo GitHub Sponsors, sua licença é ativada automaticamente via seu e-mail do GitHub. Nenhuma chave necessária -- apenas certifique-se de que seu e-mail de patrocinador corresponde:',
    'GitHub SponsorsでPRECCをスポンサーしている場合、GitHubメールを通じて自動的にライセンスが有効化されます。キーは不要です。スポンサーメールが一致していることを確認してください：',
    'Nếu bạn tài trợ PRECC qua GitHub Sponsors, giấy phép được kích hoạt tự động qua email GitHub của bạn. Không cần khóa -- chỉ cần đảm bảo email tài trợ khớp:',
    'Als u PRECC sponsort via GitHub Sponsors, wordt uw licentie automatisch geactiveerd via uw GitHub-e-mail. Geen sleutel nodig -- zorg er alleen voor dat uw sponsor-e-mail overeenkomt:',
    'Ha a PRECC-et GitHub Sponsors-on keresztül szponzorálja, a licence automatikusan aktiválódik a GitHub e-mail címén keresztül. Nincs szükség kulcsra -- csak győződjön meg róla, hogy a szponzori e-mail egyezik:',
    'إذا كنت ترعى PRECC عبر GitHub Sponsors، يتم تفعيل ترخيصك تلقائيًا عبر بريد GitHub الخاص بك. لا حاجة لمفتاح -- فقط تأكد من تطابق بريد الراعي:',
    'اگر PRECC را از طریق GitHub Sponsors حمایت می‌کنید، مجوز شما به‌طور خودکار از طریق ایمیل GitHub فعال می‌شود. نیازی به کلید نیست -- فقط مطمئن شوید ایمیل حامی مطابقت دارد:',
    'PRECC''i GitHub Sponsors üzerinden sponsor olursanız, lisansınız GitHub e-postanız aracılığıyla otomatik olarak etkinleştirilir. Anahtar gerekmez -- sadece sponsor e-postanızın eşleştiğinden emin olun:',
    'GitHub Sponsors를 통해 PRECC를 후원하면 GitHub 이메일을 통해 라이선스가 자동으로 활성화됩니다. 키가 필요하지 않습니다 -- 후원자 이메일이 일치하는지 확인하세요:',
    'หากคุณสนับสนุน PRECC ผ่าน GitHub Sponsors ใบอนุญาตจะถูกเปิดใช้งานโดยอัตโนมัติผ่านอีเมล GitHub ของคุณ ไม่ต้องใช้คีย์ -- แค่ให้แน่ใจว่าอีเมลผู้สนับสนุนตรงกัน:',
    'GitHub Sponsors မှတဆင့် PRECC ကို ပံ့ပိုးပါက သင့် GitHub email မှတဆင့် လိုင်စင်ကို အလိုအလျောက် အသက်သွင်းပေးသည်။ key မလိုအပ်ပါ -- sponsor email တူညီကြောင်း သေချာပါ:',
    'Хэрэв та GitHub Sponsors-оор PRECC-ийг ивээн тэтгэвэл, таны лиценз GitHub имэйлээр автоматаар идэвхждэг. Түлхүүр шаардлагагүй -- зөвхөн ивээн тэтгэгчийн имэйл таарч байгааг шалгаарай:',
    '',
    'Jeśli sponsorujesz PRECC przez GitHub Sponsors, Twoja licencja jest aktywowana automatycznie przez e-mail GitHub. Klucz nie jest wymagany -- upewnij się tylko, że e-mail sponsora pasuje:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_fingerprint_title',
    'Device Fingerprint',
    'Huella del dispositivo',
    'Geräte-Fingerprint',
    '设备指纹',
    'Empreinte de l''appareil',
    'Impressão digital do dispositivo',
    'デバイスフィンガープリント',
    'Dấu vân tay thiết bị',
    'Apparaat-vingerafdruk',
    'Eszköz-ujjlenyomat',
    'بصمة الجهاز',
    'اثر انگشت دستگاه',
    'Cihaz parmak izi',
    '디바이스 지문',
    'ลายนิ้วมืออุปกรณ์',
    'စက်ပစ္စည်း လက်ဗွေ',
    'Төхөөрөмжийн хурууны хээ',
    '',
    'Odcisk urządzenia');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_fingerprint_body',
    'Each license is tied to a device fingerprint. View yours with:',
    'Cada licencia está vinculada a una huella de dispositivo. Consulta la tuya con:',
    'Jede Lizenz ist an einen Geräte-Fingerprint gebunden. Zeigen Sie Ihren an mit:',
    '每个许可证都绑定到设备指纹。使用以下命令查看：',
    'Chaque licence est liée à une empreinte d''appareil. Consultez la vôtre avec :',
    'Cada licença está vinculada a uma impressão digital do dispositivo. Veja a sua com:',
    '各ライセンスはデバイスフィンガープリントに紐付けられています。以下で確認できます：',
    'Mỗi giấy phép được gắn với dấu vân tay thiết bị. Xem của bạn với:',
    'Elke licentie is gekoppeld aan een apparaat-vingerafdruk. Bekijk de uwe met:',
    'Minden licenc egy eszköz-ujjlenyomathoz van kötve. Tekintse meg az övét:',
    'كل ترخيص مرتبط ببصمة جهاز. اعرض بصمتك باستخدام:',
    'هر مجوز به اثر انگشت دستگاه متصل است. خود را ببینید با:',
    'Her lisans bir cihaz parmak izine bağlıdır. Kendinizinkini görüntüleyin:',
    '각 라이선스는 디바이스 지문에 연결됩니다. 다음으로 확인하세요:',
    'ใบอนุญาตแต่ละใบผูกกับลายนิ้วมืออุปกรณ์ ดูของคุณด้วย:',
    'လိုင်စင်တစ်ခုစီသည် စက်ပစ္စည်းလက်ဗွေနှင့် ချိတ်ဆက်ထားသည်။ သင့်အရာကို ကြည့်ရန်:',
    'Лиценз бүр төхөөрөмжийн хурууны хээтэй холбоотой. Өөрийнхөө хурууны хээг харна уу:',
    '',
    'Każda licencja jest powiązana z odciskiem urządzenia. Sprawdź swój za pomocą:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_transfer_body',
    'If you need to transfer your license to a new machine, deactivate first:',
    'Si necesitas transferir tu licencia a una máquina nueva, desactívala primero:',
    'Wenn Sie Ihre Lizenz auf einen neuen Computer übertragen müssen, deaktivieren Sie sie zuerst:',
    '如果需要将许可证转移到新机器，请先停用：',
    'Si vous devez transférer votre licence sur une nouvelle machine, désactivez d''abord :',
    'Se precisar transferir sua licença para uma nova máquina, desative primeiro:',
    'ライセンスを新しいマシンに移行する必要がある場合は、まず無効化してください：',
    'Nếu bạn cần chuyển giấy phép sang máy mới, hãy hủy kích hoạt trước:',
    'Als u uw licentie naar een nieuwe machine wilt overzetten, deactiveer dan eerst:',
    'Ha át kell helyeznie a licencét egy új gépre, először deaktiválja:',
    'إذا كنت بحاجة إلى نقل ترخيصك إلى جهاز جديد، قم بإلغاء التفعيل أولاً:',
    'اگر نیاز به انتقال مجوز به ماشین جدید دارید، ابتدا غیرفعال کنید:',
    'Lisansınızı yeni bir makineye aktarmanız gerekiyorsa, önce devre dışı bırakın:',
    '라이선스를 새 머신으로 이전해야 하는 경우 먼저 비활성화하세요:',
    'หากต้องการโอนใบอนุญาตไปยังเครื่องใหม่ ให้ยกเลิกการเปิดใช้งานก่อน:',
    'လိုင်စင်ကို စက်အသစ်သို့ လွှဲပြောင်းလိုပါက အရင်ပိတ်ပါ:',
    'Лицензээ шинэ машинд шилжүүлэх шаардлагатай бол эхлээд идэвхгүй болго:',
    '',
    'Jeśli musisz przenieść licencję na nową maszynę, najpierw dezaktywuj:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_transfer_then',
    'Then activate on the new machine.',
    'Luego activa en la nueva máquina.',
    'Dann aktivieren Sie auf dem neuen Computer.',
    '然后在新机器上激活。',
    'Puis activez sur la nouvelle machine.',
    'Depois ative na nova máquina.',
    'その後、新しいマシンで有効化します。',
    'Sau đó kích hoạt trên máy mới.',
    'Activeer vervolgens op de nieuwe machine.',
    'Ezután aktiválja az új gépen.',
    'ثم قم بالتفعيل على الجهاز الجديد.',
    'سپس در ماشین جدید فعال کنید.',
    'Ardından yeni makinede etkinleştirin.',
    '그런 다음 새 머신에서 활성화하세요.',
    'จากนั้นเปิดใช้งานบนเครื่องใหม่',
    'ပြီးနောက် စက်အသစ်တွင် အသက်သွင်းပါ။',
    'Дараа нь шинэ машин дээр идэвхжүүлнэ үү.',
    '',
    'Następnie aktywuj na nowej maszynie.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_expired_title',
    'License Expired?',
    '¿Licencia expirada?',
    'Lizenz abgelaufen?',
    '许可证过期？',
    'Licence expirée ?',
    'Licença expirada?',
    'ライセンスの有効期限切れ？',
    'Giấy phép hết hạn?',
    'Licentie verlopen?',
    'Lejárt a licenc?',
    'هل انتهت صلاحية الترخيص؟',
    'مجوز منقضی شده؟',
    'Lisans süresi doldu mu?',
    '라이선스가 만료되었나요?',
    'ใบอนุญาตหมดอายุ?',
    'လိုင်စင်သက်တမ်းကုန်ပြီလား?',
    'Лицензийн хугацаа дууссан уу?',
    '',
    'Licencja wygasła?');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('lic_expired_body',
    'When a Pro license expires, PRECC reverts to Community tier. All built-in skills and core functionality continue to work. Only Pro-specific features become unavailable. See the [FAQ](faq.md) for more details.',
    'Cuando una licencia Pro expira, PRECC vuelve al nivel Community. Todas las habilidades integradas y la funcionalidad principal siguen funcionando. Solo las funciones específicas de Pro dejan de estar disponibles. Consulta las [FAQ](faq.md) para más detalles.',
    'Wenn eine Pro-Lizenz abläuft, kehrt PRECC zur Community-Stufe zurück. Alle integrierten Skills und Kernfunktionen funktionieren weiterhin. Nur Pro-spezifische Funktionen werden nicht verfügbar. Weitere Details finden Sie in den [FAQ](faq.md).',
    '当Pro许可证到期时，PRECC会恢复到Community层。所有内置技能和核心功能继续工作。只有Pro特有功能变为不可用。详情请参阅[FAQ](faq.md)。',
    'Lorsqu''une licence Pro expire, PRECC revient au niveau Community. Toutes les compétences intégrées et les fonctionnalités de base continuent de fonctionner. Seules les fonctionnalités Pro deviennent indisponibles. Voir la [FAQ](faq.md) pour plus de détails.',
    'Quando uma licença Pro expira, PRECC retorna ao nível Community. Todas as habilidades integradas e funcionalidades principais continuam funcionando. Apenas recursos específicos do Pro ficam indisponíveis. Veja o [FAQ](faq.md) para mais detalhes.',
    'Proライセンスの有効期限が切れると、PRECCはCommunityティアに戻ります。すべての組み込みスキルとコア機能は引き続き動作します。Pro固有の機能のみ利用できなくなります。詳細は[FAQ](faq.md)をご覧ください。',
    'Khi giấy phép Pro hết hạn, PRECC quay lại cấp Community. Tất cả kỹ năng tích hợp và chức năng cốt lõi tiếp tục hoạt động. Chỉ các tính năng dành riêng cho Pro trở nên không khả dụng. Xem [FAQ](faq.md) để biết thêm chi tiết.',
    'Wanneer een Pro-licentie verloopt, keert PRECC terug naar het Community-niveau. Alle ingebouwde vaardigheden en kernfunctionaliteit blijven werken. Alleen Pro-specifieke functies worden onbeschikbaar. Zie de [FAQ](faq.md) voor meer details.',
    'Ha egy Pro licenc lejár, a PRECC visszaáll a Community szintre. Minden beépített képesség és alapfunkció tovább működik. Csak a Pro-specifikus funkciók válnak elérhetetlenné. Lásd a [FAQ](faq.md) oldalt további részletekért.',
    'عندما تنتهي صلاحية ترخيص Pro، يعود PRECC إلى مستوى Community. تستمر جميع المهارات المدمجة والوظائف الأساسية في العمل. فقط الميزات الخاصة بـ Pro تصبح غير متاحة. راجع [الأسئلة الشائعة](faq.md) لمزيد من التفاصيل.',
    'وقتی مجوز Pro منقضی شود، PRECC به سطح Community برمی‌گردد. تمام مهارت‌های داخلی و عملکردهای اصلی به کار خود ادامه می‌دهند. فقط ویژگی‌های خاص Pro غیرقابل دسترس می‌شوند. برای جزئیات بیشتر [سوالات متداول](faq.md) را ببینید.',
    'Bir Pro lisansı sona erdiğinde, PRECC Community seviyesine geri döner. Tüm yerleşik beceriler ve temel işlevler çalışmaya devam eder. Yalnızca Pro''ya özgü özellikler kullanılamaz hale gelir. Daha fazla ayrıntı için [SSS](faq.md) sayfasına bakın.',
    'Pro 라이선스가 만료되면 PRECC는 Community 티어로 되돌아갑니다. 모든 내장 스킬과 핵심 기능은 계속 작동합니다. Pro 전용 기능만 사용할 수 없게 됩니다. 자세한 내용은 [FAQ](faq.md)를 참조하세요.',
    'เมื่อใบอนุญาต Pro หมดอายุ PRECC จะกลับไปที่ระดับ Community ทักษะในตัวและฟังก์ชันหลักทั้งหมดยังคงทำงานต่อไป เฉพาะฟีเจอร์เฉพาะ Pro เท่านั้นที่จะใช้ไม่ได้ ดู [FAQ](faq.md) สำหรับรายละเอียดเพิ่มเติม',
    'Pro လိုင်စင်သက်တမ်းကုန်သောအခါ PRECC သည် Community အဆင့်သို့ ပြန်သွားသည်။ ပါဝင်သော ကျွမ်းကျင်မှုများနှင့် အဓိကလုပ်ဆောင်ချက်များ ဆက်လက်အလုပ်လုပ်သည်။ Pro သီးသန့်အင်္ဂါရပ်များသာ မရနိုင်တော့ပါ။ အသေးစိတ်အတွက် [FAQ](faq.md) ကိုကြည့်ပါ။',
    'Pro лицензийн хугацаа дуусахад PRECC Community түвшинд буцна. Бүх суулгагдсан ур чадвар болон үндсэн функцууд үргэлжлэн ажиллана. Зөвхөн Pro-д зориулсан боломжууд ашиглагдахгүй болно. Дэлгэрэнгүйг [FAQ](faq.md)-аас үзнэ үү.',
    '',
    'Gdy licencja Pro wygaśnie, PRECC wraca do poziomu Community. Wszystkie wbudowane umiejętności i podstawowe funkcje nadal działają. Tylko funkcje specyficzne dla Pro stają się niedostępne. Zobacz [FAQ](faq.md), aby uzyskać więcej szczegółów.');
