-- GIF Recording chapter strings
INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_title',
    'GIF Recording',
    'Grabación GIF',
    'GIF-Aufnahme',
    'GIF录制',
    'Enregistrement GIF',
    'Gravação GIF',
    'GIF録画',
    'Ghi GIF',
    'GIF-opname',
    'GIF-felvétel',
    'تسجيل GIF',
    'ضبط GIF',
    'GIF kaydı',
    'GIF 녹화',
    'การบันทึก GIF',
    'GIF ရိုက်ကူးခြင်း',
    'GIF бичлэг',
    '',
    'Nagrywanie GIF');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_intro',
    '`precc gif` creates animated GIF recordings of terminal sessions from bash scripts. This is a Pro feature.',
    '`precc gif` crea grabaciones GIF animadas de sesiones de terminal a partir de scripts bash. Esta es una función Pro.',
    '`precc gif` erstellt animierte GIF-Aufnahmen von Terminal-Sitzungen aus Bash-Skripten. Dies ist eine Pro-Funktion.',
    '`precc gif` 从bash脚本创建终端会话的动画GIF录制。这是Pro功能。',
    '`precc gif` crée des enregistrements GIF animés de sessions de terminal à partir de scripts bash. C''est une fonctionnalité Pro.',
    '`precc gif` cria gravações GIF animadas de sessões de terminal a partir de scripts bash. Este é um recurso Pro.',
    '`precc gif`はbashスクリプトからターミナルセッションのアニメーションGIF録画を作成します。これはPro機能です。',
    '`precc gif` tạo bản ghi GIF động của phiên terminal từ các script bash. Đây là tính năng Pro.',
    '`precc gif` maakt geanimeerde GIF-opnames van terminalsessies vanuit bash-scripts. Dit is een Pro-functie.',
    'A `precc gif` animált GIF-felvételeket készít terminál-munkamenetekről bash szkriptekből. Ez egy Pro funkció.',
    'يقوم `precc gif` بإنشاء تسجيلات GIF متحركة لجلسات الطرفية من نصوص bash. هذه ميزة Pro.',
    '`precc gif` ضبط‌های GIF متحرک از جلسات ترمینال از اسکریپت‌های bash ایجاد می‌کند. این یک ویژگی Pro است.',
    '`precc gif` bash betiklerinden terminal oturumlarının animasyonlu GIF kayıtlarını oluşturur. Bu bir Pro özelliğidir.',
    '`precc gif`는 bash 스크립트에서 터미널 세션의 애니메이션 GIF 녹화를 생성합니다. Pro 기능입니다.',
    '`precc gif` สร้างการบันทึก GIF แบบเคลื่อนไหวของเซสชันเทอร์มินัลจากสคริปต์ bash นี่เป็นฟีเจอร์ Pro',
    '`precc gif` သည် bash script များမှ terminal session များ၏ animated GIF ရိုက်ကူးမှုများ ဖန်တီးသည်။ ၎င်းသည် Pro အင်္ဂါရပ်ဖြစ်သည်။',
    '`precc gif` нь bash скриптээс терминал сешний анимацитай GIF бичлэг үүсгэнэ. Энэ нь Pro боломж юм.',
    '',
    '`precc gif` tworzy animowane nagrania GIF sesji terminala ze skryptów bash. To funkcja Pro.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_basic_title',
    'Basic Usage',
    'Uso básico',
    'Grundlegende Verwendung',
    '基本用法',
    'Utilisation de base',
    'Uso básico',
    '基本的な使い方',
    'Cách sử dụng cơ bản',
    'Basisgebruik',
    'Alapvető használat',
    'الاستخدام الأساسي',
    'استفاده پایه',
    'Temel kullanım',
    '기본 사용법',
    'การใช้งานพื้นฐาน',
    'အခြေခံ အသုံးပြုပုံ',
    'Үндсэн хэрэглээ',
    '',
    'Podstawowe użycie');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_basic_body',
    'The first argument is a bash script containing the commands to run. The second argument is the maximum recording length.',
    'El primer argumento es un script bash que contiene los comandos a ejecutar. El segundo argumento es la duración máxima de la grabación.',
    'Das erste Argument ist ein Bash-Skript mit den auszuführenden Befehlen. Das zweite Argument ist die maximale Aufnahmedauer.',
    '第一个参数是包含要运行的命令的bash脚本。第二个参数是最大录制时长。',
    'Le premier argument est un script bash contenant les commandes à exécuter. Le second argument est la durée maximale d''enregistrement.',
    'O primeiro argumento é um script bash contendo os comandos a executar. O segundo argumento é a duração máxima da gravação.',
    '最初の引数は実行するコマンドを含むbashスクリプトです。2番目の引数は最大録画時間です。',
    'Đối số đầu tiên là một script bash chứa các lệnh cần chạy. Đối số thứ hai là thời lượng ghi tối đa.',
    'Het eerste argument is een bash-script met de uit te voeren opdrachten. Het tweede argument is de maximale opnameduur.',
    'Az első argumentum egy bash szkript a futtatandó parancsokkal. A második argumentum a maximális felvételi hossz.',
    'الوسيط الأول هو نص bash يحتوي على الأوامر المراد تشغيلها. الوسيط الثاني هو الحد الأقصى لطول التسجيل.',
    'آرگومان اول یک اسکریپت bash حاوی دستورات اجرایی است. آرگومان دوم حداکثر طول ضبط است.',
    'İlk argüman çalıştırılacak komutları içeren bir bash betiğidir. İkinci argüman maksimum kayıt süresidir.',
    '첫 번째 인수는 실행할 명령을 포함하는 bash 스크립트입니다. 두 번째 인수는 최대 녹화 시간입니다.',
    'อาร์กิวเมนต์แรกเป็นสคริปต์ bash ที่มีคำสั่งที่จะรัน อาร์กิวเมนต์ที่สองคือความยาวการบันทึกสูงสุด',
    'ပထမ argument သည် run ရမည့် command များပါဝင်သော bash script ဖြစ်သည်။ ဒုတိယ argument သည် အများဆုံး ရိုက်ကူးမှု အရှည်ဖြစ်သည်။',
    'Эхний аргумент нь ажиллуулах командуудыг агуулсан bash скрипт юм. Хоёр дахь аргумент нь бичлэгийн дээд хэмжээ юм.',
    '',
    'Pierwszy argument to skrypt bash zawierający polecenia do uruchomienia. Drugi argument to maksymalna długość nagrania.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_script_title',
    'Script Format',
    'Formato del script',
    'Skriptformat',
    '脚本格式',
    'Format du script',
    'Formato do script',
    'スクリプト形式',
    'Định dạng script',
    'Scriptformaat',
    'Szkript formátum',
    'تنسيق النص',
    'فرمت اسکریپت',
    'Betik formatı',
    '스크립트 형식',
    'รูปแบบสคริปต์',
    'Script ပုံစံ',
    'Скриптийн формат',
    '',
    'Format skryptu');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_script_body',
    'The script is a standard bash file:',
    'El script es un archivo bash estándar:',
    'Das Skript ist eine Standard-Bash-Datei:',
    '脚本是标准的bash文件：',
    'Le script est un fichier bash standard :',
    'O script é um arquivo bash padrão:',
    'スクリプトは標準的なbashファイルです：',
    'Script là một tệp bash tiêu chuẩn:',
    'Het script is een standaard bash-bestand:',
    'A szkript egy szabványos bash fájl:',
    'النص هو ملف bash قياسي:',
    'اسکریپت یک فایل bash استاندارد است:',
    'Betik standart bir bash dosyasıdır:',
    '스크립트는 표준 bash 파일입니다:',
    'สคริปต์เป็นไฟล์ bash มาตรฐาน:',
    'Script သည် standard bash ဖိုင်ဖြစ်သည်:',
    'Скрипт нь стандарт bash файл юм:',
    '',
    'Skrypt to standardowy plik bash:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_input_title',
    'Input Simulation',
    'Simulación de entrada',
    'Eingabesimulation',
    '输入模拟',
    'Simulation d''entrée',
    'Simulação de entrada',
    '入力シミュレーション',
    'Mô phỏng đầu vào',
    'Invoersimulatie',
    'Bemenet szimuláció',
    'محاكاة الإدخال',
    'شبیه‌سازی ورودی',
    'Girdi simülasyonu',
    '입력 시뮬레이션',
    'การจำลองอินพุต',
    'Input Simulation',
    'Оролтын симуляц',
    '',
    'Symulacja danych wejściowych');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_input_body',
    'For interactive commands, provide input values as additional arguments:',
    'Para comandos interactivos, proporcione valores de entrada como argumentos adicionales:',
    'Für interaktive Befehle geben Sie Eingabewerte als zusätzliche Argumente an:',
    '对于交互式命令，提供输入值作为额外参数：',
    'Pour les commandes interactives, fournissez les valeurs d''entrée comme arguments supplémentaires :',
    'Para comandos interativos, forneça valores de entrada como argumentos adicionais:',
    'インタラクティブコマンドの場合、追加引数として入力値を指定します：',
    'Đối với các lệnh tương tác, cung cấp giá trị đầu vào làm đối số bổ sung:',
    'Geef voor interactieve opdrachten invoerwaarden op als extra argumenten:',
    'Interaktív parancsoknál adja meg a bemeneti értékeket további argumentumként:',
    'للأوامر التفاعلية، قدم قيم الإدخال كوسائط إضافية:',
    'برای دستورات تعاملی، مقادیر ورودی را به عنوان آرگومان‌های اضافی ارائه دهید:',
    'Etkileşimli komutlar için giriş değerlerini ek argümanlar olarak sağlayın:',
    '대화형 명령의 경우 입력 값을 추가 인수로 제공하세요:',
    'สำหรับคำสั่งแบบโต้ตอบ ให้ระบุค่าอินพุตเป็นอาร์กิวเมนต์เพิ่มเติม:',
    'Interactive command များအတွက်၊ input တန်ဖိုးများကို argument အပိုများအဖြစ် ပေးပါ:',
    'Интерактив командын хувьд оролтын утгуудыг нэмэлт аргумент болгон өгнө:',
    '',
    'W przypadku poleceń interaktywnych podaj wartości wejściowe jako dodatkowe argumenty:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_input_detail',
    'Each additional argument is fed as a line of stdin when the script prompts for input.',
    'Cada argumento adicional se proporciona como una línea de stdin cuando el script solicita entrada.',
    'Jedes zusätzliche Argument wird als stdin-Zeile übergeben, wenn das Skript nach Eingabe fragt.',
    '每个额外参数在脚本提示输入时作为一行stdin输入。',
    'Chaque argument supplémentaire est fourni comme une ligne stdin lorsque le script demande une entrée.',
    'Cada argumento adicional é fornecido como uma linha de stdin quando o script solicita entrada.',
    '追加の各引数は、スクリプトが入力を要求するときにstdinの行として渡されます。',
    'Mỗi đối số bổ sung được cung cấp dưới dạng một dòng stdin khi script yêu cầu đầu vào.',
    'Elk extra argument wordt als een stdin-regel ingevoerd wanneer het script om invoer vraagt.',
    'Minden további argumentum stdin-sorként kerül beadásra, amikor a szkript bemenetet kér.',
    'يتم تقديم كل وسيط إضافي كسطر stdin عندما يطلب النص إدخالاً.',
    'هر آرگومان اضافی به عنوان یک خط stdin هنگامی که اسکریپت ورودی درخواست می‌کند ارائه می‌شود.',
    'Her ek argüman, betik girdi istediğinde bir stdin satırı olarak beslenir.',
    '각 추가 인수는 스크립트가 입력을 요청할 때 stdin 줄로 전달됩니다.',
    'อาร์กิวเมนต์เพิ่มเติมแต่ละตัวจะถูกป้อนเป็นบรรทัด stdin เมื่อสคริปต์ร้องขออินพุต',
    'Script က input တောင်းသောအခါ argument အပိုတစ်ခုစီကို stdin စာကြောင်းတစ်ကြောင်းအဖြစ် ထည့်သွင်းသည်။',
    'Скрипт оролт хүсэх үед нэмэлт аргумент тус бүрийг stdin мөр болгон өгнө.',
    '',
    'Każdy dodatkowy argument jest podawany jako linia stdin, gdy skrypt prosi o dane wejściowe.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_output_title',
    'Output Options',
    'Opciones de salida',
    'Ausgabeoptionen',
    '输出选项',
    'Options de sortie',
    'Opções de saída',
    '出力オプション',
    'Tùy chọn đầu ra',
    'Uitvoeropties',
    'Kimeneti beállítások',
    'خيارات الإخراج',
    'گزینه‌های خروجی',
    'Çıktı seçenekleri',
    '출력 옵션',
    'ตัวเลือกเอาต์พุต',
    'Output ရွေးချယ်စရာများ',
    'Гаралтын сонголтууд',
    '',
    'Opcje wyjścia');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_output_body',
    'The output file is named after the script by default (`script.gif`). The GIF uses a dark terminal theme with standard 80x24 dimensions.',
    'El archivo de salida se nombra según el script por defecto (`script.gif`). El GIF usa un tema de terminal oscuro con dimensiones estándar 80x24.',
    'Die Ausgabedatei wird standardmäßig nach dem Skript benannt (`script.gif`). Das GIF verwendet ein dunkles Terminal-Theme mit Standard-80x24-Dimensionen.',
    '输出文件默认以脚本命名（`script.gif`）。GIF使用深色终端主题，标准80x24尺寸。',
    'Le fichier de sortie est nommé d''après le script par défaut (`script.gif`). Le GIF utilise un thème de terminal sombre avec des dimensions standard 80x24.',
    'O arquivo de saída é nomeado com base no script por padrão (`script.gif`). O GIF usa um tema de terminal escuro com dimensões padrão 80x24.',
    '出力ファイルはデフォルトでスクリプト名に基づいて命名されます（`script.gif`）。GIFはダークターミナルテーマで標準80x24サイズを使用します。',
    'Tệp đầu ra được đặt tên theo script mặc định (`script.gif`). GIF sử dụng giao diện terminal tối với kích thước chuẩn 80x24.',
    'Het uitvoerbestand wordt standaard vernoemd naar het script (`script.gif`). De GIF gebruikt een donker terminalthema met standaard 80x24-afmetingen.',
    'A kimeneti fájl alapértelmezés szerint a szkriptről kap nevet (`script.gif`). A GIF sötét terminál-témát használ szabványos 80x24-es méretekkel.',
    'يتم تسمية ملف الإخراج باسم النص بشكل افتراضي (`script.gif`). يستخدم GIF سمة طرفية داكنة بأبعاد قياسية 80x24.',
    'فایل خروجی به طور پیش‌فرض بر اساس نام اسکریپت نام‌گذاری می‌شود (`script.gif`). GIF از تم تاریک ترمینال با ابعاد استاندارد 80x24 استفاده می‌کند.',
    'Çıktı dosyası varsayılan olarak betiğin adını alır (`script.gif`). GIF, standart 80x24 boyutlarında koyu bir terminal teması kullanır.',
    '출력 파일은 기본적으로 스크립트 이름을 따릅니다(`script.gif`). GIF는 표준 80x24 크기의 어두운 터미널 테마를 사용합니다.',
    'ไฟล์เอาต์พุตจะตั้งชื่อตามสคริปต์เป็นค่าเริ่มต้น (`script.gif`) GIF ใช้ธีมเทอร์มินัลสีเข้มขนาดมาตรฐาน 80x24',
    'Output ဖိုင်သည် default အားဖြင့် script အမည်အတိုင်း သတ်မှတ်သည် (`script.gif`)။ GIF သည် standard 80x24 အတိုင်းအတာဖြင့် dark terminal theme ကို အသုံးပြုသည်။',
    'Гаралтын файл нь анхдагчаар скриптийн нэрээр нэрлэгдэнэ (`script.gif`). GIF нь стандарт 80x24 хэмжээтэй харанхуй терминал загварыг ашигладаг.',
    '',
    'Plik wyjściowy jest domyślnie nazwany po skrypcie (`script.gif`). GIF używa ciemnego motywu terminala o standardowych wymiarach 80x24.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_why_title',
    'Why GIF Instead of asciinema?',
    '¿Por qué GIF en lugar de asciinema?',
    'Warum GIF statt asciinema?',
    '为什么使用GIF而不是asciinema？',
    'Pourquoi GIF au lieu d''asciinema ?',
    'Por que GIF ao invés de asciinema?',
    'なぜasciinemaではなくGIFなのか？',
    'Tại sao GIF thay vì asciinema?',
    'Waarom GIF in plaats van asciinema?',
    'Miért GIF az asciinema helyett?',
    'لماذا GIF بدلاً من asciinema؟',
    'چرا GIF به جای asciinema؟',
    'Neden asciinema yerine GIF?',
    '왜 asciinema 대신 GIF인가?',
    'ทำไมต้อง GIF แทน asciinema?',
    'ဘာကြောင့် asciinema အစား GIF သုံးသလဲ?',
    'Яагаад asciinema биш GIF вэ?',
    '',
    'Dlaczego GIF zamiast asciinema?');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('gif_why_body',
    'The `asciinema-gif` built-in skill automatically rewrites `asciinema rec` to `precc gif`. GIF files are more portable -- they display inline in GitHub READMEs, Slack, and email without requiring a player.',
    'La habilidad integrada `asciinema-gif` reescribe automáticamente `asciinema rec` a `precc gif`. Los archivos GIF son más portátiles: se muestran en línea en READMEs de GitHub, Slack y correo electrónico sin necesidad de un reproductor.',
    'Der eingebaute Skill `asciinema-gif` schreibt `asciinema rec` automatisch in `precc gif` um. GIF-Dateien sind portabler -- sie werden inline in GitHub-READMEs, Slack und E-Mails angezeigt, ohne einen Player zu benötigen.',
    '内置技能 `asciinema-gif` 自动将 `asciinema rec` 重写为 `precc gif`。GIF文件更具可移植性——它们可以在GitHub README、Slack和电子邮件中内联显示，无需播放器。',
    'La compétence intégrée `asciinema-gif` réécrit automatiquement `asciinema rec` en `precc gif`. Les fichiers GIF sont plus portables -- ils s''affichent en ligne dans les README GitHub, Slack et les e-mails sans nécessiter de lecteur.',
    'A habilidade integrada `asciinema-gif` reescreve automaticamente `asciinema rec` para `precc gif`. Arquivos GIF são mais portáteis -- eles são exibidos inline em READMEs do GitHub, Slack e e-mail sem necessitar de um player.',
    '組み込みスキル `asciinema-gif` は `asciinema rec` を自動的に `precc gif` に書き換えます。GIFファイルはより移植性が高く、GitHub README、Slack、メールでプレーヤーなしでインライン表示されます。',
    'Kỹ năng tích hợp `asciinema-gif` tự động viết lại `asciinema rec` thành `precc gif`. Tệp GIF dễ di chuyển hơn -- chúng hiển thị trực tiếp trong GitHub README, Slack và email mà không cần trình phát.',
    'De ingebouwde vaardigheid `asciinema-gif` herschrijft `asciinema rec` automatisch naar `precc gif`. GIF-bestanden zijn draagbaarder -- ze worden inline weergegeven in GitHub READMEs, Slack en e-mail zonder een speler nodig te hebben.',
    'Az `asciinema-gif` beépített készség automatikusan átírja az `asciinema rec`-et `precc gif`-re. A GIF-fájlok hordozhatóbbak -- megjelennek a GitHub README-kban, Slackben és e-mailben lejátszó nélkül.',
    'تقوم مهارة `asciinema-gif` المدمجة بإعادة كتابة `asciinema rec` تلقائياً إلى `precc gif`. ملفات GIF أكثر قابلية للنقل -- تُعرض مباشرة في ملفات GitHub README وSlack والبريد الإلكتروني دون الحاجة إلى مشغل.',
    'مهارت داخلی `asciinema-gif` به طور خودکار `asciinema rec` را به `precc gif` بازنویسی می‌کند. فایل‌های GIF قابل حمل‌تر هستند -- بدون نیاز به پخش‌کننده در GitHub README، Slack و ایمیل نمایش داده می‌شوند.',
    'Yerleşik `asciinema-gif` becerisi `asciinema rec` komutunu otomatik olarak `precc gif` olarak yeniden yazar. GIF dosyaları daha taşınabilirdir -- GitHub README''lerinde, Slack''te ve e-postada bir oynatıcı gerektirmeden satır içi görüntülenirler.',
    '내장 스킬 `asciinema-gif`는 `asciinema rec`를 자동으로 `precc gif`로 다시 작성합니다. GIF 파일은 더 이식성이 높습니다 -- 플레이어 없이 GitHub README, Slack, 이메일에서 인라인으로 표시됩니다.',
    'ทักษะในตัว `asciinema-gif` จะเขียนใหม่ `asciinema rec` เป็น `precc gif` โดยอัตโนมัติ ไฟล์ GIF พกพาได้ง่ายกว่า -- แสดงแบบอินไลน์ใน GitHub README, Slack และอีเมลโดยไม่ต้องใช้โปรแกรมเล่น',
    'Built-in skill `asciinema-gif` သည် `asciinema rec` ကို `precc gif` သို့ အလိုအလျောက် ပြန်ရေးသည်။ GIF ဖိုင်များသည် ပိုမို portable ဖြစ်သည် -- GitHub README, Slack နှင့် email တွင် player မလိုဘဲ inline ပြသနိုင်သည်။',
    'Суурилуулсан `asciinema-gif` чадвар нь `asciinema rec`-ийг автоматаар `precc gif` болгон дахин бичнэ. GIF файлууд илүү зөөврийн -- GitHub README, Slack, имэйлд тоглуулагч шаардахгүйгээр inline харагдана.',
    '',
    'Wbudowana umiejętność `asciinema-gif` automatycznie zamienia `asciinema rec` na `precc gif`. Pliki GIF są bardziej przenośne -- wyświetlają się inline w README GitHub, Slack i e-mailu bez potrzeby odtwarzacza.');
