-- Command Reference chapter strings
-- Languages: en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_title',
    'Command Reference',
    'Referencia de comandos',
    'Befehlsreferenz',
    '命令参考',
    'Référence des commandes',
    'Referência de comandos',
    'コマンドリファレンス',
    'Tham chiếu lệnh',
    'Opdrachtreferentie',
    'Parancsreferencia',
    'مرجع الأوامر',
    'مرجع دستورات',
    'Komut referansı',
    '명령어 참조',
    'อ้างอิงคำสั่ง',
    'ကွန်မန်း ရည်ညွှန်းချက်',
    'Командын лавлагаа',
    '',
    'Referencja poleceń');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_subtitle',
    'Complete reference for all PRECC commands.',
    'Referencia completa de todos los comandos de PRECC.',
    'Vollständige Referenz für alle PRECC-Befehle.',
    '所有PRECC命令的完整参考。',
    'Référence complète de toutes les commandes PRECC.',
    'Referência completa de todos os comandos do PRECC.',
    '全PRECCコマンドの完全リファレンス。',
    'Tham chiếu đầy đủ cho tất cả các lệnh PRECC.',
    'Volledige referentie voor alle PRECC-opdrachten.',
    'Teljes referencia az összes PRECC parancshoz.',
    'مرجع كامل لجميع أوامر PRECC.',
    'مرجع کامل برای تمام دستورات PRECC.',
    'Tüm PRECC komutları için eksiksiz referans.',
    '모든 PRECC 명령어에 대한 전체 참조.',
    'เอกสารอ้างอิงฉบับสมบูรณ์สำหรับคำสั่ง PRECC ทั้งหมด',
    'PRECC ကွန်မန်း အားလုံးအတွက် ရည်ညွှန်းချက် အပြည့်အစုံ။',
    'Бүх PRECC командын бүрэн лавлагаа.',
    '',
    'Pełna referencja wszystkich poleceń PRECC.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_init_desc',
    'Initialize PRECC and register the hook with Claude Code.',
    'Inicializar PRECC y registrar el hook con Claude Code.',
    'PRECC initialisieren und den Hook bei Claude Code registrieren.',
    '初始化PRECC并向Claude Code注册钩子。',
    'Initialiser PRECC et enregistrer le hook avec Claude Code.',
    'Inicializar o PRECC e registrar o hook com o Claude Code.',
    'PRECCを初期化し、Claude Codeにフックを登録します。',
    'Khởi tạo PRECC và đăng ký hook với Claude Code.',
    'PRECC initialiseren en de hook registreren bij Claude Code.',
    'A PRECC inicializálása és a hook regisztrálása a Claude Code-ban.',
    'تهيئة PRECC وتسجيل الـ hook مع Claude Code.',
    'مقداردهی اولیه PRECC و ثبت هوک با Claude Code.',
    'PRECC''yi başlatın ve hook''u Claude Code ile kaydedin.',
    'PRECC를 초기화하고 Claude Code에 훅을 등록합니다.',
    'เริ่มต้น PRECC และลงทะเบียน hook กับ Claude Code',
    'PRECC ကို စတင်ပြီး Claude Code နှင့် hook မှတ်ပုံတင်ပါ။',
    'PRECC-ийг эхлүүлж, Claude Code-д hook бүртгэх.',
    '',
    'Zainicjalizuj PRECC i zarejestruj hook w Claude Code.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_ingest_desc',
    'Mine session logs for failure-fix patterns.',
    'Minar registros de sesión en busca de patrones de fallo-corrección.',
    'Sitzungsprotokolle nach Fehler-Fix-Mustern durchsuchen.',
    '挖掘会话日志中的失败-修复模式。',
    'Explorer les journaux de session pour des modèles échec-correction.',
    'Minerar logs de sessão em busca de padrões falha-correção.',
    'セッションログから失敗-修正パターンをマイニングします。',
    'Khai thác nhật ký phiên để tìm các mẫu lỗi-sửa.',
    'Sessielogs doorzoeken op fout-fix-patronen.',
    'Munkamenet-naplók bányászata hiba-javítás mintákért.',
    'استخراج أنماط الفشل-الإصلاح من سجلات الجلسات.',
    'استخراج الگوهای شکست-اصلاح از لاگ‌های جلسه.',
    'Oturum günlüklerinde hata-düzeltme kalıpları arayın.',
    '세션 로그에서 실패-수정 패턴을 마이닝합니다.',
    'ขุดบันทึกเซสชันเพื่อหารูปแบบข้อผิดพลาด-การแก้ไข',
    'Session log များမှ failure-fix ပုံစံများ ရှာဖွေပါ။',
    'Сессийн логоос алдаа-засвар хэв маягийг олборлох.',
    '',
    'Wydobywaj wzorce awaria-naprawa z logów sesji.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_skills_desc',
    'Manage automation skills.',
    'Gestionar habilidades de automatización.',
    'Automatisierungsskills verwalten.',
    '管理自动化技能。',
    'Gérer les compétences d''automatisation.',
    'Gerenciar habilidades de automação.',
    '自動化スキルを管理します。',
    'Quản lý các kỹ năng tự động hóa.',
    'Automatiseringsvaardigheden beheren.',
    'Automatizálási képességek kezelése.',
    'إدارة مهارات الأتمتة.',
    'مدیریت مهارت‌های خودکارسازی.',
    'Otomasyon becerilerini yönetin.',
    '자동화 스킬을 관리합니다.',
    'จัดการทักษะอัตโนมัติ',
    'Automation ကျွမ်းကျင်မှုများ စီမံပါ။',
    'Автоматжуулалтын чадваруудыг удирдах.',
    '',
    'Zarządzaj umiejętnościami automatyzacji.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_report_desc',
    'Generate an analytics report.',
    'Generar un informe analítico.',
    'Einen Analysebericht erstellen.',
    '生成分析报告。',
    'Générer un rapport d''analyse.',
    'Gerar um relatório analítico.',
    '分析レポートを生成します。',
    'Tạo báo cáo phân tích.',
    'Een analyserapport genereren.',
    'Elemzési jelentés generálása.',
    'إنشاء تقرير تحليلي.',
    'تولید گزارش تحلیلی.',
    'Bir analiz raporu oluşturun.',
    '분석 보고서를 생성합니다.',
    'สร้างรายงานวิเคราะห์',
    'ခွဲခြမ်းစိတ်ဖြာမှု အစီရင်ခံစာ ထုတ်ပါ။',
    'Аналитик тайлан үүсгэх.',
    '',
    'Wygeneruj raport analityczny.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_savings_desc',
    'Show token savings.',
    'Mostrar ahorro de tokens.',
    'Token-Einsparungen anzeigen.',
    '显示token节省。',
    'Afficher les économies de tokens.',
    'Mostrar economia de tokens.',
    'トークン節約を表示します。',
    'Hiển thị tiết kiệm token.',
    'Token-besparingen tonen.',
    'Token megtakarítások megjelenítése.',
    'عرض توفير الرموز.',
    'نمایش صرفه‌جویی توکن.',
    'Token tasarruflarını gösterin.',
    '토큰 절감을 표시합니다.',
    'แสดงการประหยัด token',
    'Token ချွေတာမှု ပြသပါ။',
    'Токены хэмнэлтийг харуулах.',
    '',
    'Pokaż oszczędności tokenów.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_compress_desc',
    'Compress context files to reduce token usage.',
    'Comprimir archivos de contexto para reducir el uso de tokens.',
    'Kontextdateien komprimieren, um Token-Verbrauch zu reduzieren.',
    '压缩上下文文件以减少token使用。',
    'Compresser les fichiers de contexte pour réduire l''utilisation de tokens.',
    'Comprimir arquivos de contexto para reduzir o uso de tokens.',
    'コンテキストファイルを圧縮してトークン使用量を削減します。',
    'Nén các tệp ngữ cảnh để giảm sử dụng token.',
    'Contextbestanden comprimeren om tokengebruik te verminderen.',
    'Kontextusfájlok tömörítése a tokenhasználat csökkentése érdekében.',
    'ضغط ملفات السياق لتقليل استخدام الرموز.',
    'فشرده‌سازی فایل‌های زمینه برای کاهش مصرف توکن.',
    'Token kullanımını azaltmak için bağlam dosyalarını sıkıştırın.',
    '토큰 사용량을 줄이기 위해 컨텍스트 파일을 압축합니다.',
    'บีบอัดไฟล์บริบทเพื่อลดการใช้ token',
    'Token အသုံးပြုမှု လျှော့ချရန် context ဖိုင်များ ချုံ့ပါ။',
    'Токены хэрэглээг бууруулахын тулд контекст файлуудыг шахах.',
    '',
    'Kompresuj pliki kontekstowe, aby zmniejszyć zużycie tokenów.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_license_desc',
    'Manage your PRECC license.',
    'Gestionar su licencia PRECC.',
    'Ihre PRECC-Lizenz verwalten.',
    '管理您的PRECC许可证。',
    'Gérer votre licence PRECC.',
    'Gerenciar sua licença PRECC.',
    'PRECCライセンスを管理します。',
    'Quản lý giấy phép PRECC của bạn.',
    'Uw PRECC-licentie beheren.',
    'A PRECC licenc kezelése.',
    'إدارة ترخيص PRECC الخاص بك.',
    'مدیریت مجوز PRECC شما.',
    'PRECC lisansınızı yönetin.',
    'PRECC 라이선스를 관리합니다.',
    'จัดการใบอนุญาต PRECC ของคุณ',
    'သင့် PRECC လိုင်စင် စီမံပါ။',
    'PRECC лицензээ удирдах.',
    '',
    'Zarządzaj licencją PRECC.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_mail_desc',
    'Email functionality.',
    'Funcionalidad de correo electrónico.',
    'E-Mail-Funktionalität.',
    '电子邮件功能。',
    'Fonctionnalité email.',
    'Funcionalidade de email.',
    'メール機能。',
    'Chức năng email.',
    'E-mailfunctionaliteit.',
    'E-mail funkció.',
    'وظائف البريد الإلكتروني.',
    'عملکرد ایمیل.',
    'E-posta işlevselliği.',
    '이메일 기능.',
    'ฟังก์ชันอีเมล',
    'အီးမေးလ် လုပ်ဆောင်ချက်။',
    'И-мэйл функц.',
    '',
    'Funkcjonalność e-mail.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_update_desc',
    'Update PRECC to the latest version.',
    'Actualizar PRECC a la última versión.',
    'PRECC auf die neueste Version aktualisieren.',
    '将PRECC更新到最新版本。',
    'Mettre à jour PRECC vers la dernière version.',
    'Atualizar o PRECC para a versão mais recente.',
    'PRECCを最新バージョンに更新します。',
    'Cập nhật PRECC lên phiên bản mới nhất.',
    'PRECC bijwerken naar de nieuwste versie.',
    'A PRECC frissítése a legújabb verzióra.',
    'تحديث PRECC إلى أحدث إصدار.',
    'به‌روزرسانی PRECC به آخرین نسخه.',
    'PRECC''yi en son sürüme güncelleyin.',
    'PRECC를 최신 버전으로 업데이트합니다.',
    'อัปเดต PRECC เป็นเวอร์ชันล่าสุด',
    'PRECC ကို နောက်ဆုံးဗားရှင်းသို့ အပ်ဒိတ်ပါ။',
    'PRECC-ийг хамгийн сүүлийн хувилбар руу шинэчлэх.',
    '',
    'Zaktualizuj PRECC do najnowszej wersji.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_telemetry_desc',
    'Manage anonymous telemetry.',
    'Gestionar telemetría anónima.',
    'Anonyme Telemetrie verwalten.',
    '管理匿名遥测。',
    'Gérer la télémétrie anonyme.',
    'Gerenciar telemetria anônima.',
    '匿名テレメトリを管理します。',
    'Quản lý đo lường từ xa ẩn danh.',
    'Anonieme telemetrie beheren.',
    'Anonim telemetria kezelése.',
    'إدارة القياس عن بعد المجهول.',
    'مدیریت تله‌متری ناشناس.',
    'Anonim telemetriyi yönetin.',
    '익명 텔레메트리를 관리합니다.',
    'จัดการการวัดระยะไกลแบบไม่ระบุตัวตน',
    'အမည်မသိ အဝေးမှတိုင်းတာခြင်း စီမံပါ။',
    'Нэргүй телеметрийг удирдах.',
    '',
    'Zarządzaj anonimową telemetrią.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_geofence_desc',
    'IP geofence compliance (Pro).',
    'Cumplimiento de geovalla IP (Pro).',
    'IP-Geofence-Compliance (Pro).',
    'IP地理围栏合规（Pro）。',
    'Conformité géorepérage IP (Pro).',
    'Conformidade de geofence IP (Pro).',
    'IPジオフェンスコンプライアンス（Pro）。',
    'Tuân thủ geofence IP (Pro).',
    'IP-geofence compliance (Pro).',
    'IP geofence megfelelőség (Pro).',
    'التوافق الجغرافي لعنوان IP (Pro).',
    'رعایت حصار جغرافیایی IP (Pro).',
    'IP coğrafi sınır uyumluluğu (Pro).',
    'IP 지오펜스 준수 (Pro).',
    'การปฏิบัติตาม geofence IP (Pro)',
    'IP geofence လိုက်နာမှု (Pro)။',
    'IP geofence нийцэл (Pro).',
    '',
    'Zgodność geofence IP (Pro).');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_gif_desc',
    'Record animated GIFs from bash scripts (Pro).',
    'Grabar GIFs animados desde scripts bash (Pro).',
    'Animierte GIFs aus Bash-Skripten aufnehmen (Pro).',
    '从bash脚本录制动画GIF（Pro）。',
    'Enregistrer des GIFs animés à partir de scripts bash (Pro).',
    'Gravar GIFs animados a partir de scripts bash (Pro).',
    'bashスクリプトからアニメーションGIFを録画（Pro）。',
    'Ghi GIF động từ các tập lệnh bash (Pro).',
    'Geanimeerde GIF''s opnemen van bash-scripts (Pro).',
    'Animált GIF-ek rögzítése bash szkriptekből (Pro).',
    'تسجيل صور GIF متحركة من نصوص bash (Pro).',
    'ضبط GIF متحرک از اسکریپت‌های bash (Pro).',
    'Bash betiklerinden animasyonlu GIF''ler kaydedin (Pro).',
    'bash 스크립트에서 애니메이션 GIF 녹화 (Pro).',
    'บันทึก GIF แบบเคลื่อนไหวจากสคริปต์ bash (Pro)',
    'bash script များမှ animated GIF များ ရိုက်ကူးပါ (Pro)။',
    'Bash скриптээс анимэйшн GIF бичих (Pro).',
    '',
    'Nagrywaj animowane GIF-y ze skryptów bash (Pro).');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_gha_desc',
    'Analyze failed GitHub Actions runs (Pro).',
    'Analizar ejecuciones fallidas de GitHub Actions (Pro).',
    'Fehlgeschlagene GitHub Actions-Läufe analysieren (Pro).',
    '分析失败的GitHub Actions运行（Pro）。',
    'Analyser les exécutions échouées de GitHub Actions (Pro).',
    'Analisar execuções falhas do GitHub Actions (Pro).',
    '失敗したGitHub Actionsの実行を分析（Pro）。',
    'Phân tích các lần chạy GitHub Actions thất bại (Pro).',
    'Mislukte GitHub Actions-runs analyseren (Pro).',
    'Sikertelen GitHub Actions futások elemzése (Pro).',
    'تحليل عمليات GitHub Actions الفاشلة (Pro).',
    'تحلیل اجراهای ناموفق GitHub Actions (Pro).',
    'Başarısız GitHub Actions çalıştırmalarını analiz edin (Pro).',
    '실패한 GitHub Actions 실행 분석 (Pro).',
    'วิเคราะห์การรัน GitHub Actions ที่ล้มเหลว (Pro)',
    'GitHub Actions ပျက်ကွက်မှုများ ခွဲခြမ်းစိတ်ဖြာပါ (Pro)။',
    'Амжилтгүй GitHub Actions гүйлтүүдийг шинжлэх (Pro).',
    '',
    'Analizuj nieudane uruchomienia GitHub Actions (Pro).');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_cachehint_desc',
    'Display cache hint information for the current project.',
    'Mostrar información de sugerencias de caché para el proyecto actual.',
    'Cache-Hinweis-Informationen für das aktuelle Projekt anzeigen.',
    '显示当前项目的缓存提示信息。',
    'Afficher les informations d''indice de cache pour le projet en cours.',
    'Exibir informações de dicas de cache para o projeto atual.',
    '現在のプロジェクトのキャッシュヒント情報を表示します。',
    'Hiển thị thông tin gợi ý bộ nhớ đệm cho dự án hiện tại.',
    'Cache-hintinformatie weergeven voor het huidige project.',
    'Gyorsítótár-tipp információk megjelenítése az aktuális projekthez.',
    'عرض معلومات تلميحات ذاكرة التخزين المؤقت للمشروع الحالي.',
    'نمایش اطلاعات راهنمای حافظه پنهان برای پروژه فعلی.',
    'Geçerli proje için önbellek ipucu bilgilerini görüntüleyin.',
    '현재 프로젝트의 캐시 힌트 정보를 표시합니다.',
    'แสดงข้อมูลคำแนะนำแคชสำหรับโปรเจกต์ปัจจุบัน',
    'လက်ရှိ ပရောဂျက်အတွက် cache hint သတင်းအချက်အလက် ပြသပါ။',
    'Одоогийн төслийн кэш зөвлөмжийг харуулах.',
    '',
    'Wyświetl informacje o wskazówkach pamięci podręcznej dla bieżącego projektu.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_trial_desc',
    'Start a Pro trial.',
    'Iniciar una prueba Pro.',
    'Eine Pro-Testversion starten.',
    '开始Pro试用。',
    'Démarrer un essai Pro.',
    'Iniciar um teste Pro.',
    'Proトライアルを開始します。',
    'Bắt đầu dùng thử Pro.',
    'Een Pro-proefperiode starten.',
    'Pro próbaverzió indítása.',
    'بدء تجربة Pro.',
    'شروع آزمایشی Pro.',
    'Bir Pro deneme sürümü başlatın.',
    'Pro 체험판을 시작합니다.',
    'เริ่มทดลองใช้ Pro',
    'Pro အစမ်းသုံးမှု စတင်ပါ။',
    'Pro туршилт эхлүүлэх.',
    '',
    'Rozpocznij okres próbny Pro.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('cmd_nushell_desc',
    'Launch a Nushell session with PRECC integration.',
    'Iniciar una sesión Nushell con integración PRECC.',
    'Eine Nushell-Sitzung mit PRECC-Integration starten.',
    '启动带有PRECC集成的Nushell会话。',
    'Lancer une session Nushell avec intégration PRECC.',
    'Iniciar uma sessão Nushell com integração PRECC.',
    'PRECC統合のNushellセッションを起動します。',
    'Khởi chạy phiên Nushell với tích hợp PRECC.',
    'Een Nushell-sessie starten met PRECC-integratie.',
    'Nushell munkamenet indítása PRECC integrációval.',
    'تشغيل جلسة Nushell مع تكامل PRECC.',
    'راه‌اندازی یک جلسه Nushell با ادغام PRECC.',
    'PRECC entegrasyonu ile bir Nushell oturumu başlatın.',
    'PRECC 통합으로 Nushell 세션을 시작합니다.',
    'เปิดเซสชัน Nushell พร้อมการรวม PRECC',
    'PRECC ပေါင်းစပ်ထားသော Nushell session စတင်ပါ။',
    'PRECC интеграцтай Nushell сесс эхлүүлэх.',
    '',
    'Uruchom sesję Nushell z integracją PRECC.');
