-- Skills chapter strings
-- Languages: en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_title',
    'Skills',
    'Habilidades',
    'Skills',
    '技能',
    'Compétences',
    'Habilidades',
    'スキル',
    'Kỹ năng',
    'Vaardigheden',
    'Képességek',
    'المهارات',
    'مهارت‌ها',
    'Beceriler',
    '스킬',
    'ทักษะ',
    'ကျွမ်းကျင်မှုများ',
    'Ур чадвар',
    '',
    'Umiejętności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_intro',
    'Skills are the pattern-matching rules that PRECC uses to detect and correct commands. They can be built-in (shipped as TOML files) or mined from session logs.',
    'Las habilidades son las reglas de coincidencia de patrones que PRECC usa para detectar y corregir comandos. Pueden ser integradas (distribuidas como archivos TOML) o extraídas de registros de sesión.',
    'Skills sind die Mustererkennungsregeln, die PRECC verwendet, um Befehle zu erkennen und zu korrigieren. Sie können eingebaut (als TOML-Dateien mitgeliefert) oder aus Sitzungsprotokollen gewonnen werden.',
    '技能是PRECC用来检测和纠正命令的模式匹配规则。它们可以是内置的（作为TOML文件分发）或从会话日志中挖掘的。',
    'Les compétences sont les règles de correspondance de motifs que PRECC utilise pour détecter et corriger les commandes. Elles peuvent être intégrées (livrées en fichiers TOML) ou extraites des journaux de session.',
    'Habilidades são as regras de correspondência de padrões que PRECC usa para detectar e corrigir comandos. Podem ser integradas (distribuídas como arquivos TOML) ou extraídas de logs de sessão.',
    'スキルは、PRECCがコマンドを検出して修正するために使用するパターンマッチングルールです。組み込み（TOMLファイルとして配布）またはセッションログからマイニングされます。',
    'Kỹ năng là các quy tắc khớp mẫu mà PRECC sử dụng để phát hiện và sửa lệnh. Chúng có thể là tích hợp sẵn (phân phối dưới dạng tệp TOML) hoặc khai thác từ nhật ký phiên.',
    'Vaardigheden zijn de patroonherkennungsregels die PRECC gebruikt om commando''s te detecteren en te corrigeren. Ze kunnen ingebouwd (meegeleverd als TOML-bestanden) of gedolven uit sessielogs zijn.',
    'A képességek azok a mintaillesztési szabályok, amelyeket a PRECC használ a parancsok észlelésére és javítására. Lehetnek beépítettek (TOML fájlokként szállítva) vagy munkamenet-naplókból bányászottak.',
    'المهارات هي قواعد مطابقة الأنماط التي يستخدمها PRECC لاكتشاف الأوامر وتصحيحها. يمكن أن تكون مدمجة (موزعة كملفات TOML) أو مستخرجة من سجلات الجلسات.',
    'مهارت‌ها قوانین تطبیق الگو هستند که PRECC برای شناسایی و اصلاح دستورات استفاده می‌کند. آن‌ها می‌توانند داخلی (به صورت فایل‌های TOML) یا استخراج‌شده از لاگ‌های جلسه باشند.',
    'Beceriler, PRECC''nin komutları tespit etmek ve düzeltmek için kullandığı desen eşleme kurallarıdır. Yerleşik (TOML dosyaları olarak dağıtılan) veya oturum günlüklerinden çıkarılmış olabilirler.',
    '스킬은 PRECC가 명령어를 감지하고 수정하는 데 사용하는 패턴 매칭 규칙입니다. 내장(TOML 파일로 배포) 또는 세션 로그에서 마이닝될 수 있습니다.',
    'ทักษะคือกฎการจับคู่รูปแบบที่ PRECC ใช้เพื่อตรวจจับและแก้ไขคำสั่ง สามารถเป็นแบบในตัว (จัดส่งเป็นไฟล์ TOML) หรือขุดจากบันทึกเซสชัน',
    'ကျွမ်းကျင်မှုများသည် PRECC က command များကိုရှာဖွေပြင်ဆင်ရန်အသုံးပြုသော ပုံစံတိုက်ဆိုင်စစ်ဆေးခြင်းစည်းမျဉ်းများဖြစ်သည်။',
    'Ур чадвар нь PRECC-ийн тушаалуудыг илрүүлж засахад ашигладаг хэв маягийн тааруулалтын дүрмүүд юм.',
    '',
    'Umiejętności to reguły dopasowywania wzorców, których PRECC używa do wykrywania i poprawiania poleceń. Mogą być wbudowane (dostarczane jako pliki TOML) lub wydobyte z logów sesji.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_builtin_title',
    'Built-in Skills',
    'Habilidades integradas',
    'Eingebaute Skills',
    '内置技能',
    'Compétences intégrées',
    'Habilidades integradas',
    '組み込みスキル',
    'Kỹ năng tích hợp',
    'Ingebouwde vaardigheden',
    'Beépített képességek',
    'المهارات المدمجة',
    'مهارت‌های داخلی',
    'Yerleşik beceriler',
    '내장 스킬',
    'ทักษะในตัว',
    'ပါဝင်သော ကျွမ်းကျင်မှုများ',
    'Суурилуулсан ур чадвар',
    '',
    'Wbudowane umiejętności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_col_skill',
    'Skill',
    'Habilidad',
    'Skill',
    '技能',
    'Compétence',
    'Habilidade',
    'スキル',
    'Kỹ năng',
    'Vaardigheid',
    'Képesség',
    'المهارة',
    'مهارت',
    'Beceri',
    '스킬',
    'ทักษะ',
    'ကျွမ်းကျင်မှု',
    'Ур чадвар',
    '',
    'Umiejętność');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_col_triggers',
    'Triggers On',
    'Se activa con',
    'Auslöser',
    '触发条件',
    'Déclencheur',
    'Acionado por',
    'トリガー条件',
    'Kích hoạt khi',
    'Activeert bij',
    'Aktiválódik',
    'يُفعَّل عند',
    'فعال‌سازی',
    'Tetikleyici',
    '트리거 조건',
    'ทริกเกอร์เมื่อ',
    'အစပျိုးခြင်း',
    'Идэвхжүүлэгч',
    '',
    'Wyzwalacz');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_col_action',
    'Action',
    'Acción',
    'Aktion',
    '动作',
    'Action',
    'Ação',
    'アクション',
    'Hành động',
    'Actie',
    'Művelet',
    'الإجراء',
    'عملکرد',
    'Eylem',
    '동작',
    'การดำเนินการ',
    'လုပ်ဆောင်ချက်',
    'Үйлдэл',
    '',
    'Akcja');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_cargo_trigger',
    '`cargo build/test/clippy` outside a Rust project',
    '`cargo build/test/clippy` fuera de un proyecto Rust',
    '`cargo build/test/clippy` außerhalb eines Rust-Projekts',
    '在Rust项目外运行 `cargo build/test/clippy`',
    '`cargo build/test/clippy` en dehors d''un projet Rust',
    '`cargo build/test/clippy` fora de um projeto Rust',
    'Rustプロジェクト外での `cargo build/test/clippy`',
    '`cargo build/test/clippy` ngoài dự án Rust',
    '`cargo build/test/clippy` buiten een Rust-project',
    '`cargo build/test/clippy` Rust projekten kívül',
    '`cargo build/test/clippy` خارج مشروع Rust',
    '`cargo build/test/clippy` خارج از پروژه Rust',
    'Rust projesi dışında `cargo build/test/clippy`',
    'Rust 프로젝트 외부에서 `cargo build/test/clippy`',
    '`cargo build/test/clippy` นอกโปรเจกต์ Rust',
    'Rust ပရောဂျက်ပြင်ပတွင် `cargo build/test/clippy`',
    'Rust төслөөс гадуур `cargo build/test/clippy`',
    '',
    '`cargo build/test/clippy` poza projektem Rust');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_cargo_action',
    'Prepend `cd` to the nearest `Cargo.toml` directory',
    'Anteponer `cd` al directorio del `Cargo.toml` más cercano',
    '`cd` zum nächsten `Cargo.toml`-Verzeichnis voranstellen',
    '在命令前添加 `cd` 到最近的 `Cargo.toml` 目录',
    'Ajouter `cd` vers le répertoire `Cargo.toml` le plus proche',
    'Adicionar `cd` para o diretório `Cargo.toml` mais próximo',
    '最も近い `Cargo.toml` ディレクトリへの `cd` を先頭に追加',
    'Thêm `cd` đến thư mục `Cargo.toml` gần nhất',
    '`cd` toevoegen naar de dichtstbijzijnde `Cargo.toml`-map',
    '`cd` hozzáfűzése a legközelebbi `Cargo.toml` könyvtárhoz',
    'إضافة `cd` إلى أقرب دليل `Cargo.toml`',
    'افزودن `cd` به نزدیک‌ترین پوشه `Cargo.toml`',
    'En yakın `Cargo.toml` dizinine `cd` ekle',
    '가장 가까운 `Cargo.toml` 디렉토리로 `cd` 추가',
    'เพิ่ม `cd` ไปยังไดเรกทอรี `Cargo.toml` ที่ใกล้ที่สุด',
    'အနီးဆုံး `Cargo.toml` လမ်းကြောင်းသို့ `cd` ထည့်ခြင်း',
    'Хамгийн ойрын `Cargo.toml` хавтас руу `cd` нэмэх',
    '',
    'Dodaj `cd` do najbliższego katalogu `Cargo.toml`');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_git_trigger',
    '`git *` outside a git repo',
    '`git *` fuera de un repositorio git',
    '`git *` außerhalb eines Git-Repos',
    '在git仓库外运行 `git *`',
    '`git *` en dehors d''un dépôt git',
    '`git *` fora de um repositório git',
    'gitリポジトリ外での `git *`',
    '`git *` ngoài kho git',
    '`git *` buiten een git-repo',
    '`git *` git tárolón kívül',
    '`git *` خارج مستودع git',
    '`git *` خارج از مخزن git',
    'git deposu dışında `git *`',
    'git 저장소 외부에서 `git *`',
    '`git *` นอกรีโพ git',
    'git repo ပြင်ပတွင် `git *`',
    'git repo-оос гадуур `git *`',
    '',
    '`git *` poza repozytorium git');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_git_action',
    'Prepend `cd` to the nearest `.git` directory',
    'Anteponer `cd` al directorio `.git` más cercano',
    '`cd` zum nächsten `.git`-Verzeichnis voranstellen',
    '在命令前添加 `cd` 到最近的 `.git` 目录',
    'Ajouter `cd` vers le répertoire `.git` le plus proche',
    'Adicionar `cd` para o diretório `.git` mais próximo',
    '最も近い `.git` ディレクトリへの `cd` を先頭に追加',
    'Thêm `cd` đến thư mục `.git` gần nhất',
    '`cd` toevoegen naar de dichtstbijzijnde `.git`-map',
    '`cd` hozzáfűzése a legközelebbi `.git` könyvtárhoz',
    'إضافة `cd` إلى أقرب دليل `.git`',
    'افزودن `cd` به نزدیک‌ترین پوشه `.git`',
    'En yakın `.git` dizinine `cd` ekle',
    '가장 가까운 `.git` 디렉토리로 `cd` 추가',
    'เพิ่ม `cd` ไปยังไดเรกทอรี `.git` ที่ใกล้ที่สุด',
    'အနီးဆုံး `.git` လမ်းကြောင်းသို့ `cd` ထည့်ခြင်း',
    'Хамгийн ойрын `.git` хавтас руу `cd` нэмэх',
    '',
    'Dodaj `cd` do najbliższego katalogu `.git`');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_go_trigger',
    '`go build/test` outside a Go module',
    '`go build/test` fuera de un módulo Go',
    '`go build/test` außerhalb eines Go-Moduls',
    '在Go模块外运行 `go build/test`',
    '`go build/test` en dehors d''un module Go',
    '`go build/test` fora de um módulo Go',
    'Goモジュール外での `go build/test`',
    '`go build/test` ngoài module Go',
    '`go build/test` buiten een Go-module',
    '`go build/test` Go modulon kívül',
    '`go build/test` خارج وحدة Go',
    '`go build/test` خارج از ماژول Go',
    'Go modülü dışında `go build/test`',
    'Go 모듈 외부에서 `go build/test`',
    '`go build/test` นอกโมดูล Go',
    'Go module ပြင်ပတွင် `go build/test`',
    'Go модулиас гадуур `go build/test`',
    '',
    '`go build/test` poza modułem Go');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_go_action',
    'Prepend `cd` to the nearest `go.mod` directory',
    'Anteponer `cd` al directorio del `go.mod` más cercano',
    '`cd` zum nächsten `go.mod`-Verzeichnis voranstellen',
    '在命令前添加 `cd` 到最近的 `go.mod` 目录',
    'Ajouter `cd` vers le répertoire `go.mod` le plus proche',
    'Adicionar `cd` para o diretório `go.mod` mais próximo',
    '最も近い `go.mod` ディレクトリへの `cd` を先頭に追加',
    'Thêm `cd` đến thư mục `go.mod` gần nhất',
    '`cd` toevoegen naar de dichtstbijzijnde `go.mod`-map',
    '`cd` hozzáfűzése a legközelebbi `go.mod` könyvtárhoz',
    'إضافة `cd` إلى أقرب دليل `go.mod`',
    'افزودن `cd` به نزدیک‌ترین پوشه `go.mod`',
    'En yakın `go.mod` dizinine `cd` ekle',
    '가장 가까운 `go.mod` 디렉토리로 `cd` 추가',
    'เพิ่ม `cd` ไปยังไดเรกทอรี `go.mod` ที่ใกล้ที่สุด',
    'အနီးဆုံး `go.mod` လမ်းကြောင်းသို့ `cd` ထည့်ခြင်း',
    'Хамгийн ойрын `go.mod` хавтас руу `cd` нэмэх',
    '',
    'Dodaj `cd` do najbliższego katalogu `go.mod`');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_make_trigger',
    '`make` without a Makefile in cwd',
    '`make` sin un Makefile en el directorio actual',
    '`make` ohne Makefile im aktuellen Verzeichnis',
    '当前目录没有Makefile时运行 `make`',
    '`make` sans Makefile dans le répertoire courant',
    '`make` sem Makefile no diretório atual',
    'カレントディレクトリにMakefileがない状態での `make`',
    '`make` khi không có Makefile trong thư mục hiện tại',
    '`make` zonder Makefile in de huidige map',
    '`make` Makefile nélkül az aktuális könyvtárban',
    '`make` بدون Makefile في الدليل الحالي',
    '`make` بدون Makefile در پوشه فعلی',
    'Geçerli dizinde Makefile olmadan `make`',
    '현재 디렉토리에 Makefile 없이 `make`',
    '`make` โดยไม่มี Makefile ในไดเรกทอรีปัจจุบัน',
    'လက်ရှိလမ်းကြောင်းတွင် Makefile မရှိဘဲ `make`',
    'Одоогийн хавтаст Makefile байхгүй үед `make`',
    '',
    '`make` bez Makefile w bieżącym katalogu');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_make_action',
    'Prepend `cd` to the nearest Makefile directory',
    'Anteponer `cd` al directorio del Makefile más cercano',
    '`cd` zum nächsten Makefile-Verzeichnis voranstellen',
    '在命令前添加 `cd` 到最近的Makefile目录',
    'Ajouter `cd` vers le répertoire Makefile le plus proche',
    'Adicionar `cd` para o diretório Makefile mais próximo',
    '最も近いMakefileディレクトリへの `cd` を先頭に追加',
    'Thêm `cd` đến thư mục Makefile gần nhất',
    '`cd` toevoegen naar de dichtstbijzijnde Makefile-map',
    '`cd` hozzáfűzése a legközelebbi Makefile könyvtárhoz',
    'إضافة `cd` إلى أقرب دليل Makefile',
    'افزودن `cd` به نزدیک‌ترین پوشه Makefile',
    'En yakın Makefile dizinine `cd` ekle',
    '가장 가까운 Makefile 디렉토리로 `cd` 추가',
    'เพิ่ม `cd` ไปยังไดเรกทอรี Makefile ที่ใกล้ที่สุด',
    'အနီးဆုံး Makefile လမ်းကြောင်းသို့ `cd` ထည့်ခြင်း',
    'Хамгийн ойрын Makefile хавтас руу `cd` нэмэх',
    '',
    'Dodaj `cd` do najbliższego katalogu Makefile');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_npm_trigger',
    '`npm/npx/pnpm/yarn` outside a Node project',
    '`npm/npx/pnpm/yarn` fuera de un proyecto Node',
    '`npm/npx/pnpm/yarn` außerhalb eines Node-Projekts',
    '在Node项目外运行 `npm/npx/pnpm/yarn`',
    '`npm/npx/pnpm/yarn` en dehors d''un projet Node',
    '`npm/npx/pnpm/yarn` fora de um projeto Node',
    'Nodeプロジェクト外での `npm/npx/pnpm/yarn`',
    '`npm/npx/pnpm/yarn` ngoài dự án Node',
    '`npm/npx/pnpm/yarn` buiten een Node-project',
    '`npm/npx/pnpm/yarn` Node projekten kívül',
    '`npm/npx/pnpm/yarn` خارج مشروع Node',
    '`npm/npx/pnpm/yarn` خارج از پروژه Node',
    'Node projesi dışında `npm/npx/pnpm/yarn`',
    'Node 프로젝트 외부에서 `npm/npx/pnpm/yarn`',
    '`npm/npx/pnpm/yarn` นอกโปรเจกต์ Node',
    'Node ပရောဂျက်ပြင်ပတွင် `npm/npx/pnpm/yarn`',
    'Node төслөөс гадуур `npm/npx/pnpm/yarn`',
    '',
    '`npm/npx/pnpm/yarn` poza projektem Node');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_npm_action',
    'Prepend `cd` to the nearest `package.json` directory',
    'Anteponer `cd` al directorio del `package.json` más cercano',
    '`cd` zum nächsten `package.json`-Verzeichnis voranstellen',
    '在命令前添加 `cd` 到最近的 `package.json` 目录',
    'Ajouter `cd` vers le répertoire `package.json` le plus proche',
    'Adicionar `cd` para o diretório `package.json` mais próximo',
    '最も近い `package.json` ディレクトリへの `cd` を先頭に追加',
    'Thêm `cd` đến thư mục `package.json` gần nhất',
    '`cd` toevoegen naar de dichtstbijzijnde `package.json`-map',
    '`cd` hozzáfűzése a legközelebbi `package.json` könyvtárhoz',
    'إضافة `cd` إلى أقرب دليل `package.json`',
    'افزودن `cd` به نزدیک‌ترین پوشه `package.json`',
    'En yakın `package.json` dizinine `cd` ekle',
    '가장 가까운 `package.json` 디렉토리로 `cd` 추가',
    'เพิ่ม `cd` ไปยังไดเรกทอรี `package.json` ที่ใกล้ที่สุด',
    'အနီးဆုံး `package.json` လမ်းကြောင်းသို့ `cd` ထည့်ခြင်း',
    'Хамгийн ойрын `package.json` хавтас руу `cd` нэмэх',
    '',
    'Dodaj `cd` do najbliższego katalogu `package.json`');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_python_trigger',
    '`python/pytest/pip` outside a Python project',
    '`python/pytest/pip` fuera de un proyecto Python',
    '`python/pytest/pip` außerhalb eines Python-Projekts',
    '在Python项目外运行 `python/pytest/pip`',
    '`python/pytest/pip` en dehors d''un projet Python',
    '`python/pytest/pip` fora de um projeto Python',
    'Pythonプロジェクト外での `python/pytest/pip`',
    '`python/pytest/pip` ngoài dự án Python',
    '`python/pytest/pip` buiten een Python-project',
    '`python/pytest/pip` Python projekten kívül',
    '`python/pytest/pip` خارج مشروع Python',
    '`python/pytest/pip` خارج از پروژه Python',
    'Python projesi dışında `python/pytest/pip`',
    'Python 프로젝트 외부에서 `python/pytest/pip`',
    '`python/pytest/pip` นอกโปรเจกต์ Python',
    'Python ပရောဂျက်ပြင်ပတွင် `python/pytest/pip`',
    'Python төслөөс гадуур `python/pytest/pip`',
    '',
    '`python/pytest/pip` poza projektem Python');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_python_action',
    'Prepend `cd` to the nearest Python project',
    'Anteponer `cd` al proyecto Python más cercano',
    '`cd` zum nächsten Python-Projekt voranstellen',
    '在命令前添加 `cd` 到最近的Python项目',
    'Ajouter `cd` vers le projet Python le plus proche',
    'Adicionar `cd` para o projeto Python mais próximo',
    '最も近いPythonプロジェクトへの `cd` を先頭に追加',
    'Thêm `cd` đến dự án Python gần nhất',
    '`cd` toevoegen naar het dichtstbijzijnde Python-project',
    '`cd` hozzáfűzése a legközelebbi Python projekthez',
    'إضافة `cd` إلى أقرب مشروع Python',
    'افزودن `cd` به نزدیک‌ترین پروژه Python',
    'En yakın Python projesine `cd` ekle',
    '가장 가까운 Python 프로젝트로 `cd` 추가',
    'เพิ่ม `cd` ไปยังโปรเจกต์ Python ที่ใกล้ที่สุด',
    'အနီးဆုံး Python ပရောဂျက်သို့ `cd` ထည့်ခြင်း',
    'Хамгийн ойрын Python төсөл рүү `cd` нэмэх',
    '',
    'Dodaj `cd` do najbliższego projektu Python');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_jj_trigger',
    '`git *` in a jj-colocated repo',
    '`git *` en un repositorio jj-colocado',
    '`git *` in einem jj-kolokierten Repo',
    '在jj共存仓库中运行 `git *`',
    '`git *` dans un dépôt jj colocalisé',
    '`git *` em um repositório jj co-localizado',
    'jj共存リポジトリでの `git *`',
    '`git *` trong kho jj đồng vị trí',
    '`git *` in een jj-gecoloceerde repo',
    '`git *` jj-kolokált tárolóban',
    '`git *` في مستودع jj مشترك',
    '`git *` در مخزن jj هم‌مکان',
    'jj birlikte yerleşimli depoda `git *`',
    'jj 공존 저장소에서 `git *`',
    '`git *` ในรีโพ jj ที่อยู่ร่วมกัน',
    'jj-colocated repo တွင် `git *`',
    'jj-colocated repo дахь `git *`',
    '',
    '`git *` w repozytorium jj-colocated');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_jj_action',
    'Rewrite to equivalent `jj` command',
    'Reescribir al comando `jj` equivalente',
    'Umschreiben zum äquivalenten `jj`-Befehl',
    '重写为等效的 `jj` 命令',
    'Réécrire en commande `jj` équivalente',
    'Reescrever para o comando `jj` equivalente',
    '同等の `jj` コマンドに書き換え',
    'Viết lại thành lệnh `jj` tương đương',
    'Herschrijven naar equivalent `jj`-commando',
    'Átírás egyenértékű `jj` parancsra',
    'إعادة الكتابة إلى أمر `jj` المكافئ',
    'بازنویسی به دستور `jj` معادل',
    'Eşdeğer `jj` komutuna yeniden yaz',
    '동등한 `jj` 명령어로 재작성',
    'เขียนใหม่เป็นคำสั่ง `jj` ที่เทียบเท่า',
    'ညီမျှသော `jj` command သို့ ပြန်ရေးခြင်း',
    'Адил `jj` тушаал руу дахин бичих',
    '',
    'Przepisz na równoważne polecenie `jj`');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_asciinema_trigger',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '`asciinema rec`',
    '',
    '`asciinema rec`');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_asciinema_action',
    'Rewrite to `precc gif`',
    'Reescribir a `precc gif`',
    'Umschreiben zu `precc gif`',
    '重写为 `precc gif`',
    'Réécrire en `precc gif`',
    'Reescrever para `precc gif`',
    '`precc gif` に書き換え',
    'Viết lại thành `precc gif`',
    'Herschrijven naar `precc gif`',
    'Átírás `precc gif` parancsra',
    'إعادة الكتابة إلى `precc gif`',
    'بازنویسی به `precc gif`',
    '`precc gif` olarak yeniden yaz',
    '`precc gif`로 재작성',
    'เขียนใหม่เป็น `precc gif`',
    '`precc gif` သို့ ပြန်ရေးခြင်း',
    '`precc gif` руу дахин бичих',
    '',
    'Przepisz na `precc gif`');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_listing_title',
    'Listing Skills',
    'Listar habilidades',
    'Skills auflisten',
    '列出技能',
    'Lister les compétences',
    'Listar habilidades',
    'スキルの一覧表示',
    'Liệt kê kỹ năng',
    'Vaardigheden weergeven',
    'Képességek listázása',
    'قائمة المهارات',
    'فهرست مهارت‌ها',
    'Becerileri listeleme',
    '스킬 목록',
    'แสดงรายการทักษะ',
    'ကျွမ်းကျင်မှုများစာရင်း',
    'Ур чадваруудын жагсаалт',
    '',
    'Listowanie umiejętności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_showing_title',
    'Showing Skill Details',
    'Mostrar detalles de la habilidad',
    'Skill-Details anzeigen',
    '显示技能详情',
    'Afficher les détails d''une compétence',
    'Mostrar detalhes da habilidade',
    'スキルの詳細表示',
    'Hiển thị chi tiết kỹ năng',
    'Vaardigheiddetails weergeven',
    'Képesség részleteinek megjelenítése',
    'عرض تفاصيل المهارة',
    'نمایش جزئیات مهارت',
    'Beceri ayrıntılarını göster',
    '스킬 세부 정보 표시',
    'แสดงรายละเอียดทักษะ',
    'ကျွမ်းကျင်မှုအသေးစိတ်ပြသခြင်း',
    'Ур чадварын дэлгэрэнгүйг харуулах',
    '',
    'Wyświetlanie szczegółów umiejętności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_exporting_title',
    'Exporting a Skill to TOML',
    'Exportar una habilidad a TOML',
    'Einen Skill nach TOML exportieren',
    '将技能导出为TOML',
    'Exporter une compétence en TOML',
    'Exportar uma habilidade para TOML',
    'スキルをTOMLにエクスポート',
    'Xuất kỹ năng sang TOML',
    'Een vaardigheid exporteren naar TOML',
    'Képesség exportálása TOML-ba',
    'تصدير مهارة إلى TOML',
    'صادرکردن مهارت به TOML',
    'Bir beceriyi TOML''a dışa aktar',
    '스킬을 TOML로 내보내기',
    'ส่งออกทักษะเป็น TOML',
    'ကျွမ်းကျင်မှုကို TOML သို့ တင်ပို့ခြင်း',
    'Ур чадварыг TOML руу экспортлох',
    '',
    'Eksportowanie umiejętności do TOML');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_editing_title',
    'Editing a Skill',
    'Editar una habilidad',
    'Einen Skill bearbeiten',
    '编辑技能',
    'Modifier une compétence',
    'Editar uma habilidade',
    'スキルの編集',
    'Chỉnh sửa kỹ năng',
    'Een vaardigheid bewerken',
    'Képesség szerkesztése',
    'تحرير مهارة',
    'ویرایش مهارت',
    'Bir beceriyi düzenle',
    '스킬 편집',
    'แก้ไขทักษะ',
    'ကျွမ်းကျင်မှုကိုတည်းဖြတ်ခြင်း',
    'Ур чадварыг засварлах',
    '',
    'Edycja umiejętności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_editing_body',
    'This opens the skill definition in your `$EDITOR`. After saving, the skill is reloaded automatically.',
    'Esto abre la definición de la habilidad en tu `$EDITOR`. Después de guardar, la habilidad se recarga automáticamente.',
    'Dies öffnet die Skill-Definition in Ihrem `$EDITOR`. Nach dem Speichern wird der Skill automatisch neu geladen.',
    '这将在您的 `$EDITOR` 中打开技能定义。保存后，技能会自动重新加载。',
    'Cela ouvre la définition de la compétence dans votre `$EDITOR`. Après sauvegarde, la compétence est rechargée automatiquement.',
    'Isso abre a definição da habilidade no seu `$EDITOR`. Após salvar, a habilidade é recarregada automaticamente.',
    'これにより、`$EDITOR` でスキル定義が開きます。保存後、スキルは自動的にリロードされます。',
    'Thao tác này mở định nghĩa kỹ năng trong `$EDITOR` của bạn. Sau khi lưu, kỹ năng được tải lại tự động.',
    'Dit opent de vaardigheidsdefinitie in uw `$EDITOR`. Na opslaan wordt de vaardigheid automatisch herladen.',
    'Ez megnyitja a képesség definícióját a `$EDITOR`-ban. Mentés után a képesség automatikusan újratöltődik.',
    'يفتح هذا تعريف المهارة في `$EDITOR` الخاص بك. بعد الحفظ، يتم إعادة تحميل المهارة تلقائيًا.',
    'این تعریف مهارت را در `$EDITOR` شما باز می‌کند. پس از ذخیره، مهارت به طور خودکار بارگذاری مجدد می‌شود.',
    'Bu, beceri tanımını `$EDITOR`''ınızda açar. Kaydettikten sonra beceri otomatik olarak yeniden yüklenir.',
    '이 명령은 `$EDITOR`에서 스킬 정의를 엽니다. 저장 후 스킬이 자동으로 다시 로드됩니다.',
    'คำสั่งนี้เปิดคำจำกัดความทักษะใน `$EDITOR` ของคุณ หลังจากบันทึก ทักษะจะถูกโหลดใหม่โดยอัตโนมัติ',
    'ဤအရာသည် သင်၏ `$EDITOR` တွင် ကျွမ်းကျင်မှုအဓိပ္ပာယ်ဖွင့်ဆိုချက်ကိုဖွင့်သည်။ သိမ်းဆည်းပြီးနောက် ကျွမ်းကျင်မှုကို အလိုအလျောက် ပြန်လည်ဖွင့်သည်။',
    'Энэ нь `$EDITOR` дотор ур чадварын тодорхойлолтыг нээнэ. Хадгалсны дараа ур чадвар автоматаар дахин ачаалагдана.',
    '',
    'Otwiera definicję umiejętności w twoim `$EDITOR`. Po zapisaniu umiejętność jest automatycznie przeładowywana.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_advise_title',
    'The Advise Command',
    'El comando Advise',
    'Der Advise-Befehl',
    'Advise 命令',
    'La commande Advise',
    'O comando Advise',
    'Advise コマンド',
    'Lệnh Advise',
    'Het Advise-commando',
    'Az Advise parancs',
    'أمر Advise',
    'دستور Advise',
    'Advise komutu',
    'Advise 명령어',
    'คำสั่ง Advise',
    'Advise command',
    'Advise тушаал',
    '',
    'Polecenie Advise');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_advise_body',
    '`precc skills advise` analyzes your recent session and suggests new skills based on repeated patterns:',
    '`precc skills advise` analiza tu sesión reciente y sugiere nuevas habilidades basadas en patrones repetidos:',
    '`precc skills advise` analysiert Ihre letzte Sitzung und schlägt neue Skills basierend auf wiederkehrenden Mustern vor:',
    '`precc skills advise` 分析您最近的会话，并根据重复模式建议新技能：',
    '`precc skills advise` analyse votre session récente et suggère de nouvelles compétences basées sur des motifs répétés :',
    '`precc skills advise` analisa sua sessão recente e sugere novas habilidades baseadas em padrões repetidos:',
    '`precc skills advise` は最近のセッションを分析し、繰り返しパターンに基づいて新しいスキルを提案します：',
    '`precc skills advise` phân tích phiên gần đây của bạn và đề xuất kỹ năng mới dựa trên các mẫu lặp lại:',
    '`precc skills advise` analyseert uw recente sessie en suggereert nieuwe vaardigheden op basis van herhaalde patronen:',
    'A `precc skills advise` elemzi a legutóbbi munkamenetet és új képességeket javasol ismétlődő minták alapján:',
    'يقوم `precc skills advise` بتحليل جلستك الأخيرة ويقترح مهارات جديدة بناءً على الأنماط المتكررة:',
    '`precc skills advise` جلسه اخیر شما را تحلیل می‌کند و مهارت‌های جدید را بر اساس الگوهای تکراری پیشنهاد می‌دهد:',
    '`precc skills advise` son oturumunuzu analiz eder ve tekrarlanan kalıplara dayalı yeni beceriler önerir:',
    '`precc skills advise`는 최근 세션을 분석하고 반복 패턴을 기반으로 새로운 스킬을 제안합니다:',
    '`precc skills advise` วิเคราะห์เซสชันล่าสุดของคุณและแนะนำทักษะใหม่ตามรูปแบบที่ซ้ำกัน:',
    '`precc skills advise` သည် သင်၏လတ်တလောစက်ရှင်ကိုခွဲခြမ်းစိတ်ဖြာပြီး ထပ်ခါထပ်ခါပုံစံများအပေါ်အခြေခံ၍ ကျွမ်းကျင်မှုအသစ်များအကြံပြုသည်။',
    '`precc skills advise` таны сүүлийн сессийг шинжилж, давтагдсан хэв маягт үндэслэн шинэ ур чадвар санал болгоно:',
    '',
    '`precc skills advise` analizuje ostatnią sesję i sugeruje nowe umiejętności na podstawie powtarzających się wzorców:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_clustering_title',
    'Clustering Skills',
    'Agrupar habilidades',
    'Skills gruppieren',
    '聚类技能',
    'Regrouper les compétences',
    'Agrupar habilidades',
    'スキルのクラスタリング',
    'Gom nhóm kỹ năng',
    'Vaardigheden groeperen',
    'Képességek csoportosítása',
    'تجميع المهارات',
    'خوشه‌بندی مهارت‌ها',
    'Becerileri kümeleme',
    '스킬 클러스터링',
    'การจัดกลุ่มทักษะ',
    'ကျွမ်းကျင်မှုအုပ်စုဖွဲ့ခြင်း',
    'Ур чадваруудыг бүлэглэх',
    '',
    'Grupowanie umiejętności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_clustering_body',
    'Groups similar mined skills together to help identify redundant or overlapping patterns.',
    'Agrupa habilidades extraídas similares para ayudar a identificar patrones redundantes o superpuestos.',
    'Gruppiert ähnliche geminte Skills, um redundante oder überlappende Muster zu identifizieren.',
    '将相似的挖掘技能分组，帮助识别冗余或重叠的模式。',
    'Regroupe les compétences extraites similaires pour aider à identifier les motifs redondants ou chevauchants.',
    'Agrupa habilidades mineradas semelhantes para ajudar a identificar padrões redundantes ou sobrepostos.',
    '類似するマイニングされたスキルをグループ化し、冗長または重複するパターンの特定を支援します。',
    'Nhóm các kỹ năng khai thác tương tự lại với nhau để giúp xác định các mẫu trùng lặp hoặc chồng chéo.',
    'Groepeert vergelijkbare gedolven vaardigheden om redundante of overlappende patronen te identificeren.',
    'Csoportosítja a hasonló bányászott képességeket a redundáns vagy átfedő minták azonosításához.',
    'يجمع المهارات المستخرجة المتشابهة معًا للمساعدة في تحديد الأنماط المتكررة أو المتداخلة.',
    'مهارت‌های استخراج‌شده مشابه را گروه‌بندی می‌کند تا الگوهای تکراری یا هم‌پوشان را شناسایی کند.',
    'Gereksiz veya örtüşen kalıpları belirlemeye yardımcı olmak için benzer çıkarılmış becerileri gruplar.',
    '유사한 마이닝된 스킬을 그룹화하여 중복되거나 겹치는 패턴을 식별하는 데 도움을 줍니다.',
    'จัดกลุ่มทักษะที่ขุดได้ที่คล้ายกันเพื่อช่วยระบุรูปแบบที่ซ้ำซ้อนหรือทับซ้อนกัน',
    'ထပ်နေသောပုံစံများကိုသိရှိရန် ဆင်တူသောကျွမ်းကျင်မှုများကိုအုပ်စုဖွဲ့သည်။',
    'Давхцаж буй хэв маягийг тодорхойлоход туслахын тулд ижил төстэй ур чадваруудыг бүлэглэнэ.',
    '',
    'Grupuje podobne wydobyte umiejętności w celu identyfikacji redundantnych lub nakładających się wzorców.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_mined_vs_builtin_title',
    'Mined vs. Built-in Skills',
    'Habilidades extraídas vs. integradas',
    'Geminte vs. eingebaute Skills',
    '挖掘技能与内置技能',
    'Compétences extraites vs. intégrées',
    'Habilidades mineradas vs. integradas',
    'マイニングスキルと組み込みスキル',
    'Kỹ năng khai thác và kỹ năng tích hợp',
    'Gedolven vs. ingebouwde vaardigheden',
    'Bányászott és beépített képességek',
    'المهارات المستخرجة مقابل المدمجة',
    'مهارت‌های استخراج‌شده در مقابل داخلی',
    'Çıkarılmış ve yerleşik beceriler',
    '마이닝 스킬 vs. 내장 스킬',
    'ทักษะที่ขุดได้เทียบกับทักษะในตัว',
    'တူးဖော်ရရှိသောနှင့်ပါဝင်သောကျွမ်းကျင်မှုများ',
    'Олборлосон ба суурилуулсан ур чадвар',
    '',
    'Wydobyte a wbudowane umiejętności');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('sk_mined_vs_builtin_body',
    'Built-in skills ship with PRECC and are defined in `skills/builtin/*.toml`. They cover the most common wrong-directory mistakes.

Mined skills are created by `precc ingest` or the `precc-learner` daemon from your session logs. They are stored in `~/.local/share/precc/heuristics.db` and are specific to your workflow. See [Mining](mining.md) for details.',
    'Las habilidades integradas se distribuyen con PRECC y están definidas en `skills/builtin/*.toml`. Cubren los errores de directorio incorrecto más comunes.

Las habilidades extraídas son creadas por `precc ingest` o el demonio `precc-learner` a partir de tus registros de sesión. Se almacenan en `~/.local/share/precc/heuristics.db` y son específicas de tu flujo de trabajo. Ver [Minería](mining.md) para más detalles.',
    'Eingebaute Skills werden mit PRECC geliefert und sind in `skills/builtin/*.toml` definiert. Sie decken die häufigsten Fehler bei falschen Verzeichnissen ab.

Geminte Skills werden von `precc ingest` oder dem `precc-learner`-Daemon aus Ihren Sitzungsprotokollen erstellt. Sie werden in `~/.local/share/precc/heuristics.db` gespeichert und sind spezifisch für Ihren Workflow. Siehe [Mining](mining.md) für Details.',
    '内置技能随PRECC一起分发，定义在 `skills/builtin/*.toml` 中。它们涵盖了最常见的目录错误。

挖掘技能由 `precc ingest` 或 `precc-learner` 守护进程从您的会话日志创建。它们存储在 `~/.local/share/precc/heuristics.db` 中，特定于您的工作流程。详情请参阅[挖掘](mining.md)。',
    'Les compétences intégrées sont livrées avec PRECC et définies dans `skills/builtin/*.toml`. Elles couvrent les erreurs de mauvais répertoire les plus courantes.

Les compétences extraites sont créées par `precc ingest` ou le démon `precc-learner` à partir de vos journaux de session. Elles sont stockées dans `~/.local/share/precc/heuristics.db` et sont spécifiques à votre flux de travail. Voir [Extraction](mining.md) pour les détails.',
    'Habilidades integradas são distribuídas com PRECC e definidas em `skills/builtin/*.toml`. Elas cobrem os erros de diretório incorreto mais comuns.

Habilidades mineradas são criadas por `precc ingest` ou pelo daemon `precc-learner` a partir dos seus logs de sessão. São armazenadas em `~/.local/share/precc/heuristics.db` e são específicas do seu fluxo de trabalho. Veja [Mineração](mining.md) para detalhes.',
    '組み込みスキルはPRECCに同梱され、`skills/builtin/*.toml` で定義されています。最も一般的なディレクトリ間違いをカバーします。

マイニングスキルは `precc ingest` または `precc-learner` デーモンによってセッションログから作成されます。`~/.local/share/precc/heuristics.db` に保存され、ワークフローに固有です。詳細は[マイニング](mining.md)を参照してください。',
    'Kỹ năng tích hợp được phân phối cùng PRECC và được định nghĩa trong `skills/builtin/*.toml`. Chúng bao gồm các lỗi thư mục sai phổ biến nhất.

Kỹ năng khai thác được tạo bởi `precc ingest` hoặc daemon `precc-learner` từ nhật ký phiên của bạn. Chúng được lưu trong `~/.local/share/precc/heuristics.db` và đặc thù cho quy trình làm việc của bạn. Xem [Khai thác](mining.md) để biết chi tiết.',
    'Ingebouwde vaardigheden worden meegeleverd met PRECC en zijn gedefinieerd in `skills/builtin/*.toml`. Ze dekken de meest voorkomende verkeerde-map-fouten.

Gedolven vaardigheden worden aangemaakt door `precc ingest` of de `precc-learner`-daemon uit uw sessielogs. Ze worden opgeslagen in `~/.local/share/precc/heuristics.db` en zijn specifiek voor uw workflow. Zie [Mining](mining.md) voor details.',
    'A beépített képességek a PRECC-kel érkeznek és a `skills/builtin/*.toml`-ban vannak definiálva. A leggyakoribb rossz könyvtár hibákat fedik le.

A bányászott képességek a `precc ingest` vagy a `precc-learner` démon által jönnek létre a munkamenet-naplókból. A `~/.local/share/precc/heuristics.db`-ben tárolódnak és specifikusak a munkafolyamatára. Lásd a [Bányászat](mining.md) oldalt a részletekért.',
    'المهارات المدمجة تأتي مع PRECC ومحددة في `skills/builtin/*.toml`. تغطي أكثر أخطاء الدليل الخاطئ شيوعًا.

المهارات المستخرجة يتم إنشاؤها بواسطة `precc ingest` أو خدمة `precc-learner` من سجلات جلساتك. يتم تخزينها في `~/.local/share/precc/heuristics.db` وهي خاصة بسير عملك. انظر [التعدين](mining.md) للتفاصيل.',
    'مهارت‌های داخلی همراه PRECC ارائه می‌شوند و در `skills/builtin/*.toml` تعریف شده‌اند. آن‌ها رایج‌ترین خطاهای پوشه نادرست را پوشش می‌دهند.

مهارت‌های استخراج‌شده توسط `precc ingest` یا دیمن `precc-learner` از لاگ‌های جلسه شما ایجاد می‌شوند. در `~/.local/share/precc/heuristics.db` ذخیره می‌شوند و مختص گردش کار شما هستند. برای جزئیات [استخراج](mining.md) را ببینید.',
    'Yerleşik beceriler PRECC ile birlikte gelir ve `skills/builtin/*.toml` içinde tanımlanır. En yaygın yanlış dizin hatalarını kapsar.

Çıkarılmış beceriler, oturum günlüklerinizden `precc ingest` veya `precc-learner` arka plan servisi tarafından oluşturulur. `~/.local/share/precc/heuristics.db` içinde saklanır ve iş akışınıza özgüdür. Ayrıntılar için [Madencilik](mining.md) sayfasına bakın.',
    '내장 스킬은 PRECC와 함께 제공되며 `skills/builtin/*.toml`에 정의되어 있습니다. 가장 흔한 잘못된 디렉토리 실수를 다룹니다.

마이닝된 스킬은 세션 로그에서 `precc ingest` 또는 `precc-learner` 데몬에 의해 생성됩니다. `~/.local/share/precc/heuristics.db`에 저장되며 워크플로에 특화됩니다. 자세한 내용은 [마이닝](mining.md)을 참조하세요.',
    'ทักษะในตัวมาพร้อมกับ PRECC และถูกกำหนดใน `skills/builtin/*.toml` ครอบคลุมข้อผิดพลาดไดเรกทอรีผิดที่พบบ่อยที่สุด

ทักษะที่ขุดได้ถูกสร้างโดย `precc ingest` หรือ daemon `precc-learner` จากบันทึกเซสชันของคุณ ถูกเก็บใน `~/.local/share/precc/heuristics.db` และเฉพาะเจาะจงกับเวิร์กโฟลว์ของคุณ ดู [การขุด](mining.md) สำหรับรายละเอียด',
    'ပါဝင်သောကျွမ်းကျင်မှုများသည် PRECC နှင့်အတူပါဝင်ပြီး `skills/builtin/*.toml` တွင်သတ်မှတ်ထားသည်။

တူးဖော်ရရှိသောကျွမ်းကျင်မှုများကို `precc ingest` သို့မဟုတ် `precc-learner` daemon မှဖန်တီးသည်။ `~/.local/share/precc/heuristics.db` တွင်သိမ်းဆည်းထားသည်။ အသေးစိတ်အတွက် [Mining](mining.md) ကိုကြည့်ပါ။',
    'Суурилуулсан ур чадвар нь PRECC-тэй хамт ирдэг бөгөөд `skills/builtin/*.toml`-д тодорхойлогдсон. Хамгийн түгээмэл буруу хавтасны алдааг хамардаг.

Олборлосон ур чадварыг `precc ingest` эсвэл `precc-learner` демон таны сессийн логоос үүсгэдэг. `~/.local/share/precc/heuristics.db`-д хадгалагддаг. Дэлгэрэнгүйг [Олборлолт](mining.md)-оос үзнэ үү.',
    '',
    'Wbudowane umiejętności są dostarczane z PRECC i zdefiniowane w `skills/builtin/*.toml`. Obejmują najczęstsze błędy niewłaściwego katalogu.

Wydobyte umiejętności są tworzone przez `precc ingest` lub daemon `precc-learner` z logów sesji. Są przechowywane w `~/.local/share/precc/heuristics.db` i są specyficzne dla twojego przepływu pracy. Zobacz [Wydobywanie](mining.md) po szczegóły.');
