-- Email chapter strings
INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_title',
    'Email',
    'Correo electrónico',
    'E-Mail',
    '电子邮件',
    'E-mail',
    'E-mail',
    'メール',
    'Email',
    'E-mail',
    'E-mail',
    'البريد الإلكتروني',
    'ایمیل',
    'E-posta',
    '이메일',
    'อีเมล',
    'အီးမေးလ်',
    'Имэйл',
    '',
    'E-mail');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_intro',
    'PRECC can send reports and files via email. This requires a one-time SMTP setup.',
    'PRECC puede enviar informes y archivos por correo electrónico. Esto requiere una configuración SMTP única.',
    'PRECC kann Berichte und Dateien per E-Mail senden. Dies erfordert eine einmalige SMTP-Einrichtung.',
    'PRECC可以通过电子邮件发送报告和文件。这需要一次性的SMTP设置。',
    'PRECC peut envoyer des rapports et des fichiers par e-mail. Cela nécessite une configuration SMTP unique.',
    'PRECC pode enviar relatórios e arquivos por e-mail. Isso requer uma configuração SMTP única.',
    'PRECCはメールでレポートやファイルを送信できます。これには一度だけのSMTP設定が必要です。',
    'PRECC có thể gửi báo cáo và tệp qua email. Điều này yêu cầu cấu hình SMTP một lần.',
    'PRECC kan rapporten en bestanden per e-mail verzenden. Dit vereist een eenmalige SMTP-configuratie.',
    'A PRECC e-mailben küldhet jelentéseket és fájlokat. Ehhez egyszeri SMTP-beállítás szükséges.',
    'يمكن لـ PRECC إرسال التقارير والملفات عبر البريد الإلكتروني. يتطلب هذا إعداد SMTP لمرة واحدة.',
    'PRECC می‌تواند گزارش‌ها و فایل‌ها را از طریق ایمیل ارسال کند. این نیاز به تنظیم یکباره SMTP دارد.',
    'PRECC e-posta ile raporlar ve dosyalar gönderebilir. Bu, tek seferlik bir SMTP kurulumu gerektirir.',
    'PRECC는 이메일로 보고서와 파일을 보낼 수 있습니다. 일회성 SMTP 설정이 필요합니다.',
    'PRECC สามารถส่งรายงานและไฟล์ทางอีเมลได้ ต้องตั้งค่า SMTP ครั้งเดียว',
    'PRECC သည် အီးမေးလ်ဖြင့် အစီရင်ခံစာများနှင့် ဖိုင်များ ပေးပို့နိုင်သည်။ SMTP တစ်ကြိမ်တည်း သတ်မှတ်ရန် လိုအပ်သည်။',
    'PRECC имэйлээр тайлан, файл илгээх боломжтой. Нэг удаагийн SMTP тохиргоо шаардлагатай.',
    '',
    'PRECC może wysyłać raporty i pliki e-mailem. Wymaga jednorazowej konfiguracji SMTP.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_setup_title',
    'Setup',
    'Configuración',
    'Einrichtung',
    '设置',
    'Configuration',
    'Configuração',
    'セットアップ',
    'Cài đặt',
    'Instelling',
    'Beállítás',
    'الإعداد',
    'راه‌اندازی',
    'Kurulum',
    '설정',
    'การตั้งค่า',
    'စနစ်ထည့်သွင်းခြင်း',
    'Тохиргоо',
    '',
    'Konfiguracja');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_config_title',
    'Configuration File',
    'Archivo de configuración',
    'Konfigurationsdatei',
    '配置文件',
    'Fichier de configuration',
    'Arquivo de configuração',
    '設定ファイル',
    'Tệp cấu hình',
    'Configuratiebestand',
    'Konfigurációs fájl',
    'ملف التكوين',
    'فایل پیکربندی',
    'Yapılandırma dosyası',
    '구성 파일',
    'ไฟล์การกำหนดค่า',
    'ပြင်ဆင်သတ်မှတ်ချက် ဖိုင်',
    'Тохиргооны файл',
    '',
    'Plik konfiguracyjny');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_config_body',
    'The configuration is stored at `~/.config/precc/mail.toml`:',
    'La configuración se almacena en `~/.config/precc/mail.toml`:',
    'Die Konfiguration wird unter `~/.config/precc/mail.toml` gespeichert:',
    '配置存储在 `~/.config/precc/mail.toml`：',
    'La configuration est stockée dans `~/.config/precc/mail.toml` :',
    'A configuração é armazenada em `~/.config/precc/mail.toml`:',
    '設定は `~/.config/precc/mail.toml` に保存されます：',
    'Cấu hình được lưu tại `~/.config/precc/mail.toml`:',
    'De configuratie wordt opgeslagen in `~/.config/precc/mail.toml`:',
    'A konfiguráció a `~/.config/precc/mail.toml` fájlban van tárolva:',
    'يتم تخزين التكوين في `~/.config/precc/mail.toml`:',
    'پیکربندی در `~/.config/precc/mail.toml` ذخیره می‌شود:',
    'Yapılandırma `~/.config/precc/mail.toml` dosyasında saklanır:',
    '구성은 `~/.config/precc/mail.toml`에 저장됩니다:',
    'การกำหนดค่าถูกเก็บไว้ที่ `~/.config/precc/mail.toml`:',
    'ပြင်ဆင်သတ်မှတ်ချက်ကို `~/.config/precc/mail.toml` တွင် သိမ်းဆည်းထားသည်:',
    'Тохиргоо нь `~/.config/precc/mail.toml` файлд хадгалагдана:',
    '',
    'Konfiguracja jest przechowywana w `~/.config/precc/mail.toml`:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_config_edit',
    'You can edit this file directly:',
    'Puede editar este archivo directamente:',
    'Sie können diese Datei direkt bearbeiten:',
    '您可以直接编辑此文件：',
    'Vous pouvez modifier ce fichier directement :',
    'Você pode editar este arquivo diretamente:',
    'このファイルを直接編集できます：',
    'Bạn có thể chỉnh sửa tệp này trực tiếp:',
    'U kunt dit bestand rechtstreeks bewerken:',
    'Ezt a fájlt közvetlenül szerkesztheti:',
    'يمكنك تحرير هذا الملف مباشرة:',
    'می‌توانید این فایل را مستقیماً ویرایش کنید:',
    'Bu dosyayı doğrudan düzenleyebilirsiniz:',
    '이 파일을 직접 편집할 수 있습니다:',
    'คุณสามารถแก้ไขไฟล์นี้ได้โดยตรง:',
    'ဤဖိုင်ကို တိုက်ရိုက် ပြင်ဆင်နိုင်သည်:',
    'Энэ файлыг шууд засварлах боломжтой:',
    '',
    'Możesz edytować ten plik bezpośrednio:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_gmail_note',
    'For Gmail, use an [App Password](https://support.google.com/accounts/answer/185833) rather than your account password.',
    'Para Gmail, use una [Contraseña de aplicación](https://support.google.com/accounts/answer/185833) en lugar de su contraseña de cuenta.',
    'Verwenden Sie für Gmail ein [App-Passwort](https://support.google.com/accounts/answer/185833) anstelle Ihres Kontopassworts.',
    '对于Gmail，请使用[应用密码](https://support.google.com/accounts/answer/185833)而不是您的账户密码。',
    'Pour Gmail, utilisez un [mot de passe d''application](https://support.google.com/accounts/answer/185833) plutôt que votre mot de passe de compte.',
    'Para Gmail, use uma [Senha de app](https://support.google.com/accounts/answer/185833) em vez da senha da sua conta.',
    'Gmailの場合は、アカウントパスワードではなく[アプリパスワード](https://support.google.com/accounts/answer/185833)を使用してください。',
    'Đối với Gmail, hãy sử dụng [Mật khẩu ứng dụng](https://support.google.com/accounts/answer/185833) thay vì mật khẩu tài khoản.',
    'Gebruik voor Gmail een [App-wachtwoord](https://support.google.com/accounts/answer/185833) in plaats van uw accountwachtwoord.',
    'Gmailhez használjon [Alkalmazásjelszót](https://support.google.com/accounts/answer/185833) a fiókjelszó helyett.',
    'بالنسبة لـ Gmail، استخدم [كلمة مرور التطبيق](https://support.google.com/accounts/answer/185833) بدلاً من كلمة مرور حسابك.',
    'برای Gmail، از [رمز عبور برنامه](https://support.google.com/accounts/answer/185833) به جای رمز عبور حساب خود استفاده کنید.',
    'Gmail için hesap şifreniz yerine bir [Uygulama Şifresi](https://support.google.com/accounts/answer/185833) kullanın.',
    'Gmail의 경우 계정 비밀번호 대신 [앱 비밀번호](https://support.google.com/accounts/answer/185833)를 사용하세요.',
    'สำหรับ Gmail ให้ใช้ [รหัสผ่านแอป](https://support.google.com/accounts/answer/185833) แทนรหัสผ่านบัญชี',
    'Gmail အတွက် သင့်အကောင့် စကားဝှက်အစား [App Password](https://support.google.com/accounts/answer/185833) ကို အသုံးပြုပါ။',
    'Gmail-ийн хувьд бүртгэлийн нууц үгийн оронд [App Password](https://support.google.com/accounts/answer/185833) ашиглана уу.',
    '',
    'W przypadku Gmaila użyj [Hasła aplikacji](https://support.google.com/accounts/answer/185833) zamiast hasła do konta.');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_sending_reports_title',
    'Sending Reports',
    'Envío de informes',
    'Berichte senden',
    '发送报告',
    'Envoi de rapports',
    'Enviando relatórios',
    'レポートの送信',
    'Gửi báo cáo',
    'Rapporten verzenden',
    'Jelentések küldése',
    'إرسال التقارير',
    'ارسال گزارش‌ها',
    'Rapor gönderme',
    '보고서 보내기',
    'การส่งรายงาน',
    'အစီရင်ခံစာများ ပေးပို့ခြင်း',
    'Тайлан илгээх',
    '',
    'Wysyłanie raportów');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_sending_files_title',
    'Sending Files',
    'Envío de archivos',
    'Dateien senden',
    '发送文件',
    'Envoi de fichiers',
    'Enviando arquivos',
    'ファイルの送信',
    'Gửi tệp',
    'Bestanden verzenden',
    'Fájlok küldése',
    'إرسال الملفات',
    'ارسال فایل‌ها',
    'Dosya gönderme',
    '파일 보내기',
    'การส่งไฟล์',
    'ဖိုင်များ ပေးပို့ခြင်း',
    'Файл илгээх',
    '',
    'Wysyłanie plików');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_ssh_relay_title',
    'SSH Relay Support',
    'Soporte de retransmisión SSH',
    'SSH-Relay-Unterstützung',
    'SSH中继支持',
    'Support de relais SSH',
    'Suporte a retransmissão SSH',
    'SSHリレーサポート',
    'Hỗ trợ chuyển tiếp SSH',
    'SSH-relay ondersteuning',
    'SSH-relay támogatás',
    'دعم ترحيل SSH',
    'پشتیبانی از رله SSH',
    'SSH aktarma desteği',
    'SSH 릴레이 지원',
    'การรองรับรีเลย์ SSH',
    'SSH relay ပံ့ပိုးမှု',
    'SSH relay дэмжлэг',
    '',
    'Obsługa przekaźnika SSH');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_ssh_relay_body',
    'If your machine cannot reach an SMTP server directly (e.g., behind a corporate firewall), PRECC supports relaying through an SSH tunnel:',
    'Si su máquina no puede acceder directamente a un servidor SMTP (por ejemplo, detrás de un firewall corporativo), PRECC soporta la retransmisión a través de un túnel SSH:',
    'Wenn Ihr Rechner keinen SMTP-Server direkt erreichen kann (z.B. hinter einer Firmen-Firewall), unterstützt PRECC die Weiterleitung über einen SSH-Tunnel:',
    '如果您的机器无法直接访问SMTP服务器（例如，在企业防火墙后面），PRECC支持通过SSH隧道中继：',
    'Si votre machine ne peut pas atteindre un serveur SMTP directement (par exemple, derrière un pare-feu d''entreprise), PRECC prend en charge le relais via un tunnel SSH :',
    'Se sua máquina não pode acessar um servidor SMTP diretamente (por exemplo, atrás de um firewall corporativo), PRECC suporta retransmissão via túnel SSH:',
    'マシンがSMTPサーバーに直接到達できない場合（例：企業ファイアウォールの背後）、PRECCはSSHトンネル経由のリレーをサポートします：',
    'Nếu máy của bạn không thể truy cập trực tiếp máy chủ SMTP (ví dụ: sau tường lửa công ty), PRECC hỗ trợ chuyển tiếp qua đường hầm SSH:',
    'Als uw machine geen SMTP-server rechtstreeks kan bereiken (bijv. achter een bedrijfsfirewall), ondersteunt PRECC relay via een SSH-tunnel:',
    'Ha a gépe nem éri el közvetlenül az SMTP-szervert (pl. vállalati tűzfal mögött), a PRECC támogatja az SSH-alagúton keresztüli továbbítást:',
    'إذا لم يتمكن جهازك من الوصول إلى خادم SMTP مباشرة (مثلاً خلف جدار حماية مؤسسي)، يدعم PRECC الترحيل عبر نفق SSH:',
    'اگر دستگاه شما نمی‌تواند مستقیماً به سرور SMTP دسترسی پیدا کند (مثلاً پشت فایروال شرکتی)، PRECC از رله از طریق تونل SSH پشتیبانی می‌کند:',
    'Makineniz doğrudan bir SMTP sunucusuna erişemiyorsa (örneğin, kurumsal bir güvenlik duvarı arkasında), PRECC bir SSH tüneli üzerinden aktarmayı destekler:',
    '기기가 SMTP 서버에 직접 연결할 수 없는 경우(예: 회사 방화벽 뒤), PRECC는 SSH 터널을 통한 릴레이를 지원합니다:',
    'หากเครื่องของคุณไม่สามารถเข้าถึงเซิร์ฟเวอร์ SMTP ได้โดยตรง (เช่น อยู่หลังไฟร์วอลล์ขององค์กร) PRECC รองรับการรีเลย์ผ่านอุโมงค์ SSH:',
    'သင့်စက်သည် SMTP ဆာဗာကို တိုက်ရိုက် ချိတ်ဆက်၍ မရပါက (ဥပမာ- ကုမ္ပဏီ firewall နောက်ကွယ်တွင်)၊ PRECC သည် SSH tunnel မှတစ်ဆင့် relay ပေးပို့ခြင်းကို ပံ့ပိုးသည်:',
    'Таны машин SMTP серверт шууд хүрч чадахгүй бол (жишээ нь байгууллагын firewall-ийн ард), PRECC SSH tunnel-ээр дамжуулан relay хийхийг дэмждэг:',
    '',
    'Jeśli Twoja maszyna nie może bezpośrednio połączyć się z serwerem SMTP (np. za firmowym firewallem), PRECC obsługuje przekazywanie przez tunel SSH:');

INSERT OR REPLACE INTO strings (key, en, es, de, zh, fr, pt, ja, vi, nl, hu, ar, fa, tr, ko, th, my, mn, bo, pl) VALUES
('eml_ssh_relay_auto',
    'PRECC will establish the SSH tunnel automatically before sending.',
    'PRECC establecerá el túnel SSH automáticamente antes de enviar.',
    'PRECC stellt den SSH-Tunnel vor dem Senden automatisch her.',
    'PRECC将在发送前自动建立SSH隧道。',
    'PRECC établira le tunnel SSH automatiquement avant l''envoi.',
    'PRECC estabelecerá o túnel SSH automaticamente antes de enviar.',
    'PRECCは送信前にSSHトンネルを自動的に確立します。',
    'PRECC sẽ tự động thiết lập đường hầm SSH trước khi gửi.',
    'PRECC zal de SSH-tunnel automatisch opzetten voor het verzenden.',
    'A PRECC automatikusan létrehozza az SSH-alagutat küldés előtt.',
    'سيقوم PRECC بإنشاء نفق SSH تلقائياً قبل الإرسال.',
    'PRECC قبل از ارسال به طور خودکار تونل SSH را برقرار می‌کند.',
    'PRECC göndermeden önce SSH tünelini otomatik olarak kuracaktır.',
    'PRECC는 전송 전에 SSH 터널을 자동으로 설정합니다.',
    'PRECC จะสร้างอุโมงค์ SSH โดยอัตโนมัติก่อนส่ง',
    'PRECC သည် ပေးပို့ခြင်းမပြုမီ SSH tunnel ကို အလိုအလျောက် ထူထောင်မည်ဖြစ်သည်။',
    'PRECC илгээхийн өмнө SSH tunnel-ийг автоматаар үүсгэнэ.',
    '',
    'PRECC automatycznie ustanowi tunel SSH przed wysłaniem.');
