//! Skill sharing and credit tracking.
//!
//! When a user shares a skill (exports it for team reuse), the system tracks:
//! - Who shared it (anonymous creator tag, no PII)
//! - Cumulative token savings across all adopters
//! - Credits ("earned tokens") distributed back to the creator
//!
//! Credits incentivize sharing: the more a shared skill saves for others,
//! the more tokens the creator "earns" toward their own usage.

use anyhow::{Context, Result};
use rusqlite::Connection;

/// Credit multiplier: creator earns 10% of total savings generated by their shared skills.
const CREATOR_CREDIT_RATE: f64 = 0.10;

/// Tokens saved estimate per activation (same as telemetry module).
const TOKENS_PER_ACTIVATION: f64 = 250.0;

/// A shared skill record.
#[derive(Debug)]
pub struct SharedSkill {
    pub skill_name: String,
    pub shared_at: String,
    /// Anonymous creator tag (hash of machine fingerprint + skill name).
    pub creator_tag: String,
    /// Total activations across all adopters (local only for now).
    pub total_activations: i64,
    /// Estimated total tokens saved by this shared skill.
    pub total_tokens_saved: f64,
    /// Tokens credited back to the creator.
    pub creator_credits: f64,
}

/// A summary of sharing credits for this user.
#[derive(Debug)]
pub struct CreditSummary {
    pub skills_shared: i64,
    pub total_activations: i64,
    pub total_tokens_saved: f64,
    pub total_credits_earned: f64,
}

/// Initialize the sharing tables (additive migration).
pub fn init_sharing_schema(conn: &Connection) -> Result<()> {
    // Silently ignore if tables already exist
    let _ = conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS shared_skills (
            id              INTEGER PRIMARY KEY,
            skill_id        INTEGER REFERENCES skills(id),
            skill_name      TEXT NOT NULL,
            creator_tag     TEXT NOT NULL,
            shared_at       TEXT NOT NULL,
            toml_content    TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS sharing_credits (
            id              INTEGER PRIMARY KEY,
            shared_skill_id INTEGER REFERENCES shared_skills(id),
            activations     INTEGER DEFAULT 0,
            tokens_saved    REAL DEFAULT 0.0,
            credits_earned  REAL DEFAULT 0.0,
            updated_at      TEXT NOT NULL
        );
        CREATE UNIQUE INDEX IF NOT EXISTS idx_shared_skill ON shared_skills(skill_name);",
    );
    Ok(())
}

/// Generate an anonymous creator tag from the skill name.
/// Uses machine fingerprint + skill name to create a reproducible but non-PII tag.
fn creator_tag(skill_name: &str) -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let fp = crate::license::machine_fingerprint();
    let mut hasher = DefaultHasher::new();
    fp.hash(&mut hasher);
    skill_name.hash(&mut hasher);
    format!("{:08x}", hasher.finish() & 0xFFFF_FFFF)
}

/// Record that a skill was shared (exported for team reuse).
/// Returns the TOML content that should be written/sent.
pub fn record_share(conn: &Connection, skill_name: &str, toml_content: &str) -> Result<()> {
    init_sharing_schema(conn)?;

    let tag = creator_tag(skill_name);
    let now = crate::skills::chrono_now();

    // Get skill_id
    let skill_id: Option<i64> = conn
        .query_row("SELECT id FROM skills WHERE name = ?1", [skill_name], |r| {
            r.get(0)
        })
        .ok();

    conn.execute(
        "INSERT OR REPLACE INTO shared_skills (skill_id, skill_name, creator_tag, shared_at, toml_content)
         VALUES (?1, ?2, ?3, ?4, ?5)",
        rusqlite::params![skill_id, skill_name, tag, now, toml_content],
    )?;

    // Initialize credits row
    let shared_id = conn.last_insert_rowid();
    conn.execute(
        "INSERT OR IGNORE INTO sharing_credits (shared_skill_id, activations, tokens_saved, credits_earned, updated_at)
         VALUES (?1, 0, 0.0, 0.0, ?2)",
        rusqlite::params![shared_id, now],
    )?;

    Ok(())
}

/// Update credits for all shared skills based on current activation stats.
pub fn update_credits(conn: &Connection) -> Result<()> {
    init_sharing_schema(conn)?;

    let mut stmt = conn
        .prepare("SELECT ss.id, ss.skill_id FROM shared_skills ss WHERE ss.skill_id IS NOT NULL")?;

    let rows: Vec<(i64, i64)> = stmt
        .query_map([], |r| Ok((r.get(0)?, r.get(1)?)))?
        .filter_map(|r| r.ok())
        .collect();

    let now = crate::skills::chrono_now();

    for (shared_id, skill_id) in rows {
        let activations: i64 = conn
            .query_row(
                "SELECT COALESCE(activated, 0) FROM skill_stats WHERE skill_id = ?1",
                [skill_id],
                |r| r.get(0),
            )
            .unwrap_or(0);

        let tokens_saved = activations as f64 * TOKENS_PER_ACTIVATION;
        let credits = tokens_saved * CREATOR_CREDIT_RATE;

        conn.execute(
            "UPDATE sharing_credits SET activations = ?2, tokens_saved = ?3, credits_earned = ?4, updated_at = ?5
             WHERE shared_skill_id = ?1",
            rusqlite::params![shared_id, activations, tokens_saved, credits, now],
        )?;
    }

    Ok(())
}

/// Get a summary of all sharing credits for this user.
pub fn credit_summary(conn: &Connection) -> Result<CreditSummary> {
    init_sharing_schema(conn)?;

    let skills_shared: i64 = conn
        .query_row("SELECT COUNT(*) FROM shared_skills", [], |r| r.get(0))
        .unwrap_or(0);

    let (total_activations, total_tokens_saved, total_credits_earned) = conn
        .query_row(
            "SELECT COALESCE(SUM(activations), 0), COALESCE(SUM(tokens_saved), 0.0),
                    COALESCE(SUM(credits_earned), 0.0)
             FROM sharing_credits",
            [],
            |r| {
                Ok((
                    r.get::<_, i64>(0)?,
                    r.get::<_, f64>(1)?,
                    r.get::<_, f64>(2)?,
                ))
            },
        )
        .unwrap_or((0, 0.0, 0.0));

    Ok(CreditSummary {
        skills_shared,
        total_activations,
        total_tokens_saved,
        total_credits_earned,
    })
}

/// List all shared skills with their credit details.
pub fn list_shared(conn: &Connection) -> Result<Vec<SharedSkill>> {
    init_sharing_schema(conn)?;

    let mut stmt = conn.prepare(
        "SELECT ss.skill_name, ss.shared_at, ss.creator_tag,
                COALESCE(sc.activations, 0), COALESCE(sc.tokens_saved, 0.0),
                COALESCE(sc.credits_earned, 0.0)
         FROM shared_skills ss
         LEFT JOIN sharing_credits sc ON sc.shared_skill_id = ss.id
         ORDER BY sc.credits_earned DESC",
    )?;

    let rows = stmt
        .query_map([], |r| {
            Ok(SharedSkill {
                skill_name: r.get(0)?,
                shared_at: r.get(1)?,
                creator_tag: r.get(2)?,
                total_activations: r.get(3)?,
                total_tokens_saved: r.get(4)?,
                creator_credits: r.get(5)?,
            })
        })?
        .filter_map(|r| r.ok())
        .collect();

    Ok(rows)
}

/// Export a skill as TOML content (same format as `precc skills export`).
pub fn export_skill_toml(conn: &Connection, skill_name: &str) -> Result<String> {
    let (id, description, source, priority): (i64, String, String, i64) = conn
        .query_row(
            "SELECT id, description, source, priority FROM skills WHERE name = ?1",
            [skill_name],
            |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?, r.get(3)?)),
        )
        .context("skill not found")?;

    let mut toml = format!(
        "[skill]\nname = {:?}\ndescription = {:?}\nsource = {:?}\npriority = {}\n",
        skill_name, description, source, priority
    );

    // Triggers
    let mut stmt = conn
        .prepare("SELECT trigger_type, pattern, weight FROM skill_triggers WHERE skill_id = ?1")?;
    let triggers: Vec<(String, String, f64)> = stmt
        .query_map([id], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)))?
        .filter_map(|r| r.ok())
        .collect();

    for (t, pat, w) in &triggers {
        toml.push_str(&format!(
            "\n[[triggers]]\ntype = {:?}\npattern = {:?}\nweight = {}\n",
            t, pat, w
        ));
    }

    // Actions
    let mut stmt = conn.prepare(
        "SELECT action_type, template, confidence FROM skill_actions WHERE skill_id = ?1",
    )?;
    let actions: Vec<(String, String, f64)> = stmt
        .query_map([id], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)))?
        .filter_map(|r| r.ok())
        .collect();

    for (t, tmpl, c) in &actions {
        toml.push_str(&format!(
            "\n[[actions]]\ntype = {:?}\ntemplate = {:?}\nconfidence = {}\n",
            t, tmpl, c
        ));
    }

    Ok(toml)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db;

    fn test_db() -> Connection {
        let dir = tempfile::tempdir().unwrap();
        let conn = db::open_heuristics(dir.path()).unwrap();
        std::mem::forget(dir);
        conn
    }

    #[test]
    fn schema_creation_is_idempotent() {
        let conn = test_db();
        init_sharing_schema(&conn).unwrap();
        init_sharing_schema(&conn).unwrap(); // second call should not fail
    }

    #[test]
    fn record_and_list_shared_skill() {
        let conn = test_db();
        let now = crate::skills::chrono_now();

        // Insert a skill first
        conn.execute(
            "INSERT INTO skills (name, description, source, priority, created_at, updated_at)
             VALUES ('test-skill', 'test', 'mined', 200, ?1, ?1)",
            [&now],
        )
        .unwrap();

        record_share(&conn, "test-skill", "[skill]\nname = \"test-skill\"").unwrap();

        let shared = list_shared(&conn).unwrap();
        assert_eq!(shared.len(), 1);
        assert_eq!(shared[0].skill_name, "test-skill");
    }

    #[test]
    fn credits_accumulate_from_activations() {
        let conn = test_db();
        let now = crate::skills::chrono_now();

        conn.execute(
            "INSERT INTO skills (name, description, source, priority, created_at, updated_at)
             VALUES ('credit-skill', 'test', 'mined', 200, ?1, ?1)",
            [&now],
        )
        .unwrap();
        let sid = conn.last_insert_rowid();
        conn.execute(
            "INSERT INTO skill_stats (skill_id, activated, succeeded, failed)
             VALUES (?1, 100, 95, 5)",
            [sid],
        )
        .unwrap();

        record_share(&conn, "credit-skill", "toml").unwrap();
        update_credits(&conn).unwrap();

        let summary = credit_summary(&conn).unwrap();
        assert_eq!(summary.skills_shared, 1);
        assert_eq!(summary.total_activations, 100);
        // 100 * 250 * 0.10 = 2500 credits
        assert!((summary.total_credits_earned - 2500.0).abs() < 0.01);
    }
}
