//! PRECC mail-agent: send reports and documents via SMTP.
//!
//! # Configuration
//! Config file: `~/.config/precc/mail.toml`
//! ```toml
//! [smtp]
//! host = "smtp.gmail.com"
//! port = 587
//! username = "you@gmail.com"
//! password = "app-password"
//! from = "you@gmail.com"       # defaults to username if omitted
//! ```

use anyhow::{bail, Context, Result};
use lettre::message::header::ContentType;
use lettre::message::{Attachment, MultiPart, SinglePart};
use lettre::transport::smtp::authentication::Credentials;
use lettre::{Message, SmtpTransport, Transport};
use serde::Deserialize;
use std::path::{Path, PathBuf};

#[derive(Deserialize, Debug)]
struct MailConfig {
    smtp: SmtpConfig,
}

#[derive(Deserialize, Debug)]
struct SmtpConfig {
    host: String,
    #[serde(default = "default_port")]
    port: u16,
    username: String,
    password: String,
    from: Option<String>,
}

fn default_port() -> u16 {
    587
}

/// Send an email with optional file attachments.
pub fn send_mail(to: &str, subject: &str, body: &str, attachments: &[PathBuf]) -> Result<()> {
    let cfg = load_config()?;
    let from = cfg
        .smtp
        .from
        .as_deref()
        .unwrap_or(&cfg.smtp.username)
        .to_string();

    // Build message
    let mut mp = MultiPart::mixed().singlepart(
        SinglePart::builder()
            .header(ContentType::TEXT_PLAIN)
            .body(body.to_string()),
    );

    for path in attachments {
        let data = std::fs::read(path)
            .with_context(|| format!("reading attachment {}", path.display()))?;
        let filename = path
            .file_name()
            .map(|n| n.to_string_lossy().to_string())
            .unwrap_or_else(|| "attachment".to_string());
        let content_type = guess_content_type(path);
        mp = mp.singlepart(Attachment::new(filename).body(data, content_type));
    }

    let email = Message::builder()
        .from(from.parse().context("invalid from address")?)
        .to(to.parse().context("invalid to address")?)
        .subject(subject)
        .multipart(mp)
        .context("building email message")?;

    let creds = Credentials::new(cfg.smtp.username.clone(), cfg.smtp.password.clone());

    let mailer = SmtpTransport::starttls_relay(&cfg.smtp.host)
        .context("connecting to SMTP")?
        .port(cfg.smtp.port)
        .credentials(creds)
        .build();

    mailer.send(&email).context("sending email")?;
    Ok(())
}

/// Interactive setup: write mail.toml config.
pub fn cmd_mail_setup() -> Result<()> {
    let path = config_path()?;
    if path.exists() {
        println!("Mail config already exists at {}", path.display());
        println!("Edit it directly to update SMTP settings.");
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let template = r#"[smtp]
host = "smtp.gmail.com"
port = 587
username = "you@example.com"
password = "your-app-password"
# from = "you@example.com"  # defaults to username
"#;
    std::fs::write(&path, template)?;
    println!("Created mail config at {}", path.display());
    println!("Edit it with your SMTP credentials, then run `precc mail send`.");
    Ok(())
}

/// Send a PRECC savings report to a recipient.
pub fn cmd_mail_report(to: &str, attachments: &[PathBuf]) -> Result<()> {
    let subject = "PRECC Token Savings Report";
    let body = "Please find your PRECC token savings report attached.\n\n\
        Generated by PRECC — Predictive Error Correction for Claude Code.\n\
        https://github.com/yijunyu/precc-cc\n";

    send_mail(to, subject, body, attachments)?;
    println!("Report sent to {to}");
    Ok(())
}

fn load_config() -> Result<MailConfig> {
    let path = config_path()?;
    if !path.exists() {
        bail!(
            "Mail config not found at {}.\nRun `precc mail setup` to create it.",
            path.display()
        );
    }
    let raw =
        std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    toml::from_str(&raw).context("parsing mail config")
}

fn config_path() -> Result<PathBuf> {
    let home = std::env::var("HOME").map_err(|_| anyhow::anyhow!("HOME not set"))?;
    Ok(PathBuf::from(home)
        .join(".config")
        .join("precc")
        .join("mail.toml"))
}

fn guess_content_type(path: &Path) -> ContentType {
    match path.extension().and_then(|e| e.to_str()) {
        Some("pdf") => ContentType::parse("application/pdf").unwrap(),
        Some("pptx") => ContentType::parse(
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        )
        .unwrap(),
        Some("gif") => ContentType::parse("image/gif").unwrap(),
        Some("png") => ContentType::parse("image/png").unwrap(),
        Some("md") => ContentType::parse("text/markdown").unwrap(),
        Some("txt") => ContentType::TEXT_PLAIN,
        _ => ContentType::parse("application/octet-stream").unwrap(),
    }
}
